### ISSUE TITLE
Links are not reloaded when only the label has changed

### ISSUE THREAD

**Issue by vincentfougeras** [swimlane/ngx-graph#100]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

When updating the [links] input, links are only updated if their source or target has changed. If a link's label changes but not its source nor its target, it does not trigger any update on the link.

The problem seems to originate from here : https://github.com/swimlane/ngx-graph/blob/master/src/graph/graph.component.ts#L392

**Expected behavior**
The link should be updated if its label changes.

**Please tell us about your environment:**

* **ngx-graph version:** 5.1.0

* **Angular version:** 6.0.6

**Comment by isaacplmann** [comment]
If you've found the line that's causing the problem, we'd be happy to get a PR that fixes the issue.  Let me know if you need help getting the project set up to contribute a PR.

**Comment by freemanlam** [comment]
Same issue here

**Comment by assafsun** [comment]
Saw it also. I have an idea for a fix.

**Comment by assafsun** [comment]
I'm looking at this issue.

A workaround for this can be creating an object that pass be reference and using it inside your link template.
For example: add to the link "model"
model: {
label: "test"
}

**Comment by assafsun** [comment]
Closing this issue as the label can be on a reference object inside the link where the hosting component can put it inside the link.

Let me know for any issues.

**Comment by andrespinov** [comment]
@assafsun I tried adding the object in the link but had no success. I am using a boolean property instead a label (but tried using a String and didn't work either). 

*ngx-graph** version: 5.5.0*
*Angular version: 7.2.11*

**Comment by Pasha73** [comment]
@andrespinov Do you have any deision about this issue?
