### ISSUE TITLE
version mismatch in Angular4

### ISSUE THREAD

**Issue by evemaria** [swimlane/ngx-graph#107]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
ERROR in Metadata version mismatch for module E:/formulary_workFlow/node_modules
/@swimlane/ngx-charts/release/index.d.ts, found version 4, expected 3,

**Expected behavior**
ngx-charts should work with Angular4

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
ngx-charts not working in Angular4

* **ngx-graph version:** - "^5.1.0",
* **Angular version:** - 6.0.8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
This is the ngx-graph repo. Did you mean to open this in ngx-charts?

ngx-charts v6.1.0 is compatible with angular 4, you may want to try using that. But I would suggest upgrading to angular 6 as soon as possible, so you're able to use the latest ngx-charts version.
