### ISSUE TITLE
Cannot scroll page even after disabling zoom

### ISSUE THREAD

**Issue by CoreyCole** [swimlane/ngx-graph#110]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When there is other content on the page, say an `ngx-bar-chart`, scrolling up and down on the page does not work even after disabling zoom. 

**Expected behavior**

Scrolling should work normally if it is not being used for zooming on the graph.

**Reproduction of the problem**

See stackblitz: https://stackblitz.com/edit/angular-tcg69j

**What is the motivation / use case for changing the behavior?**

Integrating the `ngx-graph` into a page alongside other components

**Please tell us about your environment:**

OSX, Google Chrome, Angular cli

* **ngx-graph version:** x.x.x

```
    "@swimlane/ngx-charts": "^8.1.0",
    "@swimlane/ngx-graph": "^5.1.0",
```
* **Angular version:** x.x.x

```
    "@angular/animations": "^6.0.9",
    "@angular/cdk": "^6.3.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/material": "^6.3.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
```
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
```
    "typescript": "~2.7.2"
```

**Comment by CoreyCole** [comment]
The scroll bar on the right of the page works, but using the scroll wheel does not. Is there any way to revert to the default behavior for the scroll wheel?

**Comment by CoreyCole** [comment]
It looks like the source of the problem may be here
https://github.com/swimlane/ngx-graph/blob/fd46d161a83c1cde7aeb6231f225cffb1fca5bac/src/graph/mouse-wheel.directive.ts

Where you guys call preventDefault() on scroll events

**Comment by CoreyCole** [comment]
Ah, if you disable pointer events the scroll wheel works:
```
ngx-graph {
  pointer-events: none;
}
```

I'm not going to close this issue because that is kind of a workaround. I now can't click on nodes to call the select function.

**Comment by toski112** [comment]
Any ideas to resolve this ?

**Comment by assafsun** [comment]
Hi,

Which version are you using today?

Besides trying to update pointer events and ideas in this direction, as a workaround we can ignore zoom when zoom it called (scroll or value) in  case the Boolean is disabled.
For example: checking if enableZoom is true when onZoom is called.
Adding to https://github.com/swimlane/ngx-graph/blob/5.x/src/graph/graph.component.ts#L741 the additional Boolean check.

**Comment by toski112** [comment]
I am using the latest version, the problem appears when the graph is rendered and the zoom is off. Scroll on the page works until you move to the graph. I can not turn off the pointer events, because I have the attached function (click) on the nodes.

**Comment by toski112** [comment]
I've solved the problem, we add the class pointer-events: none to the container with the graph, and in each element that has to be clickable in the graph should have a style allowing for mouse events eg pointer-events: all. Thanks to this, the graph does not interfere with scrolling the page, but you can click on its elements. I hope it will be useful to someone.

**Comment by assafsun** [comment]
Thanks for the update.

I'm closing this issue as you offered a solution which can help in this specific case.
