### ISSUE TITLE
Options for link labeling

### ISSUE THREAD

**Issue by Chamicka** [swimlane/ngx-graph#112]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here
```
I would love to have more options regarding how the links' labels are displayed. 
Currently it seems using SVG's Text and Textpath features are the way to do it, but this method is a bit inconsistent.
For example, I would like to be able to display all link labels in the graph below horizontally, and I could not come up with a good solution on my own.

Thanks in advance !

![image](https://user-images.githubusercontent.com/28919437/43784789-3971be0c-9a65-11e8-9348-3d7d8f5458b3.png)

**Comment by assafsun** [comment]
Please look at my latest PR which may fit your requirements.
https://github.com/swimlane/ngx-graph/pull/138

**Comment by assafsun** [comment]
Please check the latest version 5.2.1 and see it helps. 
You can add your own template and decide how it looks.
I'm closing this issue for now, please update for any issue.
