### ISSUE TITLE
change the node template: use the html tags

### ISSUE THREAD

**Issue by skandar-benali** [swimlane/ngx-graph#114]
How can I change the node template into a custom html/css template away from the original svg tag?

**Comment by assafsun** [comment]
You can add forienObject element on the entire node and inside of it add you HTML objects.

**Comment by assafsun** [comment]
Example which will works also on edge:
        <ng-template #nodeTemplate let-node>
                <svg:g class="node" xmlns="http://www.w3.org/2000/svg" xmlns:href="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
                    <foreignObject class="foreignObject" width="<number>" height="<number>">
                        <xhtml:div xmlns="http://www.w3.org/1999/xhtml">
                              //Content
                        </xhtml:div>
                    </foreignObject>
                </svg:g> 
        </ng-template>

**Comment by danielkalfas** [comment]
Is it also possible to use an image which is NOT from an external URL? this works perfect for an external URL, but i need to show some images which i only have local on my computer.
 <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
          <image xlink:href="https://images.techhive.com/images/article/2016/10/firefox-logo-100690302- 
           large.jpg"  height="50" width="50" />
  </svg>
Any suggestions?

**Comment by assafsun** [comment]
@danielkalfas Yes. I'm using SVG images and it works very nice.
The advantage of SVG is that on zoom change, the pixel image is not changed

**Comment by bharatrawat000** [comment]
> You can add forienObject element on the entire node and inside of it add you HTML objects.

```
<ng-template #nodeTemplate let-node>
  <svg:foreignObject>
    <div>Your HTML content here</div>
  </svg:foreignObject>
</ng-template>
```
