### ISSUE TITLE
Edge labels not visible in any browser except chrome. In chrome long text is hidden behind nodes.

### ISSUE THREAD

**Issue by tom-riddle** [swimlane/ngx-graph#122]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Edge labels are not visible in any browser except chrome. Even after changing color of textPath, the label does not appear.

**Expected behavior**
Edge labels should be visible

**Reproduction of the problem**

      <ng-template #linkTemplate let-link>
        <svg:g class="edge" (click)="editTransition($event, link)">
          <svg:path class="line" stroke-width="2" stroke="#bebebe" stroke-dasharray="2,2" marker-end="url(#arrow)">
          </svg:path>
          <svg:text class="edge-label" text-anchor="middle">
            <textPath class="text-path" [attr.href]="'#' + link.id" style="fill: #4c4c4c;" [style.dominant-baseline]="link.dominantBaseline"
              startOffset="50%">
              {{link.label}}
            </textPath>
          </svg:text>
        </svg:g>
      </ng-template>

The label appears on chrome, but in case of long text , the text appears cut.
On other browsers, the text does not even appear.
Another issue exists about the edge labels visibilty, but that seems to be a color issue.

* **ngx-graph version:** x.x.x
4.3.0
(5.1.0 not working on firefox, couldn't try)

* **Angular version:** x.x.x
6

**Comment by assafsun** [comment]
@tom-riddle can you please check the latest version? it should work on firefox

**Comment by assafsun** [comment]
Closing this issue and waiting for reply.
Please update after checking the browser support with firefox and latest version 5.2.1

**Comment by daniel-luna-gonzalez** [comment]
Hi I'm using in my package.json the below version 
"@swimlane/ngx-graph": "^5.4.1"

Indeed I can't see the link labels using firefox and safari, only with chrome works.


`<div *ngIf="nodes.length > 0">
    <h2 class="title">Flujo del asunto</h2>
  <ngx-graph
          class="chart-container"
          [view]="view"
          [legend]="showLegend"
          [links]="links"
          (legendLabelClick)="onLegendLabelClick($event)"
          [nodes]="nodes"
          [scheme]="colorScheme"
          [orientation] = orientation
          [curve] = curve
          [autoZoom] = autoZoom
          [enableZoom]= enableZoom
          [panOnZoom]="panOnZoom"
          [autoCenter]="autoCenter"
          (select)="select($event)">

    <ng-template #defsTemplate>
      <svg:marker id="arrow" viewBox="0 -5 10 10" refX="8" refY="0" markerWidth="4" markerHeight="4" orient="auto">
        <svg:path d="M0,-5L10,0L0,5" class="arrow-head" />
      </svg:marker>
    </ng-template>

    <ng-template #nodeTemplate let-node>
      <svg:g class="node"
             ngx-tooltip
             [tooltipPlacement]="'top'"
             [tooltipType]="'tooltip'"
             [tooltipTitle]="node.label">
        <svg:rect [attr.width]="node.width" [attr.height]="node.height" [attr.fill]="node.options.color" />
        <svg:text alignment-baseline="central" [attr.x]="10" [attr.y]="node.height / 2">{{ node.label }}</svg:text>
      </svg:g>
    </ng-template>

    <ng-template #linkTemplate let-link>
      <svg:g class="edge">
        <svg:path
                class="line"
                stroke-width="2"
                marker-end="url(#arrow)" >
        </svg:path>
        <svg:text
                class="edge-label"
                text-anchor="middle">
          <textPath
                  style="fill: #666; margin-bottom: 10px"
                  [attr.href]="'#' + link.id"
                  [style.dominant-baseline]="link.dominantBaseline"
                  startOffset="50%">
            daniel
          </textPath>
        </svg:text>
      </svg:g>
    </ng-template>

  </ngx-graph>
</div>`

You can see the below example with the reported browsers.

https://stackblitz.com/edit/ngx-graph-simple-example


Regards
