### ISSUE TITLE
Cant find source of node.height and node.width in demo

### ISSUE THREAD

**Issue by joncorrin** [swimlane/ngx-graph#127]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Im looking at the demo, which contains node.width and node.height for the size values, but Im not sure where this is coming from or why its not working for me. 
**Expected behavior**

I expected the values to be in the .ts file or for them to be rendered using the same code but theyre not.
**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-graph version:** x.x.x

* **Angular version:** x.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
The component populates those values itself after measuring them. Since you can pass templates for nodes, ngx-graph measures the node after it is rendered and recalculates the layout based on those dimension. That is where the width and height properties are coming from.
