### ISSUE TITLE
PanOnZoom not working 

### ISSUE THREAD

**Issue by TheAlonso95** [swimlane/ngx-graph#128]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Hello :) I've set the PanOnZoom propertie to true but whenever I try to scroll in it will zoom in the top left corner of the nodes "container" (and yes I know that the default value for the panOnZoom is set to true.)
I'm just triyng everting to make it work but I'm not able to do it...

**Expected behavior**
Should be like your demo...

* **ngx-graph version:** ^5.1.1

* **Angular version:** 6.1.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by RonjaKnudtsen** [comment]
I have the same issue.

**Comment by assafsun** [comment]
Fixed on version 6.x and version 5.x

**Comment by assafsun** [comment]
Fixed on the latest version 5.2.1

**Comment by rahul-winner** [comment]
@assafsun is "panOnZoom" working on demo page : https://swimlane.github.io/ngx-graph/?
I am not able to see 'panOnZoom' on your demo. Am I missing anything?

Thank you.

**Comment by rahul-winner** [comment]
@assafsun actually it is not working in our application as well. We are using ngx-graph@5.3.0

I noticed we got to override the "pan" method as follows in order to make it work. 

```
    pan(x: number, y: number): void {
        this.transformationMatrix = transform(this.transformationMatrix, translate(x, y));
        this.updateTransform();
    } 
```

Should we open a new issue for tracking it?

**Comment by assafsun** [comment]
Please open a new issue as a fix was introduce to this thread.

Thanks.

**Comment by rahul-winner** [comment]
filed a new issue #153

Thank you @assafsun
