### ISSUE TITLE
Additional path routing selections

### ISSUE THREAD

**Issue by alindberg** [swimlane/ngx-graph#129]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Additional path routing algorithms allowing for standard "Visio" style path behavior

**What is the motivation / use case for changing the behavior?**
The existing GitHub project, [Draw2D](https://github.com/freegroup/draw2d) has a number of path selections.

A good demonstration of path selections can be found at https://qiao.github.io/PathFinding.js/visual/.  

**Please tell us about your environment:**
I am running Angular 7
<pre>Angular CLI: 7.0.2
Node: 8.11.2
OS: win32 x64
Angular: 7.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.2
@angular-devkit/build-angular     0.10.2
@angular-devkit/build-optimizer   0.10.2
@angular-devkit/build-webpack     0.10.2
@angular-devkit/core              7.0.2
@angular-devkit/schematics        7.0.2
@angular/cdk                      7.0.1
@angular/cli                      7.0.2
@ngtools/webpack                  7.0.2
@schematics/angular               7.0.2
@schematics/update                0.10.2
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1

yarn list --pattern swim
yarn list v1.10.1
    @swimlane/ngx-charts@8.1.0
    @swimlane/ngx-graph@5.1.1
</pre>

Thank you for your good work.

**Comment by assafsun** [comment]
You can change the dagre algorithm by passing the ranker option as part of the dagre settings,
More information can be found in here:
https://github.com/dagrejs/dagre/wiki#configuring-the-layout

We can't add additional path algorithms when we are using a single layout engine

In addition, once version 6 will be release, you will be able to set your layout so you will be able to define a layout with your path implementation.
The new layout with the fact that you can pass your own curve line UI can give you great abilities that depended on your customization.

Hope that it helps! closing it for now.
