### ISSUE TITLE
Focus on node from legend list (Pan to and zoom)

### ISSUE THREAD

**Issue by RonjaKnudtsen** [swimlane/ngx-graph#130]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```
**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
I have a very large organizational chart. And I want to be able to use the legend list as a reference list to find items in the chart.  So the users can click on the legend and the chart would zoom to and pan (or just pan) to the node.

I have been able to utilize the (legendLabelClick) input which is very handy. 
But I have no way of telling the graph to pan to a specific place, or to pan at all. 

* **ngx-graph version:** 5.1.1

* **Angular version:** Angular 6.

* **Language:** [all ]

**Comment by marjan-georgiev** [comment]
That is a valid use case. I would add a `centerOnNode(id: string)` method to the graph that would pan to bring the passed node to the center of the view.

PR's welcome

**Comment by assafsun** [comment]
@marjan-georgiev  and I pushed this support to version 5.x

**Comment by rahul-winner** [comment]
@assafsun which method did we add for supporting this use case? I could not find any method with name "centerOnNode" in v 5.x

Thank you.

**Comment by assafsun** [comment]
@rahul-winner you can find a new input binding called zoomToNode (I need to improve this name :) ).

In addition, you can find the demo app (which is 5.2.1 version) an example of how it works 
![image](https://user-images.githubusercontent.com/33118325/50732980-61c6f300-118d-11e9-8c23-9d196595501c.png)
