### ISSUE TITLE
Prevent legends colors/order to change when reloading graph

### ISSUE THREAD

**Issue by doorman02** [swimlane/ngx-graph#131]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

When reloading the graph the colors and order  of the legends change which is a bit confusing for the user. Could also be related to that not all legends are displayed in the beginning and new legends are added when reloading the graph with additional data.

**Expected behavior**

Would be nice if it´s possible to fix the colors/order of the legends

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

More user friendly and readable

**Please tell us about your environment:**

* **ngx-graph version:** x.x.x

Latest
* **Angular version:** x.x.x

Latest
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by marjan-georgiev** [comment]
@doorman02 we have deprecating the `legend` feature in ngx-graph v6 and will be removing it in the next major version. If you need a legend, you can build one in your component, outside of the graph.

To persist colors, you could use custom node templates, so you have full control of the look and feel of your nodes. The basic shapes and colors are there only for the most basic use cases. Please look at the documentation to see how you can use templates: https://swimlane.github.io/ngx-graph/#demos/interactive-demo#interactive-demo
