### ISSUE TITLE
Production build fails

### ISSUE THREAD

**Issue by arcteezy** [swimlane/ngx-graph#134]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Deployed build fails while it shows no error during development. 

**Reproduction of the problem**
When loading the build, it is stacking up errors in the console and fails to show the graph.

![screenshot from 2018-12-13 13-03-37](https://user-images.githubusercontent.com/16623349/49922780-b1403900-fed7-11e8-87cc-73f4a969ba61.png)

I guess it is looking for some provider. But none is described in the demo or package. Here's my app.module.ts : 
```
import { NgxChartsModule } from '@swimlane/ngx-charts';
import { NgxGraphModule } from '@swimlane/ngx-graph';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
...
imports: [
    ...,
    NgxChartsModule,
    NgxGraphModule,
    BrowserAnimationsModule
]
```

**Please tell us about your environment:**
Build running on Apache server.

* **ngx-graph version:** 5.1.2

* **Angular version:** 6.1.0

**Comment by arcteezy** [comment]
Used `--aot=false` and `--build-optimizer=false` flags to bypass the issue.

**Comment by arcteezy** [comment]
The above solution solved the build error but it is causing a huge loading time.

**Comment by assafsun** [comment]
Closing this for now.

Please update if there is an issue here, please keep in mind that we are going towards version 6.

**Comment by daniel-luna-gonzalez** [comment]
I have the same issue when I compile or build in production mode

> {
  "name": "graph",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.1.6",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "5.2.8",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "5.2.8",
    "@swimlane/ngx-charts": "6.1.0",
    "@swimlane/ngx-graph": "5.0.0",
    "core-js": "2.6.5",
    "d3-array": "1.2.1",
    "d3-brush": "1.0.4",
    "d3-color": "1.1.0",
    "d3-force": "1.1.0",
    "d3-format": "1.2.2",
    "d3-hierarchy": "1.1.6",
    "d3-interpolate": "1.1.6",
    "d3-scale": "2.0.0",
    "d3-selection": "1.3.0",
    "d3-shape": "1.2.0",
    "d3-time-format": "2.1.1",
    "d3-transition": "1.1.1",
    "rxjs": "^6.0.0",
    "zone.js": "0.9.0",
    "rxjs-compat": "^6.5.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.11.0",
    "@angular/cli": "~7.1.2",
    "@angular/compiler-cli": "~7.1.0",
    "@angular/language-service": "~7.1.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }
}


ng serve --prod --source-map

I have the below output

<img width="603" alt="image" src="https://user-images.githubusercontent.com/13126516/56902288-92de7280-6a5f-11e9-8581-d1e401a01124.png">


<img width="604" alt="image" src="https://user-images.githubusercontent.com/13126516/56902306-9d007100-6a5f-11e9-8e65-882a195e3507.png">


When I run the below command it works! 

> ng

 serve

**Comment by arcteezy** [comment]
@daniel-luna-gonzalez Update the package to the latest version.
