### ISSUE TITLE
Arrange color-code node position wise

### ISSUE THREAD

**Issue by nbora98** [swimlane/ngx-graph#135]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
nodecolor1 = 'red';
nodecolor2= 'yellow';
nodecolor3='blue';
nodecolor4='black';
colorScheme: any = {
    domain: [ nodecolor1, nodecolor2, nodecolor3, nodecolor4 ]
      }
 If i set the above color-code i.e. fix color for particular node then its not working properly. Its setting color randomly. 

**Expected behavior**
I want to set suppose red color for node1, yellow for node2 and so on.

**Please tell us about your environment:**

* **OS: Windows 10

* **ngx-graph version: 5.1.2

* **Angular version:** Angular 6

* **Browser:** [ Chrome 71.0.3578.98 (Official Build) (64-bit)  ]

* **Language:** [ TypeScript 3.1.3 ]

**Comment by assafsun** [comment]
Why not setting the nodes colors from outside ngx-graph?

Set the attr.fill or other css property on the node itself and not use the colors that ngx-graph provide.

**Comment by nbora98** [comment]
Okay, Thanks for the reply.

**Comment by assafsun** [comment]
Closing this for now. Thanks.
