### ISSUE TITLE
distance between two nodes

### ISSUE THREAD

**Issue by self-ads** [swimlane/ngx-graph#136]
the link between two nodes had the same width, is there a way to add the width or edited it ?

**Comment by assafsun** [comment]
Is changing the link stroke-width or any other css property helps?

**Comment by self-ads** [comment]
> Is changing the link stroke-width or any other css property helps?

stroke-wisth makes the line bold

**Comment by assafsun** [comment]
Does your question related to giving the line additional space in order to better catch the click events? 
If it is, than we (my internal team) saw it also and trying to fix it.
You can check the latest support of ngx-graph which give you the ability to add a custom UI on the link which may give your links a clicking area.

**Comment by self-ads** [comment]
my problem is a nead more space for the label, when i show  a long value just a part of it is visibile i did spilt into lines but it's not good to look

**Comment by self-ads** [comment]
how can i use it ?

**Comment by assafsun** [comment]
Use the dagre layout option in order to set the ranksep value to set the vertical distance between the nodes which will affect the length of the links.
Please update for any problems.

If it doesn't work, please let me know.

**Comment by godrose** [comment]
@assafsun Can you point to any sample code? Thanks.

**Comment by carlosalvarez91** [comment]
html

```
     <ngx-graph
       ...
        [dagreLayout]="dagreLayout"
        >

```

component
```

    import { DagreLayout } from '@swimlane/ngx-graph/release/graph/graph.component'
    
     dagreLayout:DagreLayout = {
          ranksep:50 //set here the value you want
      }

```

I hope this helps @godrose

**Comment by gouthammanigonda** [comment]
Can we have same thing for 'colaForceDirected' layout as well?
