### ISSUE TITLE
build fails when the app is built prod environment 

### ISSUE THREAD

**Issue by krishnaraghavendra** [swimlane/ngx-graph#139]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Building the app with AOT fails and gives the bellow error

Couldn't resolve resource ./graph.component.html from node_modules/@swimlane/ngx-graph/release/graph/graph.component.d.ts 

**Expected behavior**
Should build without any issues 

**Reproduction of the problem**
Building the app without AOT/ Build optimizer  flags will build correctly. But if we use AOT the build fails with above error

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-graph version: 5.2.0

* **Angular version:** 6.0.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by assafsun** [comment]
Thanks. Fix is in progress

**Comment by assafsun** [comment]
https://github.com/swimlane/ngx-graph/pull/140
