### ISSUE TITLE
Allow node types/categories

### ISSUE THREAD

**Issue by waltersung** [swimlane/ngx-graph#142]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Currently nodes added to a graph cannot be distinguished by type, also each node is added as an item in the legend which is not that useful

**Expected behavior**
Nodes are identified with a 'type' which would be also displayed in the legend.
Each type could be rendered with a different node template (to customise colour, shape, etc.) 

*For example* 
A graph of People may have node types for Gender and the legend would show an entry for each gender (not each node)

Legend interactions can then become meaningful - for example click the legend to highlight all nodes of a type

**What is the motivation / use case for changing the behavior?**
This would improve the usefulness of the graph

**Comment by assafsun** [comment]
You can add you own "model" object on each node object where you can add there you own variables and control it from outside the graph.
In the model object you can pass a type and set the template based on on this type with switch on it.

If I understand, want an API from the graph to set it right?

**Comment by waltersung** [comment]
This approach works for node appearance, but it would also be nice to have functionality integrated with the Legend as well.
