### ISSUE TITLE
Nodes not emitting 'activate' or 'deactivate' events

### ISSUE THREAD

**Issue by waltersung** [swimlane/ngx-graph#144]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Nodes in a graph should emit 'activate' and 'deactivate' events but do not.
The existing event emitters in the code are only emitting events when the mouse enters/leaves *Legend* entries

https://github.com/swimlane/ngx-graph/blob/70d1a8fee68ba600d9ab69b762b04258fcf36baf/src/graph/graph.component.ts#L142-L143

In the ngx-chart definition label interactions call the onActivate and onDeactivate functions:
https://github.com/swimlane/ngx-graph/blob/70d1a8fee68ba600d9ab69b762b04258fcf36baf/src/graph/graph.component.ts#L61-L63

Node element code **does not** call the onActivate and onDeactivate event functions:
https://github.com/swimlane/ngx-graph/blob/70d1a8fee68ba600d9ab69b762b04258fcf36baf/src/graph/graph.component.ts#L93-L94

 
 
**Expected behavior**
ngx-graph **nodes** should also emit activate and deactivate events.

**Comment by assafsun** [comment]
Which ngx-graph version are you using?

**Comment by waltersung** [comment]
I am using 5.2.1 which is the current version on NPM
I am able to workaround the issue by receiving mouse events directly on the node template

**Comment by marjan-georgiev** [comment]
@waltersung we are deprecating the `activate` and `deactivate` events and will be removing them in the next major version. Your approach of registering mouse events on the node template is the correct one, and should be the one used going forward.
