### ISSUE TITLE
ngx-graph displays correctly only after resizing Chrome browser window

### ISSUE THREAD

**Issue by learnuser521** [swimlane/ngx-graph#147]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Facing the same issue reported here  #85, that was closed. It was suggested to place it outside the tab (ngx-bootstrap) but it needed for me to place it inside the tab. I also tried the other suggestion of applying the styles to the graph, it did not help either.

**Comment by assafsun** [comment]
Thanks for submitting an issue.

I read #85 but will appreciate more information and details about the problem -screen shots will help if possible.
(I closed it because a solution was offer without any response).

Did you placed the ngx-graph object in a surrounding div\container?

**Comment by learnuser521** [comment]
![chrome_2019-01-11_08-41-22](https://user-images.githubusercontent.com/26797047/51040311-c498ff80-157c-11e9-9a25-64e368c51c99.png)


I have placed ngx-graph in the modal body

**Comment by learnuser521** [comment]
I have a created an example in here https://stackblitz.com/edit/ngx-bootstrap-3xpgmb. The styles get applies once the browser is resized.

**Comment by assafsun** [comment]
Strange, It seems like the problem in the example that you sent is that the graph is draw (for the second time because we see it at load) and than the CSS apply.
The colors are coming from ngx-graph because you didn't defined anything on the css file.

when you download the repository and loads the demo app on your local environment. is it works?
Can you follow your example based on the demo code of 5.3.0 branch?

**Comment by learnuser521** [comment]
It does not work on my local environment as well. It works only when the ngx-graph is not included inside the modal/ tab. 
I looked into the code in 5.x branch, I was not sure what changes you wanted me to apply from there as the basic structure seems to the same.

**Comment by assafsun** [comment]
Just to verify, Is the demo app working? not the code from your example?

**Comment by learnuser521** [comment]
yes

**Comment by assafsun** [comment]
OK, I will try to look more at the example that you sent..

In the mean time, If the demo code is working than it means that the CSS apply without any problem.
Can you follow on this example?

**Comment by learnuser521** [comment]
I am now getting it to work by using a timeout, the graph is added to the dom after the modal has come to display. This is I feel more like a work around.  I have updated the example with the timeout. 
I really appreciate your help. Thank you.
