### ISSUE TITLE
Update required angular version

### ISSUE THREAD

**Issue by Darkheir** [swimlane/ngx-graph#15]
Hi,

Right now in the package dependencies we can find the following that are pretty restrictive.
```
"@angular/common": "~4.0.1",
"@angular/core": "~4.0.1",
```

This allows us to use at best the version 4.0.3 of Angular and right now the 4.2.3 is out.

Do you plan on updating the supported Angular versions ?

Thanks in advance.

**Comment by ericsvendsen** [comment]
FWIW I'm running this using the lastest Angular and everything seems fine. I had to fork the repo for other reasons so I changed my version of the ngx-charts-dag package.json file to the following:
```
"@angular/common": "^4.0.1",
"@angular/core": "^4.0.1",
```
But yeah it would be nice if this could get updated on their end too.

**Comment by pedrocleto** [comment]
For me some animations on the line chart don't work with 4.4.3 version of angular specially the tooltips and that highlight line.
