### ISSUE TITLE
ngx-graph fails in production 

### ISSUE THREAD

**Issue by learnuser521** [swimlane/ngx-graph#150]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
ngx-graph fails in production. Getting a Static injector error (attached image of the error). 
It however works locally and works in production while using 
"ng build --prod --aot=false --build optimizer=false".
 It mostly is the same issue mentioned in https://github.com/swimlane/ngx-graph/issues/105

Angular - 7.2 
ngx-graph - 5.4
ngx-charts - 8.1

![chrome_2019-01-16_11-05-40](https://user-images.githubusercontent.com/26797047/51267018-60ae7680-1982-11e9-81c0-4ed78657fd9a.png)

**Comment by learnuser521** [comment]
![code_2019-01-16_11-17-40](https://user-images.githubusercontent.com/26797047/51267299-fc3fe700-1982-11e9-8221-3d68bfbd997b.png)


Since I have Angular 7 installed, I get warnings while installing the npm packages. Not sure if this is would be helpful but thought will share it if it will be of any help.

**Comment by assafsun** [comment]
Regrading the warnings version 6 will support Angular 7

**Comment by learnuser521** [comment]
Is version 6 available ? I thought 5.4 was released yesterday and was the latest.

**Comment by zolee** [comment]
I think this issue is related to #145 . Could you check it?

**Comment by learnuser521** [comment]
@zolee I looked into #145. It might be the same but I am not sure. However I tried ng serve --aot locally and it is working fine but it fails for me locally when I execute ng serve --prod or with a production build (ng build --prod). I am not using the tooltip in the graph.

**Comment by learnuser521** [comment]
@zolee - The issue seems to be with ngx-charts which uses TooltipService. A work around for now to get ngx-graph to work in production is to use "import * as shape from 'd3';" instead "import * as shape from 'd3-shape';". This will increase the project build size but I could get a better solution.
