### ISSUE TITLE
PanOnZoom does not work even on latest version 5.3.0

### ISSUE THREAD

**Issue by rahul-winner** [swimlane/ngx-graph#153]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
PanOnZoom does not work. Please refer this thread for more discussion on this #128 

I noticed we got to override the "pan" method as follows in order to make it work. Expectation is that it should work OOTB.

```
    pan(x: number, y: number): void {
        this.transformationMatrix = transform(this.transformationMatrix, translate(x, y));
        this.updateTransform();
    }
```

**Expected behavior**
We should be able to pan on a particular node when zooming. A property 'panOnZoom' has been introduced however it does seem to work.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-graph version:** 5.3.0

* **Angular version:** 7.1.2

* **Browser:** All

* **Language:** All

**Comment by rahul-winner** [comment]
@assafsun did you get some clue here?

**Comment by assafsun** [comment]
Not yet. Busy with some other issues.
Will try to look st it next week.

If you have any idea, let me know.

**Comment by assafsun** [comment]
https://github.com/swimlane/ngx-graph/pull/157

**Comment by marjan-georgiev** [comment]
Fixed, will be in the next release.
