### ISSUE TITLE
The "zoomToNode$" does not reflect the changes immidiately when the graph data is updated after graph initialization. Graph gets updated only when mouse moves.

### ISSUE THREAD

**Issue by rahul-winner** [swimlane/ngx-graph#156]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
For "zoomToNode$" to work we have to move the mouse over graph. 

**Expected behavior**
When "zoomToNode$" is called it should zoom the supplied the node intuitively and without waiting for any user action.

**NOTE:** This issue got high visibility for our production release. I'll be glad if I could get through it. Thank you.

**Reproduction of the problem**
Here are the steps to recreate the issue with demo app.
- load blank nodes and links to 'hierarchialGraph' in constructor
- load the turbine data within ngOnInit() 
- call "this.zoomToNode" within setTimeout for simulating asynchronous backend calls. I've actually used it within backend call response subscription.
- now load the demo app on browser and don't move the mouse
- you see on browser console the zoomToNode has been called but the desired has not been highlighted
- now move the mouse slightly and you can see the node gets zoom.

**Following is the code snippet**

```
  constructor() {
    Object.assign(this, {
      countrySet: countries,
      colorSchemes: colorSets,
      chartTypeGroups: chartGroups,
      hierarchialGraph: {nodes: [], links: []}
    });

    this.setColorScheme('picnic');
    this.setInterpolationType('Bundle');
  }

  ngOnInit() {
    this.selectChart(this.chartType);

    setInterval(this.updateData.bind(this), 1000);

    if (!this.fitContainer) {
      this.applyDimensions();
    }
    Object.assign(this.hierarchialGraph, getTurbineData());
    setTimeout(() => {
      console.log('zoom to node...........');
      const nodeToZoom = this.hierarchialGraph.nodes.find(n => n.label === 'post_to_slack');
      this.zoomToNode(nodeToZoom.id);      
    }, 5000);
  }
```
**Note:** Problem does not get resolved even if we call 'zoomToNode' from within 'zone' something like below
```
    Object.assign(this.hierarchialGraph, getTurbineData());
    setTimeout(() => {
      console.log('zoom to node...........');
      this.zoneRef.run(() => {
        const nodeToZoom = this.hierarchialGraph.nodes.find(n => n.label === 'post_to_slack');
        this.zoomToNode(nodeToZoom.id);
      });
    }, 5000);
```

**What is the motivation / use case for changing the behavior?**
We would like to provide search function within graph and highlight the node which has been searched within the graph. However I noticed that it does not work that effectively, as user has to move the mouse to actually see the node highlighted.

**Please tell us about your environment:**

* **ngx-graph version:** 5.3.0

* **Angular version:** 7.1.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
Could you create a stackblitz where this can be reproduced? Thanks.

**Comment by shirGabiz** [comment]
Hi, As a quick solution you can trigger the update$ observable after calling zoomToNode 
update$.next(true);

**Comment by marjan-georgiev** [comment]
Yes, you can call update after zooming to refresh the graph.
