### ISSUE TITLE
Problems with address sign in link ID

### ISSUE THREAD

**Issue by fripso** [swimlane/ngx-graph#163]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Address sign (@) in link IDs causes the graph to crash after rendering nodes. I read #5 about hiphens in IDs, but it seems that is not the only special character that causes issues.

```
links = [{
    source: 'foo@bar',
    target: 'bar'
}];

OR

links = [{
    source: 'foo',
    target: 'bar@stool'
}];

```
**Expected behavior**
Since the address sign doesn't seem to cause issues when used in node IDs, one would expect to be able to use them establishing links

**Reproduction of the problem**

**Component**
```
data = { 
    "links": [
        { "source": "foo@bar", "target": "bar" } 
    ], 
    "nodes": [
        { "id": "foo@bar", "label": "foobar" }, 
        { "id": "bar", "label": "barfoo" }
     ]
 }
```

**HTML**
```
<ngx-graph [update$]="update$"
            [curve]="curve"
            [links]="data.links"
            [nodes]="data.nodes"
            [enableZoom]="false"
            [draggingEnabled]="false">
</ngx-graph>
```

* **ngx-graph version:** 5.4.1

* **Angular version:** 7.2.4

**Comment by Jerkiller** [comment]
Hi, I had the same problem as @fripso.

I experienced that _edge sources_ and _edge targets_ shouldn't contain characters as ":" or "#".
In my case I replaced them with "-". But a fix could be very useful. :-)

**Comment by fripso** [comment]
Yes a fix would be useful indeed.

I'm on a project where I don't own the data I have to display, so my current solution is to map the symbols to something safe for rendering and then put the original labels in my UI, but that feels a little ugly.

**Comment by assafsun** [comment]
Hi,

From my testing, I noticed that it doesn't reproduce on version 6.
Can you please consider upgrading to this version?

Regrading version 5, I think I understand the problem but I'm still investigating it.
Will update once I will have more information

**Comment by assafsun** [comment]
@fripso Did you tested it with version 6 (if it possible)?

**Comment by fripso** [comment]
Have not yet had a chance to upgrade and test, sorry. Might try later this week!

**Comment by assafsun** [comment]
Closing this issue as it relevant only for version 5 and there is workarounds.

Supporting it on version 5 will require additional work that it's not trivial after finding the problematic code section.

Please update the thread (mention my user name in the comment) for any problems
