### ISSUE TITLE
Path stroke is not used

### ISSUE THREAD

**Issue by godrose** [swimlane/ngx-graph#165]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
Add a stroke with color to an `svg-path`
The color isn't displayed on the edge

**Expected behavior**
The edge's color changes

**Reproduction of the problem**
Repro repo:
https://stackblitz.com/edit/ngx-graph-simple-example?file=app%2Fapp.component.html

**What is the motivation / use case for changing the behavior?**
I need to change the color of the edge/link based on some field in the binding

**Please tell us about your environment:**
It runs on Web in Chrome

* **ngx-graph version:** x.x.x
The one from the example

* **Angular version:** x.x.x
The one from the example

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
I was able to change it: https://stackblitz.com/edit/ngx-graph-simple-example-rynqrr?file=app%2Fapp.component.html

Closing this. Let me know if you have further questions.
