### ISSUE TITLE
How to use the real-time data

### ISSUE THREAD

**Issue by Fisi107** [swimlane/ngx-graph#166]
**I'm submitting a question for the documentation**  

**Current behavior**
I don't know how to add and remove nodes and links runtime (or how to reload the ngx graph).
On your demo there is this feature but not in your documentation!

**Expected behavior**

**Reproduction of the problem**
push new nodes from another event and the changes you will not see.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-graph version:** x.x.x

* **Angular version:** x.x.x

* **Browser:** [all | Chrome XX | Firefox XX 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by assafsun** [comment]
Which version are you using?

For version 5, you can just update the 'nodes' and 'links' input binding of the graph, you can check how the "real time" functionality code works.
https://github.com/swimlane/ngx-graph/blob/5.x/demo/app.component.ts#L112

Extended documentation is work in progress.

**Comment by marjan-georgiev** [comment]
When modifying the nodes or links arrays, you need to create new instances of the object, because the graph component will only detect changes if you pass it a new reference.

So after modifying, you can do this
`this.nodes = [...this.nodes]` which will create a new array with the same nodes.

**Comment by assafsun** [comment]
Closing because it was answered.

**Comment by kimbosanz-dev** [comment]
any new comment regarding the real time data application
