### ISSUE TITLE
I don't know, how I can get all nodes from the graph

### ISSUE THREAD

**Issue by layton736** [swimlane/ngx-graph#167]
I'm submitting a question for the documentation

**Current behavior**

I don't know, how I can get all the nodes of a graph. Currently  I get only one node, which was clicked. I can change the color too, but only for this one node. 

**What is the motivation / use case for changing the behavior?**

I want to change the color of a node and all other nodes, which are direct connected, when i click on a node. How can i do that?

**Comment by assafsun** [comment]
Each node can has its own model on his object model, you can pass it to your 'onClick' function.
