### ISSUE TITLE
Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by Vicky3535** [swimlane/ngx-graph#168]
I'm submitting a ... (check one with "x")

[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here

I am facing the below issue, when I was build my code(ng build --prod).

**Current behavior**
<--- Last few GCs --->

[16108:00000194EE4A31A0]   305627 ms: Mark-sweep 1350.7 (1453.1) -> 1341.6 (1457.1) MB, 1072.1 / 0.0 ms  (average mu = 0.155, current mu = 0.087) allocation failure scavenge might not succeed
[16108:00000194EE4A31A0]   307473 ms: Mark-sweep 1354.0 (1457.1) -> 1345.0 (1457.1) MB, 1727.2 / 0.0 ms  (average mu = 0.101, current mu = 0.064) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 000000BC781DC5C1]
Security context: 0x0203c299e6e1 <JSObject>
    1: input(aka next_token) [00000218435F1ED9] [0x0011dd0026f1 <undefined>:~2296] [pc=000000BC7BB9D58E](this=0x0218435f1f19 <Object map = 00000267EDF2D651>,force_regexp=0x0011dd0026f1 <undefined>)
    2: arguments adaptor frame: 0->1
    3: next(aka next) [00000218435F2211] [0x0011dd0026f1 <undefined>:~2475] [pc=000000BC7BB9F21E](this=0x0011dd0026f1 <unde...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6355C08AA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4810
 2: 00007FF635599C46 node::MakeCallback+4518
 3: 00007FF63559A630 node_module_register+2160
 4: 00007FF63582AA4E v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF63582A97F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF635D68984 v8::internal::Heap::MaxHeapGrowingFactor+11476
 7: 00007FF635D5F0E7 v8::internal::ScavengeJob::operator=+25543
 8: 00007FF635D5D65C v8::internal::ScavengeJob::operator=+18748
 9: 00007FF635D665D7 v8::internal::Heap::MaxHeapGrowingFactor+2343
10: 00007FF635D66656 v8::internal::Heap::MaxHeapGrowingFactor+2470
11: 00007FF6359179BF v8::internal::Factory::NewLoadHandler+95
12: 00007FF635FF4CD3 v8::internal::compiler::operator<<+118947
13: 00007FF635D9D892 v8::internal::Bitmap::IsClean+91090
14: 00007FF635D9D295 v8::internal::Bitmap::IsClean+89557
15: 00007FF635D9BD7C v8::internal::Bitmap::IsClean+84156
16: 00007FF635DA3663 v8::internal::Bitmap::IsClean+115107
17: 000000BC781DC5C1

**Please tell us about your environment:**
OS: Windows 10, IDE: Visual Studio Code, Package Manager: npm

* **ngx-graph version:** "^5.5.0"

* **Angular version:**
    "@angular/animations": "~5.0.0",
    "@angular/common": "~5.0.0",
    "@angular/compiler": "~5.0.0",
    "@angular/compiler-cli": "~5.0.0",
    "@angular/core": "~5.0.0",
    "@angular/flex-layout": "^6.0.0-beta.18",
    "@angular/forms": "~5.0.0",
    "@angular/http": "~5.0.0",
    "@angular/platform-browser": "~5.0.0",
    "@angular/platform-browser-dynamic": "~5.0.0",
    "@angular/platform-server": "~5.0.0",
    "@angular/router": "~5.0.0",
    "@angular/upgrade": "~5.0.0"

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript 2.4.2 | ES5]

**Comment by marjan-georgiev** [comment]
Could you provide a repository where this can be reproduced?

**Comment by assafsun** [comment]
@Vicky3535 Is this still relevant?

**Comment by marjan-georgiev** [comment]
Closing as there's no response. Please create a new issue if you still want us to look at this and provide an example.
