### ISSUE TITLE
How to call Center and Fit In View pragmatically

### ISSUE THREAD

**Issue by martyn-harris** [swimlane/ngx-graph#169]
Not really an issue, but something that I am struggling to find any progress with in the documentation.

I have a stackoverflow question open here:  [https://stackoverflow.com/questions/55022528/how-to-call-center-and-fit-in-view-pragmatically-on-ngx-graph](https://stackoverflow.com/questions/55022528/how-to-call-center-and-fit-in-view-pragmatically-on-ngx-graph)

Would be great if someone could give me some guidance on this.

**Comment by assafsun** [comment]
I recommended looking at the example of version 5 (5.x branch).
It will help you to better understand how to use it.

**Comment by martyn-harris** [comment]
Thanks @assafsun ,
The code sample in the 5.x branch was helpful.   However my issue in the end was that we were using version 4.0, which I believe didn't contain the members I was trying to call.  Updated to version 4.3 and have it working now.
