### ISSUE TITLE
Node of graph moves after orientation

### ISSUE THREAD

**Issue by EmmanuelKontcheu** [swimlane/ngx-graph#170]
I am trying to put a select box as a div box to change the orientation of the graph nodes in the same div as the graph. But when i change the orientation of the graph, the node change the position too, But without the selected div box, it works.

Example: My Orientation is "left to right", then i change it to "Right to left", and i change it back again. Every node has a lower position. I read the position of a node after the orientation was changed, but the position of the node change sometime and sometimes not. But in the graph view, it is always lower, independent of the position value. 

Value of a Node
Begin:
height: 41.15625
id: "MyID"
label: "MyLabel"
options: {color: "#adcded", transform: "translate(118.2578125, 20)"}
type: "MyType"
width: 134.890625
x: 185.703125
y: 40.578125

Node after left to right, and right to left:
height: 40.515625
id: "MyID"
label: "MyLabel"
options: {color: "#adcded", transform: "translate(114.65625, 20)"}
type: "MyType"
width: 140.890625
x: 185.1015625
y: 40.2578125

Node after left to right, and right to left again:
height: 40.390625
id: "MyID"
label: "MyLabel"
options: {color: "#adcded", transform: "translate(110.0078125, 20)"}
type: "MyType"
width: 133.984375
x: 177
y: 40.1953125

I expect, the graph looks  like how it was at the beginning, after i change the orientation back, how it was at the beginning.

**Comment by EmmanuelKontcheu** [comment]
My code
<div *ngIf="graph_ready && message.type !== 'error'" class="container ngx-graph-container">
<div class="test">
    <div class="col-auto my-1">
      <div class="">
        <button class="btn btn-primary">Edit</button>
      </div>

      <label class="mr-sm-2" for="inlineFormCustomSelect">Orientation</label>
      <select [(ngModel)]="orientation" class="custom-select mr-sm-1" id="inlineFormCustomSelect">
            <option *ngFor="let orient of orientations" [value]="orient.value">{{orient.label}}</option>
        </select>
      </div>
  </div>
    <ngx-graph class="chart-container" [autoZoom]="ngxgraph.autoZoom"
            [orientation]="orientation"
            [links]="hierarchialGraph.links" [nodes]="hierarchialGraph.nodes"
                [legend]="ngxgraph.legend" [curve]="ngxgraph.curve" [draggingEnabled]="ngxgraph.dragging" [autoCenter]="ngxgraph.autoCenter">
        <ng-template #defsTemplate>
            <svg:marker id="arrow" viewBox="0 -5 10 10" refX="8" refY="0" markerWidth="4" markerHeight="4" orient="auto">
                <svg:path d="M0,-5L10,0L0,5" class="arrow-head" />
            </svg:marker>
        </ng-template>

        <ng-template #nodeTemplate let-node>
            <svg:g (click)="changeNodeColor(node)"  ngx-tooltip [tooltipPlacement]="'top'" [tooltipType]="'tooltip'" [tooltipTitle]="node.position">
                <svg:rect [attr.width]="node.width" [attr.ry]="4" [attr.height]="node.height" [attr.fill]="node.options.color" />
                <svg:text alignment-baseline="central" [attr.x]="0" [attr.y]="node.height / 2">
                    <svg:tspan text-anchor="middle" [attr.x]="node.width/2" [attr.y]="15" font-weight="bold">{{node.type}}</svg:tspan>
                    <svg:tspan text-anchor="middle" [attr.x]="node.width/2" [attr.y]="35" font-weight="lighter ">{{node.label}}</svg:tspan>
                </svg:text>
            </svg:g>
        </ng-template>

        <ng-template #linkTemplate let-link>
            <svg:g class="edge">
                <svg:path class="line" stroke-width="2" marker-end="url(#arrow)">
                </svg:path>
                <svg:text class="edge-label" text-anchor="middle">
                </svg:text>
            </svg:g>
        </ng-template>
    </ngx-graph>
</div>

**Comment by EmmanuelKontcheu** [comment]
`<div *ngIf="graph_ready && message.type !== 'error'" class="container ngx-graph-container">

  <div class="test">
      <div class="col-auto my-1">
        <div class="">
          <button class="btn btn-primary">Edit</button>
        </div>

        <label class="mr-sm-2" for="inlineFormCustomSelect">Orientation</label>
        <select [(ngModel)]="orientation" class="custom-select mr-sm-1" id="inlineFormCustomSelect">
              <option *ngFor="let orient of orientations" [value]="orient.value">{{orient.label}}</option>
          </select>
        </div>
    </div>
    <ngx-graph class="chart-container" [autoZoom]="ngxgraph.autoZoom"
            [orientation]="orientation"
            [links]="hierarchialGraph.links" [nodes]="hierarchialGraph.nodes"
                [legend]="ngxgraph.legend" [curve]="ngxgraph.curve" [draggingEnabled]="ngxgraph.dragging" [autoCenter]="ngxgraph.autoCenter">
        <ng-template #defsTemplate>
            <svg:marker id="arrow" viewBox="0 -5 10 10" refX="8" refY="0" markerWidth="4" markerHeight="4" orient="auto">
                <svg:path d="M0,-5L10,0L0,5" class="arrow-head" />
            </svg:marker>
        </ng-template>

        <ng-template #nodeTemplate let-node>
            <svg:g (click)="changeNodeColor(node)"  ngx-tooltip [tooltipPlacement]="'top'" [tooltipType]="'tooltip'" [tooltipTitle]="node.position">
                <svg:rect [attr.width]="node.width" [attr.ry]="4" [attr.height]="node.height" [attr.fill]="node.options.color" />
                <svg:text alignment-baseline="central" [attr.x]="0" [attr.y]="node.height / 2">
                    <svg:tspan text-anchor="middle" [attr.x]="node.width/2" [attr.y]="15" font-weight="bold">{{node.type}}</svg:tspan>
                    <svg:tspan text-anchor="middle" [attr.x]="node.width/2" [attr.y]="35" font-weight="lighter ">{{node.label}}</svg:tspan>
                </svg:text>
            </svg:g>
        </ng-template>

        <ng-template #linkTemplate let-link>
            <svg:g class="edge">
                <svg:path class="line" stroke-width="2" marker-end="url(#arrow)">
                </svg:path>
                <svg:text class="edge-label" text-anchor="middle">
                </svg:text>
            </svg:g>
        </ng-template>
    </ngx-graph>
</div>
`

**Comment by bohdyone** [comment]
I think I may be experiencing a similar (same?) issue, where if we force the graph to re-render by giving it new data, the nodes move, and in my case increase the height of the container (since no fixed height is given).

You can see the issue here https://stackblitz.com/edit/angular-edligh if you just click the Render button a few times.

**Comment by marjan-georgiev** [comment]
Does the div container around the ngx-graph component have a set height? If you do not define the `view` input on the graph, it will resize itself to fit the container element, but the container div needs an actual height css property set on it (it can be 100%, that's fine too). Also, the container should have no padding. If you want padding, you can add another container around it.

I updated @bohdyone stackblitz by adding a height: 500px to the wrapping container and that fixes it.

https://stackblitz.com/edit/angular-mghnpv?file=src/app/app.component.html

**Comment by bohdyone** [comment]
Hi @marjan-georgiev, For my use case at least, requiring a fixed size is a big limitation. 

To give some more background, what I want to do is have the component take up remaining vertical space in the viewport, which is inherently dynamic sizing. This can be done with flexbox layout, and I've added to my earlier example: https://stackblitz.com/edit/angular-uzcbkr

As you can see, the initial render is sized correctly, but then on subsequent renders the component grows outside of its boundaries.

Can you comment on this limitation, or suggest a way I can achieve the same effect with this component?

**Comment by marjan-georgiev** [comment]
You don't have to have fixed size, you can use 100%. Flex layout should also work (I am using it in my app without any issues).

There might to be something in your flex-layout configuration that is causing this. If I remove it and replace it with a 100% height on the container it works fine:

https://stackblitz.com/edit/angular-7psrux?file=src/app/app.component.html

**Comment by bohdyone** [comment]
Hmm, I'm still seeing issues with the flexbox-based layout we are using that height: 100% can't fix. The component just keeps growing.
Even if you look at my earlier example (https://stackblitz.com/edit/angular-uzcbkr) and just change the ngx-graph container to be 'height: 100%' it doesn't quite work as expected...

**Comment by marjan-georgiev** [comment]
@bohdyone I was able to solve this by wrapping the chart in another container:
`<div style="position: absolute; top: 0; left: 0; bottom: 0; right: 0;">`

Take a look at the example:
https://stackblitz.com/edit/angular-me14g3?file=src/app/app.component.html

**Comment by bohdyone** [comment]
Hi @marjan-georgiev, thanks for that - it does seem like the combination of `position: relative` on the parent and the `position: absolute` snippet does do the job. 

Bit of an odd workaround, but at least it works :)

**Comment by csruchitaoza** [comment]
If anyone archived the saving position of the node, so that the next time it renders then it renders from the same position, could you please share your code to this? I would be appreciated.,
