### ISSUE TITLE
Production Build fails for Angular 5.0.0

### ISSUE THREAD

**Issue by rpvsen** [swimlane/ngx-graph#171]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

if i  use ngx-graph my build gets fails or else its works fine.

"devDependencies": {
    "@angular/cli": "1.5.0",
    "@types/chartjs": "0.0.31",
    "@types/datatables.net": "^1.10.15",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "^2.0.3",
    "@types/jquery": "^3.3.29",
    "@types/node": "^6.0.45",
    "jasmine": "~2.4.1",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.2",
    "lodash": "^4.17.11",
    "phantomjs-prebuilt": "^2.1.7",
    "popper.js": "^1.12.9",
    "protractor": "^5.4.1",
    "ts-node": "^3.3.0",
    "tslint": "^3.15.1",
    "typescript": "2.4.2"
  }

**Expected behavior**

**Reproduction of the problem**
92% chunk asset optimization
<--- Last few GCs --->

[15660:000001AA45530090]   207204 ms: Mark-sweep 1338.7 (1450.5) -> 1329.4 (1454.0) MB, 987.5 / 0.0 ms  (average mu = 0.171, current mu = 0.112) allocation failure scavenge might not succeed
[15660:000001AA45530090]   208309 ms: Mark-sweep 1342.0 (1454.0) -> 1332.7 (1457.5) MB, 988.6 / 0.0 ms  (average mu = 0.140, current mu = 0.106) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0000038EE0ADC5C1]
    1: StubFrame [pc: 0000038EE0ADDB86]
Security context: 0x01ea01b9e6e1 <JSObject>
    2: read_word(aka read_word) [0000018B1FE77D81] [0x02f95f3826f1 <undefined>:~2276] [pc=0000038EE4532D92](this=0x02f95f3826f1 <undefined>)
    3: next_token [0000018B1FE77DC1] [0x02f95f3826f1 <undefined>:~2296] [pc=0000038EE4566BCA](this=0x018b1fe77e01 <Object map = 0000006EC88E8749>,force_regexp=0x02f95f3826f1 <un...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7FD7C121A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4810
 2: 00007FF7FD79A5B6 node::MakeCallback+4518
 3: 00007FF7FD79AFA0 node_module_register+2160
 4: 00007FF7FDA2B3EE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF7FDA2B31F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF7FDF69304 v8::internal::Heap::MaxHeapGrowingFactor+11476
 7: 00007FF7FDF5FA67 v8::internal::ScavengeJob::operator=+25543
 8: 00007FF7FDF5DFDC v8::internal::ScavengeJob::operator=+18748
 9: 00007FF7FDF66F57 v8::internal::Heap::MaxHeapGrowingFactor+2343
10: 00007FF7FDF66FD6 v8::internal::Heap::MaxHeapGrowingFactor+2470
11: 00007FF7FDB09DD7 v8::internal::Factory::NewFillerObject+55
12: 00007FF7FDBA1ABA v8::internal::WasmJs::Install+29530
13: 0000038EE0ADC5C1

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

OS: 10,
IDE: Visual Studio Code,
Angular CLI: 7.3.1
Node: 10.15.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.1
@angular-devkit/core         7.3.1
@angular-devkit/schematics   7.3.1
@schematics/angular          7.3.1
@schematics/update           0.13.1
rxjs                         6.3.3
typescript                   3.2.4

* **ngx-graph version:** ^4.1.1

* **Angular version:** 5.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript 2.4.2  | ES5]

**Comment by assafsun** [comment]
what about version 5.5.0?

**Comment by rpvsen** [comment]
@assafsun, 

"dependencies": {
    "@angular/animations": "~7.1.0",
    "@angular/common": "~7.1.0",
    "@angular/compiler": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/forms": "~7.1.0",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/router": "~7.1.0",
    "@ngx-loading-bar/core": "^4.1.1",
    "@ngx-loading-bar/http": "^4.1.1",
    "@ngx-loading-bar/http-client": "^4.1.1",
    "@ngx-loading-bar/router": "^4.1.1",
    "@swimlane/ngx-charts": "^10.0.0",
    "@swimlane/ngx-graph": "^5.5.0",
    "bootstrap": "^4.3.0",
    "core-js": "^2.5.4",
    "d3-array": "^2.0.3",
    "d3-brush": "^1.0.6",
    "d3-color": "^1.2.3",
    "d3-force": "^2.0.0",
    "d3-hierarchy": "^1.1.8",
    "d3-interpolate": "^1.3.2",
    "d3-scale": "^2.2.2",
    "d3-selection": "^1.4.0",
    "d3-shape": "^1.3.4",
    "d3-time-format": "^2.1.3",
    "d3-transition": "^1.2.0",
    "jquery": "^3.3.1",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  }

Now my build issue is resolved. But i am getting below error message after deployed in the server

`ERROR Error: StaticInjectorError[e -> t]: 
  StaticInjectorError(Platform: core)[e -> t]: 
    NullInjectorError: No provider for t!
    at t.get (main.9551989c75433e6329dd.js:1)
    at main.9551989c75433e6329dd.js:1
    at t (main.9551989c75433e6329dd.js:1)
    at t.get (main.9551989c75433e6329dd.js:1)
    at main.9551989c75433e6329dd.js:1
    at t (main.9551989c75433e6329dd.js:1)
    at t.get (main.9551989c75433e6329dd.js:1)
    at kg (main.9551989c75433e6329dd.js:1)
    at t.get (main.9551989c75433e6329dd.js:1)
    at _v (main.9551989c75433e6329dd.js:1)`

**Comment by arcteezy** [comment]
There are two workarounds but they are not perfect solutions.

- Use flags `--aot=false` and `--build-optimizer=false` during building.

- Change versions of **ngx-graph** to **v5.0.0** and **ngx-charts** to **v8.1.0**.

**Comment by assafsun** [comment]
I think using ngx-graph 5.5.0 with charts 8.0.0 or 8.1.0 can solve this.

**Comment by rpvsen** [comment]
@arcteezy & @assafsun  thanks.
