### ISSUE TITLE
Zoom Level default 0.2

### ISSUE THREAD

**Issue by Vicky3535** [swimlane/ngx-graph#172]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request => Please do not submit support request here
```

**Current behavior**
Zoom Level fit to the Screen.

**Expected behavior**
Zoom level should be 0.2.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-graph version:** 4.1.1

* **Angular version:** 5.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES5]

**Comment by assafsun** [comment]
Closing this issue.
Please update using the latest version 5.

Thanks.
