### ISSUE TITLE
Display data in sequence  issue 

### ISSUE THREAD

**Issue by maxwellfargose** [swimlane/ngx-graph#174]
![Untitled](https://user-images.githubusercontent.com/26279980/54268727-e37a3900-45a1-11e9-9b25-eedf48e16ff6.png)

Want to display data in sequence as shown in image, on update or page refresh sequence will change automatically.

**Comment by marjan-georgiev** [comment]
Please provide a stackblitz example and fill in the issue form properly.

**Comment by maxwellfargose** [comment]
https://stackblitz.com/edit/angular-7nwem6?embed=1&file=src/app/app.component.html


![image](https://user-images.githubusercontent.com/26279980/54408778-4508e780-4709-11e9-8986-2cf4eb8e09fe.png)



I have added some functionality in it(drag or drop, remove node, add/remove link).   when user click on link it will remove, when link remove the next node will display below current node. Also links will display in sequence like (write00, write01, write02),(write00),(write09,write05,write06)(added first will display first). when User click on same node twice it will remove automatically.


Please help me.......

Thanks in advance
