### ISSUE TITLE
I don't know how to change the color of a node and all other nodes, which are direct linked, when i click on that node

### ISSUE THREAD

**Issue by EmmanuelKontcheu** [swimlane/ngx-graph#175]
I'm trying to change  the color of a node and all other nodes, which are direct linked, when i click on that node but i can actually just change the color of the one that was clicked.Even  if the color of the others linked nodes are setted, the nodes color in the graph are not actualized.Please can you help?

**Comment by assafsun** [comment]
Hi,

1. Which version are you using 

2. That a good scenario which you can address it by running different algorithms on the links and nodes that you pass to ngx-graph and mark them by changing the passing model object.

We need to think if ngx-graph can output the connected nodes after passing a specific node, ngx-graph is not a graph data library but a UI component so I doubt that we can do it.

**Comment by assafsun** [comment]
Update on this issue:

From my experience, It is simple to maintain the the data and css properties for highlight graph flows from outside ngx-graph. 
beside basic highlight, there are many scenarios of more complex highlight\filter  that each user can decide what to show (add\remove nodes) or highlight.

**Comment by assafsun** [comment]
Closing this issue as this functionality should be outside ngx-graph IMO
