### ISSUE TITLE
Bundle size reduction

### ISSUE THREAD

**Issue by zolee** [swimlane/ngx-graph#178]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
Currently `@swimlane/ngx-graph` imports the full `@swimlane/ngx-charts/release` dependency which causes an excessive increase of the final bundle size. Please check the picture below, the full @angular framework stat size is 1.31 Mb while the full import of @swimlane/ngx-charts/release adds 1.16MB
![bundle_size](https://user-images.githubusercontent.com/2125279/54570169-e039df80-49dd-11e9-9408-b59539b0c0e3.png)

**Expected behavior**
Import only the required modules/code. Please check this issue https://github.com/swimlane/ngx-charts/issues/699 where a similar problem was solved in @swimlane/ngx-charts.

**Reproduction of the problem**
* **Install / use:** Install and use the ngx-graph module according to the documentation
* **Build:** Create a production build (in my case I use angular CLI) `ng build --prod --statsJson=true`
* **Check stats:** Use (for example) the [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) to see the production package content based on the generated `stats.json`

**What is the motivation / use case for changing the behavior?**
Reduce final bundle size to improve application load performance.

**Please tell us about your environment:**

* **ngx-graph version:**
`@swimlane/ngx-graph 5.5.0`

* **Angular version:**
`@angular 7.2.7` `@angular/cli 7.3.4`

* **Browser:**
All browsers affected as the feature has an impact on the bundle size. It is not a runtime problem rather than a packaging issue (tree shaking?).

* **Language:**
`typescript 3.2.4`

**Comment by marjan-georgiev** [comment]
We have deprecated the dependency on ngx-graph in version 6, and will completely remove it in version 7.
