### ISSUE TITLE
ERROR TypeError: Cannot set property 'height' of undefined at index.js:44051

### ISSUE THREAD

**Issue by TestingAndDebugging** [swimlane/ngx-graph#179]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
I'm adding new nodes with a form and i get an error:

```
ERROR TypeError: Cannot set property 'height' of undefined
    at index.js:44051
    at Array.map (<anonymous>)
    at QueryList.push../node_modules/@angular/core/fesm5/core.js.QueryList.map (core.js:18157)
    at GraphComponent../src/index.ts.GraphComponent.draw (index.js:44033)
    at index.js:44318
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17280)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:498)
```
I'm not sure why this error occures...

```
/**
   * Draws the graph using dagre layouts
   *
   *
   * @memberOf GraphComponent
   */
  draw(): void {
    // Calc view dims for the nodes
    if (this.nodeElements && this.nodeElements.length) {
      this.nodeElements.map(elem => {
        const nativeElement = elem.nativeElement;
        const node = this._nodes.find(n => n.id === nativeElement.id);

        // calculate the height
        let dims;
        try {
          dims = nativeElement.getBBox();
        } catch (ex) {
          // Skip drawing if element is not displayed - Firefox would throw an error here
          return;
        }

        if (this.nodeHeight) {
          if (!this.isCustomNodeSize) {
            node.height = this.nodeHeight;
          }
        } else {
          node.height = dims.height; //<--- Error is thrown here
        }
```

this is how my graph looks like after adding new nodes

![ngx-graph_issue](https://user-images.githubusercontent.com/22895715/54598239-64b94c00-4a38-11e9-9683-53cd50cd3fad.PNG)

**Expected behavior**
This is how my graph looks like after just reloading the page:
![ngx-graph_expected](https://user-images.githubusercontent.com/22895715/54598320-87e3fb80-4a38-11e9-8ede-c6ce1787caff.PNG)

**Please tell us about your environment:**
Windows Version 10.0.17134
VS Code Version 1.32.3

* **ngx-graph version:** 5.5.0

* **Angular version:** 7.2.3

* **Browser:** 
Chrome Version 73.0.3683.75 (Offizieller Build) (64-Bit)

**Comment by assafsun** [comment]
Are you settings the height inside the node or inside the graph as general input?

**Comment by TestingAndDebugging** [comment]
I'm not setting the height variable... this should be automatically generated by the draw function as I know...

**Comment by assafsun** [comment]
it's not from what I know. You need to set a general height on the graph level for all nodes or per each node. 

Let me know if you have any problems.

I'm closing this issue

**Comment by TestingAndDebugging** [comment]
oh okey... didn't knew I need to do that because the node height was set to 30 by default... where it came from? I dont know, but everything worked nicely until i added a node, like described.

Can you provide a little code example for the general height?

Thanks for the Help :)
