### ISSUE TITLE
error building

### ISSUE THREAD

**Issue by self-ads** [swimlane/ngx-graph#181]
i got this error when i try to build my project 

             ERROR in : Cannot determine the module for class GraphComponent in C:/Users/yassine/Documents/NetBeansProjects/Horizon/CRMApplication/node_modules/@swimlane/ngx-graph/src/graph/ graph.component.ts! Add GraphComponent to the NgModule to fix it.

**Comment by marjan-georgiev** [comment]
You need to import `NgxGraphModule` into your module.

**Comment by self-ads** [comment]
> NgxGraphModule

i did it, but still the same error
