### ISSUE TITLE
IE not allowing the user to click and drag the entire graph

### ISSUE THREAD

**Issue by jlarso11** [swimlane/ngx-graph#183]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

In IE, when a user clicks and drags on the graph to reposition the whole thing, the graph is moved to 0,0 because the location is returned as NaN 

**Expected behavior**

IE should have the same behavior as the other two browsers where the user is able to reposition the graph as expected.  

**Reproduction of the problem**

This defect is viewable in the current demo

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10

* **ngx-graph version:** x.x.x

5.5.0

* **Angular version:** x.x.x

7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

IE version 11.648.17134.0

**Comment by assafsun** [comment]
IE has its own limitation while working with SVG and with other HTML elements.
You can issue a PR for a specific case that you want to handle for IE but I suggest to maintain support for major browsers.
I believe that the graph is loaded and handled better on Edge if it helps.

Closing this issue as we can't proceed with any action item on it.

Thanks.
