### ISSUE TITLE
Support for Angular 8 Plan and Timelines

### ISSUE THREAD

**Issue by rahul-winner** [swimlane/ngx-graph#187]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
Angular will be releasing version 8.0 sometime in May 2019. We will like to be proactive and prepare in order to move onto it smoothly. We have started developer testing of our application with Angular Beta versions.

Could someone please throw light if some work has been started for supporting Angular 8?

**Please tell us about your environment:**

* **ngx-graph version:** x.x.x

* **Angular version:** x.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
We will release a compatible version of ngx-graph shortly after Angular 8 is released. This will be a 6.x version. 5.x will not be supported any more.
