### ISSUE TITLE
Expose _nodes to allow dynamic change without redrawing the whole graph

### ISSUE THREAD

**Issue by iwoogy** [swimlane/ngx-graph#189]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
The nodes sent to ngx-graph are cloned into _nodes.

**Expected behavior**
I would like to have a way to get the _nodes to modify the state of node to make them more dynamic on click or on keyboard event.
Updating the node rendered direclty would be more efficient than redrawing the whole graph.

**What is the motivation / use case for changing the behavior?**
I'm using extensively Xmind and I like to reproduce the keyboard navigation with ngx-graph.
So when a node is selected, I highlight it. Then I'd like to use the arrows to move the selection around the graph without redrawing the whole graph.

**Please tell us about your environment:**
Operating system: OS X 10.13.6
IDE: VSCode 1.33.1
package manager: npm 6.9.0

* **ngx-graph version:** 
5.5.0

* **Angular version:** 
7.2.13

* **Browser:** 
[all]

* **Language:** 
[all]

I would like to expose the nodes that are cloned:
```
@Output() nodesChange: EventEmitter<any> = new EventEmitter();
```
![2019-04-22_19-04-29](https://user-images.githubusercontent.com/479162/56499788-27157a80-6532-11e9-8534-d0ac96d74632.jpeg)

```
this.nodesChange.emit({value: this._nodes})
```
![2019-04-22_19-06-03](https://user-images.githubusercontent.com/479162/56499792-2c72c500-6532-11e9-96a3-362f0d0247a3.jpeg)

Would it be possible to make this change and merge it ?

Thanks

Regards

Bobby

**Comment by assafsun** [comment]
The keyboard navigation sounds very interesting, I would like to get more information on it if it's possible.

Why do you need it? the _nodes array contains the internal objects of nodes so in case you have a reference object inside _nodes, it will be pointed also from nodes.

Can't you use it outside ngx-graph?

**Comment by iwoogy** [comment]
Hello,


> The keyboard navigation sounds very interesting, I would like to get more information on it if it's possible.

For a use on Desktop, the keyboard is very convenient to create and modify the content.
On Xmind, they have those shortcuts that are very useful :

- Arrows keys: select node on the respective direction
- Enter: Add a new node below the current selected node
- Tab: Create a new child node
- Slash: Collapse the branch
- Star: Expand all collapsed node

> Why do you need it? the _nodes array contains the internal objects of nodes so in case you have a reference object inside _nodes, it will be pointed also from nodes.
> 
> Can't you use it outside ngx-graph?

My bad, you're right with the id and the custom options attached to the nodes I can achieve what I need.

Thanks for your help.

Regards

Bobby

**Comment by assafsun** [comment]
@iwoogy 

Hi,

Thanks for the reply.

Just to ask, are you working on xmind?

Thanks,
Assaf

**Comment by iwoogy** [comment]
Yes I'm working with Xmind daily but I use the version 7.5.

They started going to a direction that didn't fit my needs that's why I'm developing my own version thanks to ngx-graph.

**Comment by assafsun** [comment]
Thanks
