### ISSUE TITLE
Legends appear below graph instead of the right side

### ISSUE THREAD

**Issue by doorman02** [swimlane/ngx-graph#192]
**Describe the bug**
After updating to 6.0.1 the legends don't appear on the right side next to the graph. They seem to appear below the graph. Is there an online example with the legends in use?

**Expected behavior**
Legends should appear on the right side of the graph

**ngx-graph version**
6.0.1

**Comment by marjan-georgiev** [comment]
We will look into this, but we have deprecated the legend feature and will remove it in the next major version (7.0.0). If you need a legend, I would suggest building one outside of the graph component.

**Comment by doorman02** [comment]
Hi @marjan-georgiev  in that case I will build my own legend so no need to investigate further.
