### ISSUE TITLE
Restrict to horizontal/vertical panning

### ISSUE THREAD

**Issue by ctaepper** [swimlane/ngx-graph#193]
**Is your feature request related to a problem? Please describe.**
I have a very wide graph (orientation top-down) and a fixed height (always same amount of ranks). so i need to enable panning on the graph, however I want to restrict panning to horizontal, because there is no need to pan vertical. It will be a better UX if panning is only horizontal

**Describe the solution you'd like**
set `panningEnabled` to either `true|false|'horizontal'|'vertical'`

**Comment by marjan-georgiev** [comment]
Resolved in https://github.com/swimlane/ngx-graph/pull/195.
