### ISSUE TITLE
Reduce edge complexity

### ISSUE THREAD

**Issue by zolee** [swimlane/ngx-graph#194]
**Is your feature request related to a problem? Please describe.**
This issue is a kind request for configuration advice (I think) rather than a feature request. I have a graph which visualize a workflow, this can be seen on the picture below (zoomed out to see the whole picture).

![complex-workflow](https://user-images.githubusercontent.com/2125279/57483842-f6f70700-72a7-11e9-8532-5f5aedcbfe7b.PNG)

As you can see above it is quite hard to understand as it is visually overcrowded. The nodes are quite distant from each other and the edges connect them in a complex way. Is there any configuration advice I could try to render the nodes and their connections more simple?

**Describe the solution you'd like**
I would like to achieve the proportions similar to JIRA (I have attached a complex workflow below) which would be the target. As you can see this can fit in a smaller screen as it is much more compact.

![word-image-10](https://user-images.githubusercontent.com/2125279/57484238-d54a4f80-72a8-11e9-804a-aeb7d8941230.png)

**Describe alternatives you've considered**
I have tried to use different curves, currently I use `d3-shape.curveBundle` but could not achieve similar result. Is there anything I miss here? Like enable bidirectional connection rendered using the same edge? Reduce node distance or edge lengths? I have checked the documentation of course but could not make any significant progress.

**Additional context**
I currently use `@swimlane/ngx-graph 5.5.0`. Is there any other configuration advice (like upgrade to version 6.x and use node templates or edge templates) I could achieve my goal?

Thank you very much for your valuable help.

**Comment by assafsun** [comment]
ngx-graph version 5.5.0 is using dagre layout for placing the nodes and lines after setting the relationship between nodes. 

My advice in this case is to upgrade to version 6 and to build your own layout for placing your nodes and links. This is very dependent on how your internal graph structure but that's one direction that you can do for achieving this graph layout.

**Comment by zolee** [comment]
> ngx-graph version 5.5.0 is using dagre layout for placing the nodes and lines after setting the relationship between nodes.
> 
> My advice in this case is to upgrade to version 6 and to build your own layout for placing your nodes and links. This is very dependent on how your internal graph structure but that's one direction that you can do for achieving this graph layout.
> For example, I used a dagre only nodes layout where I set the lines shapes between the nodes in order to place a column based graph (using clusters) with a lines that exit and enter from the same location on the node.



> ngx-graph version 5.5.0 is using dagre layout for placing the nodes and lines after setting the relationship between nodes.
> 
> My advice in this case is to upgrade to version 6 and to build your own layout for placing your nodes and links. This is very dependent on how your internal graph structure but that's one direction that you can do for achieving this graph layout.
> For example, I used a dagre only nodes layout where I set the lines shapes between the nodes in order to place a column based graph (using clusters) with a lines that exit and enter from the same location on the node.

Thank you for your reply. I already have a plan to upgrade to version 6.x I just would like to wait until the new version will be released with the corrected package dependency syntax.

Do you have any kind of documentation (some API description, tutorial or maybe a stackblitz example) I could use as an example to build a custom layout to render the required result?

**Comment by assafsun** [comment]
https://swimlane.github.io/ngx-graph/

This is a good start

**Comment by assafsun** [comment]
I'm closing this issue for now.
For any issue with version 6, please open a new issue

**Comment by arsh437git** [comment]
@ assafsun  : Hi I need your help very urgently , I want to group nodes in the respective clusters and the cluster node shold be TB where as the cluster should be horizontally placed ?, how can i ACHIEVE THIS.
![image](https://user-images.githubusercontent.com/37994048/88590099-c8fe0e00-d077-11ea-9d98-1f92fe06802f.png)
