### ISSUE TITLE
Horizontal scroll for huge dataset ?

### ISSUE THREAD

**Issue by JeromeDesseaux** [swimlane/ngx-graph#197]
Hi, 

First of all : thanks for your work! This is really huge and awesome. 

I just miss a thing : I'm using a huge dataset (data every day, for some years). My client needs to see the whole dataset that (obviously) don't fit a single page width. 

Is there a way adding horizontal scroll bar to stacked bar charts ? 

Thanks

**Comment by marjan-georgiev** [comment]
Hi @JeromeDesseauxm, did you mean to open this in https://github.com/swimlane/ngx-charts?

**Comment by JeromeDesseaux** [comment]
ooops, yes. 

Sorry. 

I'll open it there. 

Thanks :)
