### ISSUE TITLE
Drag/Drop to reposition nodes

### ISSUE THREAD

**Issue by marjan-georgiev** [swimlane/ngx-graph#2]
Implement a possibility to reposition nodes by drag and drop. Once a node is repositioned manually, it should ignore new positions assigned to it by layout.

**Comment by isaacplmann** [comment]
This should also include being able to assign a position on the node object before the graph is rendered.

**Comment by marjan-georgiev** [comment]
I agree. Preserving the current state and restoring it should be supported.

**Comment by mattmutt** [comment]
Some additional ideas. It would be nice to have the dagre layout engine retain the correct line interpolation style while dragging. Currently the edge path gets rendered as a straight line after repositioning. The current code assumes two points in `onDrag()`.
The text labels on the path lines could also benefit from a more normal orientation. Since things were programmed to have the text follow the path in `calcDominantBaseline()`, they often render odd making it hard to read.
I think this view has good potential for evolving into an all purpose diagram editor.

**Comment by bolota** [comment]
Hello all,

Any news about this feature?

thank you

**Comment by isaacplmann** [comment]
@bolota I haven't had a chance to work on this. Want to take a crack at a PR?

**Comment by calebeaires** [comment]
Good job on the new version, but do you have news on this issue?

**Comment by isaacplmann** [comment]
I'll be doing some work on this library in the next few weeks.  I plan to address this feature among others.

**Comment by assafsun** [comment]
@marjan-georgiev , is this issue still relevant?

**Comment by ZachRoberts25** [comment]
Would be interesting in this.  This is a requirement for a project I am currently working on as well, where we want to remember the placement on the nodes on the graph so we can re render an identical graph after reload.  Even just allow the graph to have an initial state I think would be helpful

**Comment by mattmutt** [comment]
I have side project that mimics this requirement in Angular, using a grid-like layout engine to retain positioning of the nodes. Worth a mention to those interested in building graphs with SVG and components. Suppose this project could also leverage some working parts.

https://github.com/mattmutt/ngx-card-deck-seed

**Comment by saurabh-shelgaonkar** [comment]
Hey @marjan-georgiev, great library! Any plan on release of this feature? Thanks.

**Comment by assafsun** [comment]
Closing this because of the following reason:
1. User can drag node.
2. Version 7 contains external layout where the user can custom  of the layout and node position.

If I missed anything, please reopen it.

**Comment by rkbk1997** [comment]
Hi, All
I am using "Cola Force Directed" of Ngx Graph, and now I am facing one issue. When I drag a node to a new position. it will move all graphs to a new position instead of one node. Can you pls help me to solve this issue?
