### ISSUE TITLE
View attribute not defined by ngx-graph component.

### ISSUE THREAD

**Issue by slindenberg** [swimlane/ngx-graph#201]
**Describe the bug**
I have installed ngx-graph into an Angular 7 (CLI based) project. When I use the [Simple example](https://github.com/swimlane/ngx-graph#simple) from this page, it tells me there is no view input attribute provided (see screenshot). When  I remove the view attribute the graph renders on page.

**To Reproduce**
1. npm install @swimlane/ngx-graph --save (resolves to "@swimlane/ngx-graph": "^6.0.1")
2. Import module to app.module
3. Add component with [Simple example](https://github.com/swimlane/ngx-graph#simple)
4. Open page

**Expected behavior**
The `view` input attribute sets the graph's dimension.

**Screenshots**
![view-attribute- not-defined](https://user-images.githubusercontent.com/2778907/58410896-6bd18b80-8073-11e9-830f-fe4b74a61360.PNG)

**ngx-graph version**
^6.0.1

**angular version**
7.2.8

**Comment by marjan-georgiev** [comment]
Are you only seeing that message in the editor, or does it not work at all? The same example is used in https://swimlane.github.io/ngx-graph/

**Comment by slindenberg** [comment]
Yes, it only appears in the editor (Webstorm). The dimensions are getting set. I also had to install ngx-charts to make custom svg tags work.

**Comment by marjan-georgiev** [comment]
It looks like the editor not properly loading the type definitions. I would test if vscode reports the same problem.

**Comment by KingDarBoja** [comment]
I have used swimlane libraries on my projects (ngx-graph, ngx-charts, ngx-ui) and I am pretty sure VSCode will load the type definitions as long as you properly import the module.

![VSCode example](https://user-images.githubusercontent.com/30560560/58569316-8171bd00-81fb-11e9-9b62-3ec1f573d662.png)

**Comment by assafsun** [comment]
@slindenberg is this issue still relevant?

**Comment by marjan-georgiev** [comment]
Closing as it doesn't seem to be a bug with the library.

**Comment by siroz1907** [comment]
I also had a same problem.
Version that i used : Angular 12.1.1 ve "@swimlane/ngx-charts": "^18.0.1"  
I solved the problem like follow down: 

`[view] = "[view[0], view[1]]"`

![2021-07-29_091444](https://user-images.githubusercontent.com/1819509/127441181-fbd99fd7-679c-4435-a07a-897fa8530114.png)
