### ISSUE TITLE
Custom Templates demo don't work

### ISSUE THREAD

**Issue by kkseven07** [swimlane/ngx-graph#205]
Custom templates examples are not loaded
![Screen Shot 2019-06-07 at 4 47 01 PM](https://user-images.githubusercontent.com/25701048/59099077-f9e72500-8943-11e9-9e48-8ccf58035972.png)

**Comment by assafsun** [comment]
Can you please check the example by running the latest master code?

Can you please share more information?

**Comment by kkseven07** [comment]
I mean on the website [https://swimlane.github.io/ngx-graph/#custom-templates#node-template](url)

**Comment by KingDarBoja** [comment]
Happened to me in some project where using the `ngx-graph` component, if you check the browser console, you will get this message:

`Uncaught Error: StaticInjectorError(i9)[t -> e]: 
  StaticInjectorError(Platform: core)[t -> e]: 
    NullInjectorError: No provider for e!`

I am pretty sure it is related to the Tooltip service (something related to Dependency Injection) as happened to me if being used together with ngx-charts.

**Comment by marjan-georgiev** [comment]
> Happened to me in some project where using the `ngx-graph` component, if you check the browser console, you will get this message:
> 
> `Uncaught Error: StaticInjectorError(i9)[t -> e]: StaticInjectorError(Platform: core)[t -> e]: NullInjectorError: No provider for e!`
> 
> I am pretty sure it is related to the Tooltip service (something related to Dependency Injection) as happened to me if being used together with ngx-charts.
> 
> Related to this Issue too: [ngx-charts Injection Service Error](https://github.com/swimlane/ngx-charts/issues/975)

Yeah, that's one of the reasons I want to remove ngx-charts as a dependency.

**Comment by KingDarBoja** [comment]
> > Happened to me in some project where using the `ngx-graph` component, if you check the browser console, you will get this message:
> > `Uncaught Error: StaticInjectorError(i9)[t -> e]: StaticInjectorError(Platform: core)[t -> e]: NullInjectorError: No provider for e!`
> > I am pretty sure it is related to the Tooltip service (something related to Dependency Injection) as happened to me if being used together with ngx-charts.
> > Related to this Issue too: [ngx-charts Injection Service Error](https://github.com/swimlane/ngx-charts/issues/975)
> 
> Yeah, that's one of the reasons I want to remove ngx-charts as a dependency.

Would either ẁebpack` or `ng-packagr` solution fix this? I am not skilled on packing stuff but could give it a try to check if it works. The other idea would be just copy and pasting the required services from the `ngx-charts` project inside the `ngx-graph` source folder unless there are other stuff being used...

**Comment by marjan-georgiev** [comment]
Demos should be fixed.
