### ISSUE TITLE
swimlane-ngx-graph.umd.js (2:111) missing ) after argument list

### ISSUE THREAD

**Issue by moplin** [swimlane/ngx-graph#207]
**Describe the bug**
I am trying to make a simple graph, but I just added the dependency and it crashed, it might be related to angular 8.0

**To Reproduce**
1. Go to https://stackblitz.com/edit/angular-8-xxa?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
Using a very simple angular 8 project just added the module.

**Demo**
https://stackblitz.com/edit/angular-8-xxa

**ngx-graph version**
6.0.1

**Comment by KingDarBoja** [comment]
Hello @moplin,

As far as I know, ngx-graph hasn't been updated to be compatible with the lastest angular version (8 or higher).

@marjan-georgiev Is there any release date for compatibility with Angular 8?

**Comment by marjan-georgiev** [comment]
@duredhel13 is working on that at the moment. We should have a PR for it pretty soon.

**Comment by moplin** [comment]
Lovely thanks

**Comment by marjan-georgiev** [comment]
https://github.com/swimlane/ngx-graph/pull/211 has been merged. This will be in the next releases (7.0.0)
