### ISSUE TITLE
Npm dependency warning 

### ISSUE THREAD

**Issue by learnuser521** [swimlane/ngx-graph#208]
**Describe the bug**
Peer Dependency warning even if the dependencies are installed

**Screenshots**
![Code_2019-06-10_11-19-22](https://user-images.githubusercontent.com/26797047/59210033-40ba6200-8b72-11e9-9592-76c1c0bf2157.png)

**ngx-graph version**
6.0.1

**Additional context**
"@angular/animations": "~7.2.0",
    "@angular/cdk": "^7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@swimlane/ngx-graph": "^6.0.1",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"

**Comment by marjan-georgiev** [comment]
This should be resolved by this commit: https://github.com/swimlane/ngx-graph/commit/01a48eae66162e6dff6fc50d375ad2d9d1ff195a

and will be fixed in the next release.
