### ISSUE TITLE
How can I add a custom Layout?

### ISSUE THREAD

**Issue by mvenin** [swimlane/ngx-graph#217]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo**
Provide an online demo (stackblitz, codesandbox, or similar) where the issue can be reproduced 

**ngx-graph version**
Specify the version of ngx-graph where this bug is present

**Additional context**

**Comment by mvenin** [comment]
in LayoutService, all layouts are declared with: const layouts.
const layouts = {  dagre: DagreLayout, ... }
export class LayoutService {..}
How can I add a new layout to may <ngx-graph ..>?

**Comment by marjan-georgiev** [comment]
See the docs:

https://swimlane.github.io/ngx-graph/#layouts#custom-layouts

**Comment by mvenin** [comment]
From  projects/swimlane/ngx-graph/src/lib/graph/layouts/layout.service.ts
LayoutService#getLayout() cannot discover the new layout.
```
const layouts = {
  dagre: DagreLayout,
  dagreCluster: DagreClusterLayout,
  dagreNodesOnly: DagreNodesOnlyLayout,
  d3ForceDirected: D3ForceDirectedLayout,
  colaForceDirected: ColaForceDirectedLayout
};

@Injectable()
export class LayoutService {
  getLayout(name: string): Layout {
    if (layouts[name]) {
      return new layouts[name]();
    } else {
      throw new Error(`Unknown layout type '${name}'`);
    }
  }
}
```

**Comment by marjan-georgiev** [comment]
You need to implement a class with the Layout interface, then create an object from that class, and pass that object to the `layout` input instead of the string.

Here's a component that shows how to do that:
https://github.com/swimlane/ngx-graph/blob/master/src/docs/demos/components/ngx-graph-custom-curve/ngx-graph-custom-curve.component.ts#L15

**Comment by mvenin** [comment]
I wanted to allow the user to change the layout from a dropdown where I add custom layouts also. 
`myGhraph.setlayout(this.myLayout)` is not the way to go. I'll take your approach. Thx
