### ISSUE TITLE
Static Injector Error Tooltip Service

### ISSUE THREAD

**Issue by Calidus** [swimlane/ngx-graph#221]
**Describe the bug**
Using ngx-graph 6.1.0 and ngx-charts 10.1.0 I am seeing run time static injector errors when using build --prod or --aot. These errors also don't appear when using ng serve. These errors don't come up when using build --prod or --aot  when using ngx-graph 6.0.0 and ngx-charts 10.0.0. 

`swimlane-ngx-graph.d.ts.GraphComponent.html:1`

`message: StaticInjectorError(AppModule)[TooltipService -> InjectionService]: \n  StaticInjectorError(Platform: core)[TooltipService -> InjectionService]: \n    NullInjectorError: No provider for InjectionService!`

`stack:"Error: StaticInjectorError(AppModule)[TooltipService -> InjectionService]: \n  StaticInjectorError(Platform: core)[TooltipService -> InjectionService]: \n    NullInjectorError: No provider for InjectionService!\n    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (http://localhost:4200/vendor.js:27077:19)\n    at resolveToken (http://localhost:4200/vendor.js:27322:24)\n    at tryResolveToken (http://localhost:4200/vendor.js:27266:16)\n    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (http://localhost:4200/vendor.js:27163:20)\n    at resolveToken (http://localhost:4200/vendor.js:27322:24)\n    at tryResolveToken (http://localhost:4200/vendor.js:27266:16)\n    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (http://localhost:4200/vendor.js:27163:20)\n    at resolveNgModuleDep (http://localhost:4200/vendor.js:39399:29)\n    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (http://lo...`
 

**ngx-graph version**
6.1.0

**Additional context**
I am still using Angular 7.

**Comment by KingDarBoja** [comment]
Hello @Calidus,

Your bug is already related to #105. You can check the related issue to find out how to solve it.

Cheers!

**Comment by kkseven07** [comment]
This errors exists for more than a year. Why developers aren't fixing it? I tried all provided workarounds and can't get rid of this cycling error. 

angular-core - 8.0.3
ngx-graph - 6.1.0
ngx-charts - 10.1.0

Tried also angular-core - 7+, ngx-charts from 10 to 12 version. 
It works only in simple dev mode. When I try to use `--configuration=ru` with i18n, I face this error. Any solutions?!!!

**Comment by Calidus** [comment]
Its a open source project, don't complain about other developers not fixing bugs.

Make sure you set package file to do a exact matches for ngx-graph and ngx-chart.

Looks like some fixes are in the works with moving to ng-packegr.
