### ISSUE TITLE
NullInjectorError: StaticInjector(AppModule)[TooltipService -> InjectionService]

### ISSUE THREAD

**Issue by kkseven07** [swimlane/ngx-graph#222]
It happens only when the ngx-graph component is rendered with `ng serve --configuration=ru` using angualar i18n.
The error is cycling.

**Screenshots**
![Screen Shot 2019-07-02 at 1 19 53 PM](https://user-images.githubusercontent.com/25701048/60492655-3c92e780-9ccd-11e9-928c-81ea4507d375.png)

**ngx-graph version**
6.1.0
**ngx-charts version**
12.0.1
**angular/core version**
8.0.3

**Additional context**
I know there are several topics, but all the solutions are not working for me and I noticed that the error is a bit different from all others(NullInjectorError). The project is compiling without errors

I import ngxGraphModule in shared module, which is imported by App and other module.

**Comment by kkseven07** [comment]
Seems like the problem is related to configuration where `"aot":true`

**Comment by abjagtap** [comment]
@kkseven07 , Facing the same issue?
