### ISSUE TITLE
ERROR Error: Cannot read property 'x' of null using colaForceDirected layout and a relation to self

### ISSUE THREAD

**Issue by Lauriy** [swimlane/ngx-graph#225]
**Describe the bug**
A link from node A to node A (itself) breaks colaForceDirected graphs with the aforementioned error.

**To Reproduce**
1. Install ngx-graph according to the instructions on Github
2. Use the 'Custom Templates' example code
3. Switch the layout to 'colaForceDirected'
4. Make a reference to self in the graph
5. View the console

**Expected behavior**
A relation to the node itself gets drawn. Maybe something like this?
http://dugai.club/wp-content/uploads//2018/08/reflexive-definition-math-matrix-representation-of-reflexive-relations-reflexive-relation-mathematics-definition.jpg

**Screenshots**
https://i.imgur.com/YbbyaI6.png

**Demo**
https://stackblitz.com/edit/angular-x7dwy5

**ngx-graph version**
6.1.0

**Comment by assafsun** [comment]
Do we know if this layout should support this case? Why do you think it's a bug?

**Comment by assafsun** [comment]
Removing the bug label from this.
cc: @marjan-georgiev

**Comment by Lauriy** [comment]
Well, it should at least break in a more elegant way than this : )

**Comment by assafsun** [comment]
Closing this, please open is this is still active\relevant.

Thanks.
