### ISSUE TITLE
Since Version 6: ERROR TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Laruu** [swimlane/ngx-graph#226]
**Describe the bug**
Everything worked fine with the previous version, but now i get errors

Here is my code:
` 
<div id="graph-parent">
  <ngx-graph
    class="chart-container"
    [links]="hierarchialGraph.links"
    [nodes]="hierarchialGraph.nodes"
    [legend]="true"
    [curve]="curve"
    [draggingEnabled]="false"
    >

    <ng-template #defsTemplate>
      <svg:marker id="arrow" viewBox="0 -5 10 10"
      refX="8" refY="0"
      markerWidth="4" markerHeight="4" orient="auto">
        <svg:path d="M0,-5L10,0L0,5" class="arrow-head" />
      </svg:marker>
    </ng-template>

    <ng-template #nodeTemplate let-node>
      <svg:g class="node"
      ngx-tooltip
      [tooltipPlacement]="'bottom'"
      [tooltipType]="'tooltip'"
      [tooltipTitle]="'ID: ' + node.id + ' <br> ' + node.description"
      (click)="chooseNode(node.id)"
      >

        <svg:rect
          [attr.width]="node.dimension.width"
          [attr.height]="node.dimension.height"
          [attr.fill]="node.data.color"
        />
        <svg:text
          alignment-baseline="central"
          [attr.x]="10"
          [attr.y]="node.dimension.height / 2"
        >
        {{node.label}}
        </svg:text>
      </svg:g>
    </ng-template>

    <ng-template #linkTemplate let-link>
      <svg:g
      class="edge"
      (click)="chooseLink(link.source, link.target)"
      >
        <svg:path
          class="line"
          stroke-width="2"
          marker-end="url(#arrow)" >
        </svg:path>
        <svg:text
          class="edge-label"
          text-anchor="middle">
        <textPath
                  class="text-path"
                  [style.dominant-baseline]="link.dominantBaseline"
                  [attr.href]="'#' + link.id"
                  startOffset="60%">
          {{link.label}}
        </textPath>
      </svg:text>
      </svg:g>
    </ng-template>

  </ngx-graph>
</div>
`

This is the error i get:

`
ERROR TypeError: Cannot read property 'id' of undefined
    at swimlane-ngx-graph.js:82
    at Array.find (<anonymous>)
    at _loop_1 (swimlane-ngx-graph.js:82)
    at DagreLayout.push../node_modules/@swimlane/ngx-graph/fesm5/swimlane-ngx-graph.js.DagreLayout.run (swimlane-ngx-graph.js:94)
    at GraphComponent.push../node_modules/@swimlane/ngx-graph/fesm5/swimlane-ngx-graph.js.GraphComponent.draw (swimlane-ngx-graph.js:1525)
    at swimlane-ngx-graph.js:1494
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17280)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
`

**Screenshots**
I only get one black rectangle:

![id of undefined](https://user-images.githubusercontent.com/22962642/61457148-f6de4c00-a967-11e9-97d6-5ebf71a96c76.PNG)

I tried downgrading ngx-graph, but the error still remains.
Does anyone know what I am doing wrong?
Or where i can get a solution for my problem?

**Comment by marjan-georgiev** [comment]
Can you create a stackblitz please? It's possible there's an issue with your data.

**Comment by assafsun** [comment]
Please check the nodes and links that you are passing to the graph.
In addition, do you use clusters?

**Comment by Laruu** [comment]
here is my data.model:

````
export interface Diagram {
  KdNr: string;
  Kundenname: string;
  domains: [{
    name: string;
    in: {
      graph: {
        nodes: Nodes[];
        links: Links[];
      }
    };
    out: {
      graph: {
        nodes: Nodes[];
        links: Links[];
      }
    };
  }];
}

export interface Nodes {
  id: string;
  label: string;
  description: string;
}

export interface Links {
  id: string;
  source: string;
  target: string;
  label: string;
}
````

and the data i pass looks like this: 

```
{nodes: Array(3), links: Array(3)}
links: Array(3)
0: {_id: "5d42afdaac882b20dc94027d", id: "aepu7", source: "0", target: "1", label: "sendet"}
1: {_id: "5d42afdaac882b20dc94027c", id: "akkay", source: "1", target: "2", label: ""}
2: {_id: "5d42afdaac882b20dc94027b", id: "afd5f", source: "2", target: "3", label: "Empf. domain"}
length: 3
__proto__: Array(0)
nodes: Array(3)
0: {_id: "5d42afdaac882b20dc94027a", id: "0", label: "Client", description: "Client", meta: {…}, …}
1: {_id: "5d42afdaac882b20dc940279", id: "1", label: "Mail Server", description: "zb. "Exchange/Tobit"?", meta: {…}, …}
2: {_id: "5d42afdaac882b20dc940278", id: "2", label: "Firewall", description: "Default: On Premise öfftl. IP: ???", meta: {…}, …}
length: 3
__proto__: Array(0)
__proto__: Object
```

I dont know... I dont feel like the error is in my data... it used to work before with the same data...
only thing i changed is I added ids to the links

**Comment by assafsun** [comment]
Interesting..
Try the following:
1. Remove all your metedata attributes such as description, meta etc.
2. Set all labels as an empty string.

Can you please send your input parameters to ngx-graph? in your first message, you added only the inside content.

In general, it seems that after running Dagre, the node is not found when it's being searched inside the return object.

**Comment by Laruu** [comment]
Weird thing I found:

here is some default data I pass and it's working fine as it should:

```
const standardGraphIncome = {
      nodes: [{
        id: '0',
        label: 'Name',
        description: 'Domain'
      }, {
        id: '1',
        label: 'Provider',
        description: ''
      }, {
        id: '2',
        label: 'NameServer',
        description: ''
      }, {
        id: '3',
        label: 'MX Record',
        description: ''
      }, {
        id: '4',
        label: 'Firewall',
        description: 'Default: On Premise\nöfftl. IP: ???'
      }, {
        id: '5',
        label: 'Mail Server',
        description: 'zb. "Exchange/Tobit"?'
      }, {
        id: '6',
        label: 'Client',
        description: 'Client'
      }],

      links: [{
        id: null,
        source: '0',
        target: '1',
        label: 'gehostet bei'
      }, {
        id: null,
        source: '0',
        target: '2',
        label: 'liegt bei'
      }, {
        id: null,
        source: '2',
        target: '3',
        label: ''
      }, {
        id: null,
        source: '3',
        target: '4',
        label: ''
      }, {
        id: null,
        source: '4',
        target: '5',
        label: ''
      }, {
        id: null,
        source: '5',
        target: '6',
        label: 'verteilt an'
      }]
    };
```

But if I use my other default data, I get the error:

```
const standardGraphOutcome = {
      nodes: [{
        id: '0',
        label: 'Client',
        description: 'Client'
      }, {
        id: '1',
        label: 'Mail Server',
        description: 'zb. "Exchange/Tobit"?'
      }, {
        id: '2',
        label: 'Firewall',
        description: 'Default: On Premise öfftl. IP: ???'
      }],

      links: [{
        id: null,
        source: '0',
        target: '1',
        label: 'sendet'
      }, {
        id: null,
        source: '1',
        target: '2',
        label: ''
      }, {
        id: null,
        source: '2',
        target: '3',
        label: 'Empf. domain'
      }]
    };
```

**Comment by abjagtap** [comment]
` multigraph: false,
compound: true`
Just comment above lines.

**Comment by assafsun** [comment]
Closing this one for now. let me know if I missed something and will open it.

**Comment by sm-cdecker** [comment]
Yeah, where is the documentation on how to set those values? I'm only seeing documentation for configuring layout via string and not via object...

**Comment by sweeneki** [comment]
try in your HTML: layout="dagreCluster" (not simply "dagre"). This fixed it for me.

**Comment by lingberries** [comment]
Try removing id from links
