### ISSUE TITLE
Export existing layouts

### ISSUE THREAD

**Issue by maleet** [swimlane/ngx-graph#227]
**Is your feature request related to a problem? Please describe.**
Would like to use existing layout with custom defaultSettings

**Describe the solution you'd like**
Add existing layouts export to public_api

**Describe alternatives you've considered**
Copy of existing layout just for custom values for initial rendering. Created dublicate code and if anything fixed/changed in this library... then I need to manually sync these

**Comment by assafsun** [comment]
For dagre you can override the default setting

**Comment by assafsun** [comment]
Closing this one.
1. For your own custom layout, you can pass your own file.
2. For dagre deafult settings, you can override them using the input binding layoutSettings
