### ISSUE TITLE
Implement custom ranking/layering for nodes

### ISSUE THREAD

**Issue by billywzliu** [swimlane/ngx-graph#230]
**Is your feature request related to a problem? Please describe.**
I have nodes which should fit into one of seven layers (columns) in the final diagram. Each node has a parameter in `data` describing which layer it should be in.

**Describe the solution you'd like**
Provide a layering accessor. "A layering accessor takes a dag and assigns every node a layer attribute from zero to the number of layers" from https://github.com/erikbrinkman/d3-dag

**Describe alternatives you've considered**
I have attempted to create a custom layout and forcing a custom ranking, however the ranks are automatically set in one of the three ranking algorithms provided.

**Comment by assafsun** [comment]
Is using Dagre clusters (setParent) helps the layers divide?

**Comment by billywzliu** [comment]
Thanks @assafsun, I am using Dagre clusters now. While clusters do group the nodes into columns, the current implementation allows the possibility of multiple clusters to be in one column (instead of one cluster per column in the layout.)
