### ISSUE TITLE
NGX-Graph Online Meeting

### ISSUE THREAD

**Issue by assafsun** [swimlane/ngx-graph#235]
Hi All, we will want to schedule our first ngx-graph online meeting for sharing updates, basic and advanced graph use, and answering questions that may help a lot of people.
I think sharing work between us can help in each one daily tasks using ngx-graph so keep an open mind on this idea.
If you are interested, send me a private message on Gitter with your name, email and your timezone (link can be found on the project main page).
Once we will understand how many people are interested, we will schedule our first online meeting.
Feel free to comment what do you think on this idea.
Thanks, Assaf

**Comment by assafsun** [comment]
Hi All, we will tentative schedule our first ngx-graph meeting at September 23 at 19:00 GMT time. the meeting will focus on introduction, project update, common scenarios and questions. if you want to join the meeting, please send me a private message with your name, email and timezone. don't miss it :)

**Comment by sweeneki** [comment]
Hi Assad,

CET. Zurich. 

Looking forward. 

Kieran Sweeney 
Sent from my iPhone
+41 79 959 37 59

On Sep 6, 2019, at 07:53, Assaf Shemesh <notifications@github.com> wrote:

Hi All, we will tentative schedule our first ngx-graph meeting at September 23 at 19:00 GMT time. the meeting will focus on introduction, project update, common scenarios and questions. if you want to join the meeting, please send me a private message with your name, email and timezone. don't miss it :)

**Comment by assafsun** [comment]
Updating that the meeting was postponed to October 2 at 19:00 GMT.

**Comment by assafsun** [comment]
Hi All,  an invitation to the meeting next week was created. the meeting will take place at October 2 at 19:00 GMT, if additional people want to join the meeting, please send me a message with your name and email.
