### ISSUE TITLE
Distance between root nodes

### ISSUE THREAD

**Issue by kkseven07** [swimlane/ngx-graph#236]
Some time ago I've opened an issue about nodes' width. The direct advice was to add a fixed number of pixels to the width of the nodes to make it look properly. However, in the example you can see that if I add the width to the nodes, the curves of the first tree go through the nodes of the next tree. My question: is there any possibility to make the distance between to root nodes more so that two trees do not go through each other?

**To Reproduce**
1. Make a graph with two root nodes
2. Add custom fixed width to html 'rect' element.
3. It also happens when the nodes' width is more than 100px without adding any fixed value to the width.
**Expected behavior**
The next root node should be located under the whole previous tree.

**Demo**
[Stackblitz demo](https://stackblitz.com/edit/ngx-graph-demo-pm8i1t)

**ngx-graph version**
@swimlane/ngx-graph": "^6.1.0"

I need it to look like this, however I reached this result when I added one more node to the second tree.
![Screen Shot 2019-08-06 at 11 50 29 AM](https://user-images.githubusercontent.com/25701048/62514265-82991900-b840-11e9-996b-1414895d4667.png)

This screenshots shows how it looks in my project, the curves go through the nodes of the same tree, not only through the next tree.
![Screen Shot 2019-08-06 at 1 36 59 PM](https://user-images.githubusercontent.com/25701048/62520435-68b30280-b84f-11e9-8a30-e0db01bed2b7.png)

**Comment by assafsun** [comment]
I suggest that you will play with dagre rank settings value. try to extend them.

Please note that you can override the default setting by adding an input binding of settings

**Comment by kkseven07** [comment]
> I suggest that you will play with dagre rank settings value. try to extend them.
> 
> Please note that you can override the default setting by adding an input binding of settings

Can you provide a little bit more information about dagre rank settings(with code if possible). According to documentation, I can't understand how I should do this

**Comment by assafsun** [comment]
Look at 
https://github.com/swimlane/ngx-graph/blob/2e38a41fffd5c5d1aff9f24d034b7a095eeb1cb4/projects/swimlane/ngx-graph/src/lib/graph/layouts/dagre.ts#L41

Those settings are part of dagre which is the layout engine.

You  can override it with the following input:
https://github.com/swimlane/ngx-graph/blob/2e38a41fffd5c5d1aff9f24d034b7a095eeb1cb4/projects/swimlane/ngx-graph/src/lib/graph/graph.component.ts#L95

**Comment by kkseven07** [comment]
> Look at
> https://github.com/swimlane/ngx-graph/blob/2e38a41fffd5c5d1aff9f24d034b7a095eeb1cb4/projects/swimlane/ngx-graph/src/lib/graph/layouts/dagre.ts#L41
> 
> Those settings are part of dagre which is the layout engine.
> 
> You can override it with the following input:
> https://github.com/swimlane/ngx-graph/blob/2e38a41fffd5c5d1aff9f24d034b7a095eeb1cb4/projects/swimlane/ngx-graph/src/lib/graph/graph.component.ts#L95

Well, I've played with the settings, it kinda helped, however all paddings are set to all the nodes/edges/curves, which makes the tree much bigger. Is there any possibility to increase the padding between two trees(two root nodes)?

**Comment by vatsalpande** [comment]
@kkseven07 - How did you ultimately resolve this? If you can show a code snippet that will be really helpful
