### ISSUE TITLE
Multiple Links appear as single straight line on drag of any node. Possibly the curve property gets reset.

### ISSUE THREAD

**Issue by sbharam** [swimlane/ngx-graph#238]
**Describe the bug**
A graph could have multiple links between two nodes. I noticed ngx-graph is properly rendering it. However when any one of node on the graph is either select or drag then all that multiple links became a single link. Not sure if this is a bug or require some enhancement.

**To Reproduce**
1. Go to initially render graph
2. Click on or drag any node
3. See error - Multiple links get converted into single link

**Expected behavior**
Want to retain multiple links as it is when were initially load not to become single link when user drag or select the node on graph.

**Screenshots**
1. Initially rendered Graph view: where properly shown multiple links i.e. Link 1, Link 2 & Link 3 

![image](https://user-images.githubusercontent.com/24386905/63747715-6b8c9a80-c8c5-11e9-84c0-a355ecf262b4.png)

2. Graph view after any node drag: where Link 1, Link 2 & Link 3 appear as single link.

![image](https://user-images.githubusercontent.com/24386905/63747855-b60e1700-c8c5-11e9-8c78-724f97854634.png)

**ngx-graph version**
6.1.0

**Comment by assafsun** [comment]
Inside the custom layout file, we need to update the points again on every drag. I think there are some examples that do support it and you can see that the line is not change during drag

**Comment by fendri-x** [comment]
Thank you for responding @assafsun to this issue, could you please share the examples that support separate links during a drag

**Comment by assafsun** [comment]
Sure, please check the following code in the organization tree example.
https://github.com/swimlane/ngx-graph/blob/184ce5aea8accadd6b72756a8d470e9da1d2d652/src/docs/demos/components/ngx-graph-org-tree/customDagreNodesOnly.ts#L77

After running the dagre layout, the points are custom built based on the nodes position - the points are not taken from dagre.

By modify the updateEdge function, on each drag, ngx-graph will recalculate the edge and will keep the line. 

Try to drag a node inside the organization tree example, you can navigate it to from the left pane inside ngx-graph demo.

I'm closing this issue for now, hope that it helps.

**Comment by sbharam** [comment]
@assafsun The suggested solution is not working for me. Please check the below demo link: https://stackblitz.com/edit/ngx-graph-demo-dryz5z?file=src%2Fapp%2FdagreNodesOnly.ts

**Comment by assafsun** [comment]
Hi,

This is an open source project that can be maintained by everyone, I offered you a solution that works but you encountered on a new use case which is interesting. 

Your phrasing of "Please review demo code & suggest a solution that will be much helpful & appreciated." is not the right approach IMO as I'm not an owner for your bugs, you are welcome to suggest a solution on your own and consult with other developers for the best solution for you.
My role is here to try to track open issues and help as much as I can.

Please note that the end solution can be used only on your custom layout file for your use case so you can investigate this issue without any code changes from ngx-graph

**Comment by alindberg** [comment]
This is still an issue with 8.0.0.rc1
