### ISSUE TITLE
Adding images to graph nodes are not displayed immediately 

### ISSUE THREAD

**Issue by wassim-azirar** [swimlane/ngx-graph#242]
**Describe the bug**
I changed the ng-template of the nodes to display an svg image inside a circle.
In my local environnement, the images don't show at all. In stackblitz, the images are not showed immediately, but if I make a change to the code to force the view to refresh the images get showed.

**To Reproduce**
1. Go to [demo](https://stackblitz.com/edit/angular-efytvy)
2. You will see two circles but no image inside.
3. Open app.component.ts and make any change.
4. The images get showed.

**Expected behavior**
I expect the images to show immediately without any changes in the code to force reshresh of the view.

**Screenshots**
![error](https://user-images.githubusercontent.com/670586/64027168-7141e480-cb40-11e9-85fe-238027af9b07.png)

**ngx-graph version**
"@swimlane/ngx-graph": "^6.1.0",

**Comment by KingDarBoja** [comment]
Hello @wassim-azirar,

You should use `defs-template` as you can see on my [fork](https://stackblitz.com/edit/angular-ngx-graph-defs-example) from your demo.

Don't forget to check the [official docs](https://swimlane.github.io/ngx-graph/#custom-templates#defs-template).

Hopefully, the project team will implement some custom demos for each of these template options at some point.

Cheers!

**Comment by marjan-georgiev** [comment]
Closing as resolved.
