### ISSUE TITLE
Glitching edges and nodes when using colaForceDirected and overlapping clusters

### ISSUE THREAD

**Issue by risavkarna** [swimlane/ngx-graph#245]
**Describe the bug**
When cluster nodes are overlapping and colaForceDirected is enabled, the nodes that are found in more than 1 clusters and/or the edges related to those nodes keep moving.

**To Reproduce**
1. Create 2 or more clusters.
2. Create 2 or more disconnected graphs.
3. Add 2 or more nodes from different graphs in multiple clusters.
4. See error in linked screencast -> The nodes and related edges keep moving

**Expected behavior**
Expected to see the 'force' feature to 'stabilize' the movements of edges and nodes after finding the optimum positions. 

**Screencast**
In the screencast, I try to move the shaky nodes to see if I can nudge them to a more stable layout. See [here](https://i.imgur.com/fIUGQrS.mp4)

**Repo**
Stackblitz couldn't serve this workspace setup but might be handy to browse the github repo where the bug can be seen:

https://stackblitz.com/github/CUREDIT/n-graf

https://github.com/CUREDIT/n-graf

**ngx-graph version**
6.2.0

**Comment by assafsun** [comment]
Is this still relevant?

**Comment by assafsun** [comment]
Closing this issue.
