### ISSUE TITLE
GraphComponent  is part of the declarations of 2 modules

### ISSUE THREAD

**Issue by self-ads** [swimlane/ngx-graph#247]
I'm trying to build an angular project using the AOT build mode:

         ng build --prod

When I run build with the --prod switch, I receive the following error:

        ERROR in : Cannot determine the module for class GraphComponent in 
        C:/Users/yassine/Documents/NetBeansProjects/Horizon/CRMApplication
        /node_modules/@swimlane/ngx-graph/src/graph/graph.component.ts! Add 
        GraphComponent to the NgModule to fix it.

I followed its instructions and added GraphComponent to the NgModule:

        ERROR in : Type GraphComponent in 
        C:/Users/yassine/Documents/NetBeansProjects/Horizon
        /CRMApplication/node_modules/@swimlane/ngx- graph/release/graph
        /graph.component.d.ts is part of the declarations of 2 modules:
        GraphModule in C:/Users/yassine/Documents/NetBeansProjects/Horizon/
        CRMApplication/node_modules/@swimlane/ngxgraph/release/graph
         /graph.module.d.ts and AppModule in C:/Users/yassine/Documents/
         NetBeansProjects/Horizon/CRMApplication/src/app/app.module.ts! Please
         consider moving GraphComponent in C:/Users/yassine/Documents/Net
         BeansProjects/Horizon/CRMApplication/node_modules/@swimlane/ngx- 
         graph/release/graph/graph.component.d.ts to a higher module that imports 
          GraphModule in 
          C:/Users/yassine/Documents/NetBeansProjects/Horizon/CRMApplication
         /node_modules/@swimlane/ngx-graph/release/graph/gr
         aph.module.d.ts and AppModule in 
         C:/Users/yassine/Documents/NetBeansProjects/Horizon/CRMApplication
         /src/app/app.module.ts. You can also create a new NgModule that exports 
         and includes GraphComponent in 
         C:/Users/yassine/Documents/NetBeansProjects/Horizon/CRMApplication
        /node_modules/@swimlane/ngx-graph/release/graph/graph.component.d.ts then 
         import that NgModule in GraphModule in 
        C:/Users/yassine/Documents/NetBeansProjects/Horizon/CRMApplication
        /node_modules/@swimlane/ngx-graph/release/graph/graph.module.d.ts and 
        AppModule in C:/Users/yassine/Documents/NetBeansProjects/Horizon
        /CRMApplication/src/app/app.module.ts.

**Comment by self-ads** [comment]
I'm trying to build an angular project using the AOT build mode:

        ng build --prod

When I run build with the --prod switch, I receive the following error:

       ERROR in : Cannot determine the module for class GraphComponent in 
       C:/Users/yassine/Documents/NetBeansProjects/Horizon/CRMApplication
        /node_modules/@swimlane/ngx-graph/src/graph/graph.component.ts! Add 
       GraphComponent to the NgModule to fix it.

I followed its instructions and added GraphComponent to the NgModule:


ERROR in : Type GraphComponent in 
 C:/Users/yassine/Documents/NetBeansProjects/Horizon
 /CRMApplication/node_modules/@swimlane/ngx- graph/release/graph
 /graph.component.d.ts is part of the declarations of 2 modules:
 GraphModule in C:/Users/yassine/Documents/NetBeansProjects/Horizon/
CRMApplication/node_modules/@swimlane/ngxgraph/release/graph
/graph.module.d.ts and AppModule in C:/Users/yassine/Documents/
NetBeansProjects/Horizon/CRMApplication/src/app/app.module.ts! Please
consider moving GraphComponent in C:/Users/yassine/Documents/Net
BeansProjects/Horizon/CRMApplication/node_modules/@swimlane/ngx- 
graph/release/graph/graph.component.d.ts to a higher module that imports 
GraphModule in 
C:/Users/yassine/Documents/NetBeansProjects/Horizon/CRMApplication
/node_modules/@swimlane/ngx-graph/release/graph/gr
aph.module.d.ts and AppModule in 
C:/Users/yassine/Documents/NetBeansProjects/Horizon/CRMApplication
/src/app/app.module.ts. You can also create a new NgModule that exports 
 and includes GraphComponent in 
C:/Users/yassine/Documents/NetBeansProjects/Horizon/CRMApplication
/node_modules/@swimlane/ngx-graph/release/graph/graph.component.d.ts then 
import that NgModule in GraphModule in 
C:/Users/yassine/Documents/NetBeansProjects/Horizon/CRMApplication
/node_modules/@swimlane/ngx-graph/release/graph/graph.module.d.ts and 
 AppModule in C:/Users/yassine/Documents/NetBeansProjects/Horizon
 /CRMApplication/src/app/app.module.ts.

**Comment by self-ads** [comment]
the problem is the version of the labrary use 

       version 6.1.0

**Comment by assafsun** [comment]
Is this still reproduce?

**Comment by assafsun** [comment]
Closing this for now, if the issue still reproduce, please open a new issue
