### ISSUE TITLE
 Individual Line Styles

### ISSUE THREAD

**Issue by alecosborne** [swimlane/ngx-graph#248]
I have to express a variety of things in my graph. Above all, it bothers me that I can not select a line type for each Link / Edge.

<img width="281" alt="sample" src="https://user-images.githubusercontent.com/13859208/65355706-d72b0480-dbf2-11e9-98d0-ed152ecbe772.png">
.

It would be great if you could specify a CSS class with the definition of an edge.

export const links: Edge[] = [
  {
    id: 'a',
    source: 'first',
    target: 'second',
    label: 'is parent of',
    styleclass: 'own-edge-line-style-dashed'
  },
  {
    id: 'aa',
    source: 'second',
    target: 'first',
    label: 'is parent of'
    styleclass: 'own-edge-line-style-solid-line'
  }, {

**Comment by Fahnenschwinger** [comment]
I didn't test it but shouldn't this be possible currently?
Pass custom data like "styleclass" in the edge array and in the html use the data with ngStyle or ngClass?

sth. like 
```[ngClass]="{'is--lineTypeOne': link.styleclass === 'lineOne'}"```

on the link template?

**Comment by marjan-georgiev** [comment]
You can use custom templates and style the lines based on the properties of the Edge objects:
```
<ng-template #linkTemplate let-link>
  <svg:g class="edge">
    <svg:path
      *ngIf="!link.label || link.label === ''"
      class="line"
      stroke-width="2"
    ></svg:path>
    <svg:path
      *ngIf="link.label === 'success'"
      class="line line-success"
      stroke-width="1"
    ></svg:path>
    <svg:path
      *ngIf="link.label === 'failure'"
      class="line line-error"
      stroke-width="5"
    ></svg:path>
  </svg:g>
</ng-template>
```

**Comment by assafsun** [comment]
Closing this issue as a solution was given.
Please open a new issue if needed.
