### ISSUE TITLE
Make Clusters accessable through "PanToNode"

### ISSUE THREAD

**Issue by Fahnenschwinger** [swimlane/ngx-graph#249]
**Is your feature request related to a problem? Please describe.**
In a graph with multiple clusters which contain multiple nodes, the graph gets insanely huge.
For a better overview and an improved feel for the user, it would be very helpful to be able to pan not only to a node but also to a cluster and make it so it fills the viewport (zoom it).
This way the users would just need to focus on one part of the whole graph and make it easier to understand.

**Describe the solution you'd like**
I am looking for a feature where the panToNode function gets enhanced so that it can not just pan to a node, but also a cluster.
Internally both nodes and clusters seem to be dagreNodes so I suppose they are handled pretty equally. I think that enhancing this functionality shouldn't be too hard to implement.
It would also be very cool to zoom the node/cluster accordingly.
This could maybe be accomplished with an input like:
```
{ 
    id: node-id/cluster-id, 
    zoom: true/false
}
```

 
If this use case is too special, and no one is interested in it. I would also be very thankful for tips.
Maybe I am able to hack it myself so it does what I want :^)

**Comment by Calidus** [comment]
I would find this useful, right now I simulate this by finding a node in the middle of the cluster and using the `panToNode$` observable.

**Comment by assafsun** [comment]
I don't think we can find cluster node because it's not really a node. cluster nodes don't have points after dagre calculate the layout.
You can read about it on dagre project.

I suggest the approch that @Calidus is doing.

I'm closing this for now, if you find that dagre return additional information that can help us, please create a new issue.

Thanks!
