### ISSUE TITLE
Issue with centering graph content inside of drawing area.

### ISSUE THREAD

**Issue by kenisteward** [swimlane/ngx-graph#25]
[X ] feature request

**Current behavior**
Currently when a chart initializes it starts at the top left of the container when set to 'fit to container'
https://swimlane.github.io/ngx-charts-dag/

**Expected behavior**
Would like the option to center the chart inside of its drawing space.  This is currently already done in the original ngx-force-directed
https://swimlane.github.io/ngx-charts/#/ngx-charts/force-directed-graph

Granted the force directed is always centered (not panned)  it would be nice if the initial pan was set so that it was centered on the graph

**What is the motivation / use case for changing the behavior?**
Just having the capability to properly center the graph after data is added or other things.  My use case is as I add new nodes to a clicked node I'd like to center on that node.  Also when the initial graph is created (parents -> center -> children) I would like to have that centered.

* **ngx-charts version:** x.x.x
2.1.4 ngx-charts-dag

* **Angular version:** 2.x.x
4.1.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Just tested in chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS >2.0

**Comment by jawadst** [comment]
@isaacplmann 
I have submitted a PR to introduce an `autoCenter` option to center the graph in the viewport: https://github.com/swimlane/ngx-graph/pull/51

Would you have time to review? I am happy to make any change you want.

**Comment by assafsun** [comment]
Closing this issue as it was fixed and merged.
