### ISSUE TITLE
Clusters MouseEvent / Drag

### ISSUE THREAD

**Issue by Fahnenschwinger** [swimlane/ngx-graph#250]
The graphs in my application are pretty huge!
>\>10 Clusters with >15 nodes each

Each cluster takes a considerable amount of space of the viewport.
Since clusters seem to overwrite the mouse functions like nodes, they cant be used to drag the whole graph.

At the moment you would have to zoom out and find spots where no cluster/node is and drag the graph. This isn't very optimal. 

Is there a way to make it so the graph can also be moved when dragging on a cluster?
At the same time, I would still need the possibility to click a cluster!

**Comment by assafsun** [comment]
Yes, I had this problem, I think you can add a css on visibility: hidden on the clusters inside your code (not inside ngx-graph) in case you don't have a UI for it (for example, background on all the cluster).

**Comment by assafsun** [comment]
Closing this issue, if there is another problem, please open a new issue

**Comment by randomcoggles** [comment]
This worked pretty good for me. But I didn't need my clusters to be clickable:
`
        <svg:path [attr.d]="'M10 10 
           L' + (cluster.dimension.width - 10) + ' 10 
           Q' + cluster.dimension.width + ' 10 ' + cluster.dimension.width + ' 20 
           L' + cluster.dimension.width + ' ' + (cluster.dimension.height - 10) + ' 
           Q' + cluster.dimension.width + ' ' + cluster.dimension.height + ' ' + (cluster.dimension.width - 10) + ' ' + cluster.dimension.height + ' 
           L10 ' + cluster.dimension.height + ' 
           Q0 ' + cluster.dimension.height + ' 0 ' + (cluster.dimension.height - 10) + ' 
           L0 20 
           Q0 10 10 10'" 
           stroke="gray" 
           stroke-dasharray="9 7 9 9"
        fill="none" />`
