### ISSUE TITLE
Nodes Elements hide the arrow and not showing the full text on the arrow path

### ISSUE THREAD

**Issue by HDaghash** [swimlane/ngx-graph#251]
**Describe the bug**

After add some custom svg node 
- the arrow and path between nodes not showing properly  
- the arrows gets hidden under the node svg 
- path not showing the label properly  
**my question**
how to extend the path length between the node and the other one ? 

**Expected behavior**

1-text to be fully showing over the arrow path.
2- arrow to be showing (some of them are hidden under the node circle)

**Demo**
https://stackblitz.com/edit/ngx-graph-demo-test

**ngx-graph version**
6.1

**Comment by assafsun** [comment]
I think dagre has the option of longest path which you can test.

You will need to override the ranker option.
Look at https://github.com/swimlane/ngx-graph/blob/feb91c846d9c850b4f0ea1243786bda8222331fd/projects/swimlane/ngx-graph/src/lib/graph/layouts/dagre.ts#L30

**Comment by HDaghash** [comment]
> I think dagre has the option of longest path which you can test.
> 
> You will need to override the ranker option.
> Look at
> 
> https://github.com/swimlane/ngx-graph/blob/feb91c846d9c850b4f0ea1243786bda8222331fd/projects/swimlane/ngx-graph/src/lib/graph/layouts/dagre.ts#L30

Thanks for your response,
is it doable to do it on the colaForceDirected mode cause I want it to be in circle shape?

**Comment by assafsun** [comment]
Good point, don't think so because it's not dagre.

In that case, you can't extend the space between each node (circle) but maybe you can adjust your line shape to fit better? just a thought

**Comment by allensutton** [comment]
> I think dagre has the option of longest path which you can test.
> 
> You will need to override the ranker option.
> Look at
> 
> https://github.com/swimlane/ngx-graph/blob/feb91c846d9c850b4f0ea1243786bda8222331fd/projects/swimlane/ngx-graph/src/lib/graph/layouts/dagre.ts#L30

I'm having the same problem, but I am in fact using dagre for my layout.  Can you explain more about your proposed solution?  I was trying to see if there was a way to set a minimum length for the SVG path and set it to at least the length of its accompanying label, but overriding the ranker option sounds like it might be easier.

**Comment by assafsun** [comment]
Closing this, @allensutton please open a new issue as it sound different from the original thread.
