### ISSUE TITLE
Multiple Links appear as single straight line on drag of any node.

### ISSUE THREAD

**Issue by sbharam** [swimlane/ngx-graph#252]
**Describe the bug**
When any one of the node on the graph is drag then all associated multiple links/edges between two nodes became a single link/edge. 

**To Reproduce**

1. Go to initially render graph
2. Drag any node
3. Multiple links/edges between two nodes get converted into single link/edge

**Expected behavior**
- Retain multiple links/edges between two nodes as it is when were initially load not to become a single link/line when user drag any node on the graph.

**Demo**
https://stackblitz.com/edit/ngx-graph-demo-dryz5z?file=src%2Fapp%2FdagreNodesOnly.ts

**ngx-graph version**
6.1.0

**Comment by sbharam** [comment]
@assafsun The suggested solution is not working for me for the above issue. Please below PR: 

https://github.com/swimlane/ngx-graph/issues/238

**Comment by AshwinJd** [comment]
This issue still exists in version 7
