### ISSUE TITLE
EmptyErrorImpl when nodes array is empty

### ISSUE THREAD

**Issue by doorman02** [swimlane/ngx-graph#253]
**Describe the bug**
Getting this red error in console of Chrome 
EmptyErrorImpl
message: "no elements in sequence"
name: "EmptyError"
__proto__: Error

because the nodes array is empty. 

**To Reproduce**
1. Graph with empty nodes array 

**Expected behavior**
Should not output an error. Normal behaviour that the nodes array is empty.

**ngx-graph version**
6.2.0

**Comment by dongjunson** [comment]
thank you. i had same issue. so solved it.!!!

**Comment by KingDarBoja** [comment]
Hello @doorman02,

You are not suppose to pass a empty array of nodes as far as I know. Maybe the error being displayed is the expected one for such cases, right @marjan-georgiev ?

Cheers!

**Comment by doorman02** [comment]
Hi @KingDarBoja thanks for your suggestion. However, since the nodes array is bound to the view it feels like it should by default be handled by the graph component. I think the only way to prevent this error is to add a ngIf statement that checks the empty array on the graph element  but it feels a bit of a hack.

**Comment by creekorful** [comment]
Hello all,

I have faced the same error today. Basically I have a component with the following fields declared:

```typescript
  nodes: Node[] = [];
  links: Edge[] = [];
```

And on the **ngOnInit()** I perform an HTTP call to get data and perform a little aggregation and finally I push elements on the nodes and links.

```typescript
ngOnInit() {
   this._service.getServices().subscribe(services => {
      services.forEach(service => {
         this.nodes.push({
            id: service.id,
            label: service.name
         });
         // ...
      });
   });
}
```

However, since the component is being rendered before data are available I face the following error:

```

EmptyErrorImpl {message: "no elements in sequence", name: "EmptyError"}
```
I have tried a workaround by delaying the rendering of the ngx-graph only when data are available (using a **ngIf=""** plugged on nodes array length)

In the component.html

```html
<ngx-graph
  *ngIf="ready"
  [links]="links"
  [nodes]="nodes">
</ngx-graph>
```
In the component.ts

```typescript
  get ready(): boolean {
    return this.nodes.length !== 0 && this.links.length !== 0;
  }
```

But now I am facing another error:

```
ERROR TypeError: Cannot read property 'id' of undefined
```
I don't really know what's going on. Does anyone has faced a similar problem?

**Comment by sweeneki** [comment]
Hi Alois,

I too have exactly the same issue.

Regards

Kieran

**Comment by creekorful** [comment]
Hello @KingDarBoja any news on this?

**Comment by khalilou88** [comment]
any update i am facing the same problem

**Comment by assafsun** [comment]
I think the problem is that you are passing an empty nodes and not empty links array.
In case this is the situation, there is no meaning on empty links without nodes.

**Comment by creekorful** [comment]
@assafsun Sure it make sense. But why do delayed rendering fails with the following error?

```
ERROR TypeError: Cannot read property 'id' of undefined
```

**Comment by assafsun** [comment]
The render should fail but I agree that that code should protect itself better, for example when the graph load it can test this case of empty nodes with defined links.

**Comment by creekorful** [comment]
I don't understand why the rendering should fails if it is delayed until data are available using ngIf for example

**Comment by assafsun** [comment]
The rendering is not failing but the data preparation phase before drawing it.

**Comment by assafsun** [comment]
Adding that the additional missing part that I'm working on is the ability to get this error notification to your code as a consumer of ngx-graph object. this will not solve the case of empty nodes with links but will result that you will have the ability to handle the error on your code.

**Comment by creekorful** [comment]
Looks like there is something I don't understand. How can we use this component if data are not available at parent component (the one that will use ngx-graph) instantiation ? (When using Observable f.e)

**Comment by doorman02** [comment]
@creekorful  sorry for the late answer. In case you are still getting 

`ERROR TypeError: Cannot read property 'id' of undefined`

Verify both the source and target attributes of all the link objects and make sure they are not referencing nodes that do not exist in the nodes array.

Of course it´s a question if the graph component should catch this and allow links to reference nodes that do not 'yet' exist since there are use cases for this. In my case I am aggregating nodes into one node which can be expanded when needed and it would be useful to keep links in the array even though they are not yet being used. Anyway I am now tracking this and keeping unused links out of the links array.

**Comment by doorman02** [comment]
In relation to the original post, I am still faced with the EmptyErrorImpl when nodes array is empty when graph is loaded. It´s a bit strange to treat this as an error since it´s a normal behavior to have an empty nodes and links array.

**Comment by creekorful** [comment]
> @creekorful sorry for the late answer. In case you are still getting
> 
> `ERROR TypeError: Cannot read property 'id' of undefined`
> 
> Verify both the source and target attributes of all the link objects and make sure they are not referencing nodes that do not exist in the nodes array.
> 
> Of course it´s a question if the graph component should catch this and allow links to reference nodes that do not 'yet' exist since there are use cases for this. In my case I am aggregating nodes into one node which can be expanded when needed and it would be useful to keep links in the array even though they are not yet being used. Anyway I am now tracking this and keeping unused links out of the links array.

Good point. It was a little mistake on my side. Now everything is working properly!

Thank you

**Comment by waltersung** [comment]
> Adding that the additional missing part that I'm working on is the ability to get this error notification to your code as a consumer of ngx-graph object. this will not solve the case of empty nodes with links but will result that you will have the ability to handle the error on your code.

I also have this problem.
I think that an empty node array should be a normal input for the graph.
When dealing with data, having an empty dataset is a standard behaviour and should not result in an error.

For example I have two scenarios:
1. I have a graph that begins empty and the user then creates data to add nodes.
2. I want to present filtered data from a dataset - if the filter returns no values the graph should render no nodes

**Comment by rohitbhoite** [comment]
Facing same issue
