### ISSUE TITLE
Toggle Zoom+Pan vs Scroll

### ISSUE THREAD

**Issue by Calidus** [swimlane/ngx-graph#255]
**Is your feature request related to a problem? Please describe.**
Panning the graph becomes difficult if you have a large number of clusters nodes.

**Describe the solution you'd like**
The Zoom + Pan, feature works well but some times it would be useful be able to define to view size and use scroll bars. 

**Describe alternatives you've considered**
I looked into doing this with HTML and CSS outside of ngx-graph but I think it might be better to do inside the graph component itself.

**Comment by assafsun** [comment]
Please check the enableTrackpadSupport for mouse scroll instead of zoom when using the wheel button.

In addition, adding scroll bar is not easy and wrong IMO to SVG. we do want to add a mini map which will solve the navigation issues.

**Comment by Calidus** [comment]
Looks like `enableTrackpadSupport` hasn't been released yet. 

The mini map feature sounds very useful.

**Comment by Calidus** [comment]
What about using Angular's `HostListener` and binding arrow keys to panning the graph?

**Comment by assafsun** [comment]
Update: I created a PR but it was not working good.
The keyboard navigation works but it caught the events also of the parent component which cause some problem.
The main issue here is a good sync between the child and parent component and event handling.

Closing this issue, I'm sure @marjan-georgiev will create a new version soon in case this is was not release yet.
Thanks!
