### ISSUE TITLE
How to disable drag of the whole graph

### ISSUE THREAD

**Issue by piyushpriyam** [swimlane/ngx-graph#256]
I am not able to find something which helps me disable the drag of the ngx-charts

**Comment by dongjunson** [comment]
[draggingEnabled]="false"

eg]
`<ngx-graph [links]="links" [nodes]="nodes" [clusters]="clusters" [curve]="curve" [layout]="layout"
		[layoutSettings]="layoutSettings" [enableZoom]="false" [draggingEnabled]="false" [panningEnabled]="false" [autoZoom]="true" 
		[autoCenter]="true" [animate]="false" [update$]="update$" [center$]="center$" [zoomToFit$]="zoomToFit$" 
		(window:resize)="onResize($event)">`

**Comment by piyushpriyam** [comment]
Yes , it worked
