### ISSUE TITLE
Adding a new node to the nodes array does not update the graph

### ISSUE THREAD

**Issue by CryHenry** [swimlane/ngx-graph#257]
When adding a new node object to the nodes array, bound to the ngx-graph, the graph does not render, it seems to require a call to...

this.update$.next(true);

or 

this.nodes = [...this.nodes];

to force it to display the new node. However, this also forces the graph to re-render in it's entirety. 

Is there a way to have a new node object, added to the nodes array, add to the current render without requiring the entire graph to be redrawn ? I would have thought, as the nodes array is bound to the ngx-graph with the attribute [nodes], the graph would simply add the new svg template to it's current render ?

This also seems to be an issue when modifying the properties of a node object in the nodes array bound to the ngx-graph. When changing the label of a node in the nodes array, the label is not rendered in the graph until a 

this.update$.next(true);

Or 

this.nodes = [...this.nodes]

is called, but again, this causes the entire graph to redraw. 

I must be missing something here as I expected the behaviour of ngx-graph to reflect changes automagically in it's bound nodes array.

**Comment by prabhushan** [comment]
+1 .. this is really needed to retain the last arrangement of the nodes

**Comment by assafsun** [comment]
IMO, this is not an easy case because once adding a new node, you need to calculate the layout again so you can't render only a single node because it may have affect on the other nodes positions.

Being said that, maybe there is an option by using the custom layout and save the result each run and this will make sure that you will have the same layout? not sure yet.

**Comment by assafsun** [comment]
Closing this. Thanks!

**Comment by cedricve** [comment]
how do you rerender this then @assafsun ?
