### ISSUE TITLE
Enable Graph to expand and collapse on node clicks

### ISSUE THREAD

**Issue by skolipaka** [swimlane/ngx-graph#258]
**Is your feature request related to a problem? Please describe.**
Is there a way to collapse and expand the graph on node clicks. It would be helpful with large graphs.

**Describe the solution you'd like**
On graph with click on nodes will collapse/expand sub graph (links, target nodes) originating from the node.

**Describe alternatives you've considered**
I see a click event on node, but doesn't seem to provide any node related information. If node information is provided on click along with sub graph information (links) and couple of methods on nodes & link to hide and show, that would allow users to attach custom behavior on click.

**Comment by novarx** [comment]
I would also be interested in such a feature.

**Comment by darrynhoskingluna** [comment]
This is something that you can add yourself easily.
You can add click events on any part of the SVG in your node template and trigger any function that edits the arrays of nodes links and clusters then just call the update feature on the graph

**Comment by assafsun** [comment]
Agree, I don't think ngx-graph should support it directly but the consumer (user) by modifying the nodes and links array.

Closing this one, @marjan-georgiev FYI
