### ISSUE TITLE
zoom$ observable

### ISSUE THREAD

**Issue by Calidus** [swimlane/ngx-graph#259]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able programmatically set the zoom level. Then developers could build control components to manipulate the zoom level graph.

**Describe the solution you'd like**
Add a zoom$ observable/subject that we can push a value to adjust the current zoom level.

**Describe alternatives you've considered**

**Additional context**

**Comment by assafsun** [comment]
Please use the zoomToFit$ which suppose to do what you ask.

**Comment by xoneill** [comment]
I think the idea was to allow zooming on a click (and not only by scrolling mouse wheel), similar to e.g. Google Maps approach
