### ISSUE TITLE
Allow Legend Title to be set

### ISSUE THREAD

**Issue by kenisteward** [swimlane/ngx-graph#26]
[ X] feature request

**Current behavior**
The component currently generates its own legend options.  Because of this it does not set a Legend title and the user is unable to set a legend title

**Expected behavior**
either [legendTitle] is exposed or the user can set their own legend options.

* **ngx-charts version:** x.x.x
current with latest ngx-charts-dag

**Comment by assafsun** [comment]
I'm closing this issue because it's refer to ngx-charts and not ngx-graph

**Comment by assafsun** [comment]
Hi @kenisteward 

Sorry if I missed something, I'm opening it again in order for better understanding.
Thank you for responding to it.

1. ngx-charts is used as container to ngx-graph. Can you please explain on your description (if possiable screen shots) on the loaded legend and what is missing?

2. If you are refer to the legends on the links than today you can set your own template on the middle of the links.

3. If you are refer to a legend table that is outside the graph (as seen in charts)  than you can craete your own custom legend regardless to the graph that ngx-graph create.

Please update me on the missing items and I will be happy to try to help.

Assaf

**Comment by kenisteward** [comment]
https://github.com/swimlane/ngx-graph/blob/master/src/graph/graph.component.ts#L61

This was what I was referring to in the original post.  

I use your library in this project 
https://github.com/FINRAOS/herd-ui/blob/master/src/app/data-entities/components/data-entity-detail/data-entity-detail.component.html#L300

When I used it originally, I was unable to figure out how to set the legend title to something that I wanted other than the default.  I had assumed an input needed to be added (currently [legend] is a boolean and does not allow you to actually set the title or other things) that would handle all the other legend options.

What is the proper way to change the legend options?

Will update this with screenshots when I reset the dev environment.  I've since moved from that project.

**Comment by assafsun** [comment]
I will check it and will update.

**Comment by marjan-georgiev** [comment]
@kenisteward we will be deprecating the legend feature in the next major version (6.0.0) and remove it in 7.0.0. This change will happen as a side effect of removing the dependency on ngx-charts (thus reducing bundle size and improving performance).

Please consider building a separate legend component outside of the graph if you need one.

**Comment by assafsun** [comment]
Closed due to the legend deprecating in the next major version
