### ISSUE TITLE
Zoom to fit, if less than min should default to min, same for max

### ISSUE THREAD

**Issue by ZachRoberts25** [swimlane/ngx-graph#261]
```  /**
   * Zooms to fit the entier graph
   */
  zoomToFit(): void {
    const heightZoom = this.dims.height / this.graphDims.height;
    const widthZoom = this.dims.width / this.graphDims.width;
    const zoomLevel = Math.min(heightZoom, widthZoom, 1);

    if (zoomLevel <= this.minZoomLevel || zoomLevel >= this.maxZoomLevel) {
      return;
    }
    
    if (zoomLevel !== this.zoomLevel) {
      this.zoomLevel = zoomLevel;
      this.updateTransform();
      this.zoomChange.emit(this.zoomLevel);
    }
  }
```

if the zoom level is greater or less than the max and min, you should just default it to being the min or max, not return.  This got me backwards for a couple hours

**Comment by assafsun** [comment]
In case we will not return, the code will continue to the if statement and will not execute it so in the end, no functionality will run. It's the same as return. what problem did you had?

**Comment by ZachRoberts25** [comment]
It should default to whatever the min and max is if it is over/under that.  I don't think the desire would be for nothing to happen at all.

Our use case is, we have a very large graph that has a reset button that tries to zoom to fit everything, if the necessary zoom to fit the whole graph is greater than the max zoom, then it does nothing.  It should at least zoom to the max zoom in an attempt to fit the whole graph

**Comment by assafsun** [comment]
I think I understand you case but don't understand your problem.
How does the necessary zoom can be greater from the max zoom if we are doing Math.min(heightZoom, widthZoom, 1);

**Comment by assafsun** [comment]
I believe that I understand better your problem, did you had a graph loading issues after adding nodes?
