### ISSUE TITLE
is it possible to add image on the svg path beside <textPath>

### ISSUE THREAD

**Issue by HDaghash** [swimlane/ngx-graph#263]
**Is your feature request related to a problem? Please describe.**
Need to define the relation type between to nodes by adding image along the arrow path beside the text path element 

**Describe the solution you'd like**
i'm asking for solution for this issue !

**Comment by HDaghash** [comment]
Closing the ticket I did it with some custom logic thanks 👍  :

![Screen Shot 2019-10-31 at 10 12 49 PM](https://user-images.githubusercontent.com/15608990/67974464-eb1f4880-fc2b-11e9-9f48-0b028ff2cd76.png)

**Comment by marjan-georgiev** [comment]
That looks awesome! 👍

**Comment by assafsun** [comment]
Can you please share the basic logic for other users? I think it will help

**Comment by HDaghash** [comment]
Thank you guys @marjan-georgiev & @assafsun.

sure thing I'll try to share full source soon but here's the basic idea :

as per what I understood there is no element in SVG will allow you to display image along the path as same as the `<textPath>` element do with the text 

so my task here was to find the coordinates `x,y` for each path start point and then start positioning the images along the path 

my link-template looks like : 

```
<ng-template #linkTemplate let-link>
   <svg:g class="edge">
      <svg:path class="line" stroke-width="4" marker-end="url(#arrow)" [attr.stroke-dasharray]="link.level"></svg:path>
      <image #image *ngFor="let icon of link.icons; let i = index;" (click)="alert('hi')"
      width="5" height="25" [attr.xlink:href]="icon"
      [attr.position]="link.id | getPosition:i:image:link.icons.length:nodes:init" /> 
   </svg:g>
</ng-template>
```

if you noticed we have here a custom pipe : getPosition :


```
import { Pipe, PipeTransform } from '@angular/core';
@Pipe({name: 'getPosition'})
export class GetPositionPipe implements PipeTransform {
  transform(id , index ,image,total,nodes,init): any {
   const iconSize = 28;
   const lineMargin = 5;
    setTimeout(()=>{
    let path:SVGGeometryElement  = document.querySelector('#'+id + ' .line');
    const margin = 40 + (index === 0 ? 0 : (index * iconSize) );
    const target = path.getPointAtLength(margin);
    image.style.transform=`translate(${target.x}px,${target.y  +lineMargin}px)`;
    }) 
  }
}
```
btw @assafsun now i'm adding some nice animations to the paths and this is will reflect my function if the paths start animating before positionsing each icon on it place and  if you noticed here i'm doing setTimeOut function and i'm sending some exrta params to the pipe to make sure to trigger it after the graph is fully drawen that's why i opend the ticket here : https://github.com/swimlane/ngx-graph/issues/264  and it will be helpful if we can have the trigger soon 

**will share with you full working code once I'm done with some small animation**

**Comment by zmzimpl** [comment]
> Thank you guys @marjan-georgiev & @assafsun.
> 
> sure thing I'll try to share full source soon but here's the basic idea :
> 
> as per what I understood there is no element in SVG will allow you to display image along the path as same as the `<textPath>` element do with the text
> 
> so my task here was to find the coordinates `x,y` for each path start point and then start positioning the images along the path
> 
> my link-template looks like :
> 
> ```
> <ng-template #linkTemplate let-link>
>    <svg:g class="edge">
>       <svg:path class="line" stroke-width="4" marker-end="url(#arrow)" [attr.stroke-dasharray]="link.level"></svg:path>
>       <image #image *ngFor="let icon of link.icons; let i = index;" (click)="alert('hi')"
>       width="5" height="25" [attr.xlink:href]="icon"
>       [attr.position]="link.id | getPosition:i:image:link.icons.length:nodes:init" /> 
>    </svg:g>
> </ng-template>
> ```
> 
> if you noticed we have here a custom pipe : getPosition :
> 
> ```
> import { Pipe, PipeTransform } from '@angular/core';
> @Pipe({name: 'getPosition'})
> export class GetPositionPipe implements PipeTransform {
>   transform(id , index ,image,total,nodes,init): any {
>    const iconSize = 28;
>    const lineMargin = 5;
>     setTimeout(()=>{
>     let path:SVGGeometryElement  = document.querySelector('#'+id + ' .line');
>     const margin = 40 + (index === 0 ? 0 : (index * iconSize) );
>     const target = path.getPointAtLength(margin);
>     image.style.transform=`translate(${target.x}px,${target.y  +lineMargin}px)`;
>     }) 
>   }
> }
> ```
> 
> btw now i'm adding some nice animations to the paths and this is will reflect my function if the paths start animating before positionsing each icon on it place and if you noticed here i'm doing setTimeOut function and i'm sending some exrta params to the pipe to make sure to trigger it after the graph is fully drawen that's why i opend the ticket here : #264 and it will be helpful if we can have the trigger soon
> 
> **will share with you full working code once I'm done with some small animation**

Hi,I have a requirement similar to yours. I need to replace `svg:text` with `icon`, but when I refer to your code, I find that `image` is set via `xlink:href="#icon-left_join"` It cannot be displayed normally, and the position of `image` cannot be correctly mapped even if the setTimeout method is used. Can you give me some help? Thanks~
![image](https://user-images.githubusercontent.com/27490895/85946370-806b0c00-b976-11ea-910a-fe20ec006c4e.png)

**Comment by tamaghna-ba** [comment]
can you share how did you add image to the node instance?

**Comment by nemtudom123** [comment]
Hey @HDaghash, how did you link the images to the nodes? I've tried to add them via <image> tag to my customized nodes template, but it's still not showing them. In my list of nodes I've added a label, where I set the path of the image. Any tipps?

**Comment by nemtudom123** [comment]
nevermind, I've fixed it myself! So it works with referencing the image (if anybodys facing same issues). Curios why it didn't worked at first

html add to node:

<image 
       [set styles first]
        [attr.href]="node.image">
  {{node.image2}}
</image>

in the node add your image path
