### ISSUE TITLE
event or subject to trigger when the graph is fully loaded 

### ISSUE THREAD

**Issue by HDaghash** [swimlane/ngx-graph#264]
**Describe the bug**
can't find an event to trigger when the graph is fully loaded 

**Expected behavior**
event or subject, for example, onLoaded$ to subscribe to it to know the graph is fully loaded 
and it's good to go to do your custom logic 

Thanks.

**Comment by assafsun** [comment]
This is not a bug but an enhancement

**Comment by HDaghash** [comment]
@assafsun that's correct, is there a way to catch that?
is the drawing finished once the `tick() `function completed : https://github.com/swimlane/ngx-graph/blob/master/projects/swimlane/ngx-graph/src/lib/graph/graph.component.ts#L385

**Comment by assafsun** [comment]
No but I'm working on an output event that return the loading status (based on functionality), hope to create a PR soon. From UI aspect, you can really know when the UI has finished to render or moreover of the actual draw is correct.

**Comment by HDaghash** [comment]
@assafsun  thanks for the fast response, do we hide the graph for some reason  in case the user was out of the viewport ?

**Comment by assafsun** [comment]
Sorry for the late response, what do you mean?
