### ISSUE TITLE
When data is updated dynamically, link-labels are shown but links are not displayed

### ISSUE THREAD

**Issue by Shubhamgorde** [swimlane/ngx-graph#266]
Describe the bug
When we update data(Links and Nodes) dynamically via API links are not shown whereas labels and nodes are displayed as expected.

Expected behavior
Its expected to display links between nodes

Screenshots

Working with dummy data:
<img width="960" alt="Screen Shot 2019-11-06 at 12 04 24 PM" src="https://user-images.githubusercontent.com/13245531/68273909-b4af5680-008d-11ea-9229-d04e873fd3bd.png">

Issue when data fetched from API:
<img width="492" alt="Screen Shot 2019-11-06 at 12 24 20 AM" src="https://user-images.githubusercontent.com/13245531/68273768-5aae9100-008d-11ea-9e70-1740ac67bb29.png">

Demo
With Dummy data:
https://angular-bge4wk.stackblitz.io/flow (Working as expected)
When API is integrated:
https://angular-bge4wk.stackblitz.io/flow1 . (Causing issue)

ngx-graph version
"@swimlane/ngx-graph": "6.0.0-rc.6"

Additional context

**Comment by assafsun** [comment]
Didn't you tried to bind to the graphUpdate and call for an update?

**Comment by egarantia-lab** [comment]
I have added below line once all nodes and links are generated after API call: this.update$.next(true);

And also added below line in html:
[update$]="update$"
eg : <ngx-graph
id="diagram"
style="pointer-events: none; "
[curve]="curve"
(activate)="onEnter()"
[update$]="update$"
[draggingEnabled]="true"
[enableZoom]="false"
[panningEnabled]="true"
[view]="view"
[links]="links"
[nodes]="nodes"
[layoutSettings]="{ orientation: 'dagreCluster' }"
>

**Comment by Shubhamgorde** [comment]
I have added below line once all nodes and links are generated after API call: this.update$.next(true);

And also added below line in html: 
[update$]="update$"

 eg : <ngx-graph id="diagram" 
style="pointer-events: none;
 " [curve]="curve"
 (activate)="onEnter()"
 [update$]="update$"
 [draggingEnabled]="true" 
[enableZoom]="false"
 [panningEnabled]="true" 
[view]="view"
 [links]="links"
 [nodes]="nodes"
 [layoutSettings]="{ orientation: 'dagreCluster'}"
>

But didn't worked for me

**Comment by Shubhamgorde** [comment]
I have added below line once all nodes and links are generated after API call: this.update$.next(true);

And also added below line in html: 
[update$]="update$"

 eg : <ngx-graph id="diagram" 
style="pointer-events: none;
 " [curve]="curve"
 (activate)="onEnter()"
 [update$]="update$"
 [draggingEnabled]="true" 
[enableZoom]="false"
 [panningEnabled]="true" 
[view]="view"
 [links]="links"
 [nodes]="nodes"
 [layoutSettings]="{ orientation: 'dagreCluster'}"
>

But didn't worked for me

**Comment by rahul-winner** [comment]
We are also experiencing similar problem at our end and investigating it further. The graph gets completely cramped up at our end. 
We could not find any clue yet.
I'd like to share one observation. If we change the browser zoom-out on browser (chrome) to somewhere near to 80% then above problem it not encountered. 

Any help or suggestion will be very useful for us.

**Comment by hit-en** [comment]
We are also facing the same issue in our application. when we fetch nodes and link via API and reload the graph then we are facing this issue.

**Comment by assafsun** [comment]
Is this still active?

**Comment by assafsun** [comment]
Closing this issue
