### ISSUE TITLE
Automatically zoom on a node in the graph

### ISSUE THREAD

**Issue by doorman02** [swimlane/ngx-graph#270]
**Is your feature request related to a problem? Please describe.**

It would be useful to set the location to a specific node automatically be specifying the id e.g.
Use case would when you have a large graph with many nodes and you want to find a specific node. Currently you have to pan around the graph till you find the node. If you could jump to a node it would be much quicker.

**Describe the solution you'd like**
A way to tell the graph to zoom in on a node by giving the id or label name of the node.

**Comment by marjan-georgiev** [comment]
You can use the `panToNode$` input for that. It pans the graph to center on the node ID emited from the observable.

In your component:
```
panToNodeObservable: Subject<string> = new Subject<string>();
...
this.panToNodeObservable.next(nodeId);
```

and pass it to the graph:

`[panToNode$]="panToNodeObservable"`

This will center the graph onto the node. You can also set the zoom manually by setting the `zoomLevel` input.

Here are all the inputs that the graph accepts:
https://swimlane.github.io/ngx-graph/#/#inputs
