### ISSUE TITLE
ngx-graph-org-tree Angular 4 support

### ISSUE THREAD

**Issue by jincybharill** [swimlane/ngx-graph#272]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Is this library provides support in angular 4 ? 
I'm not able to run the application after installing the ngx-graph library and getting errors while in Angular above version it is working fine.

Kindly respond for same.

**Comment by marjan-georgiev** [comment]
No. The last version that is compatible with angular 4 is ngx-graph v3. We do not actively support older versions of angular.
