### ISSUE TITLE
Get graph´s current location/zoom level to restore it in the exact same state.

### ISSUE THREAD

**Issue by doorman02** [swimlane/ngx-graph#273]
**Describe the bug**
Is there a way to get the current location and zoom level and setting these values to restore the graph in the exact same location and zoom as the user left it last time he was viewing the graph?

**Expected behavior**
Get the position and zoom level from the graph. Setting these values to the graph component should move the graph and set the zoom correspondingly.

**ngx-graph version**
6.2.0

**Comment by assafsun** [comment]
Interesting, I thought about it also.

This is not a bug but an enhancement that should be done by the custom layout.
ngx-graph provide you an API on how to arrange the nodes so you just need to save it and load it the next time ngx-graph is loaded.

Regrading to the zoom, you can monitor it with the output binding.

**Comment by doorman02** [comment]
Hi @assafsun  thanks for your reply. Is there a similar example how to achieve this with the API and the custom layout?

**Comment by marjan-georgiev** [comment]
These are available through these getters:

`zoomLevel`
`panOffsetX`
`panOffsetY`
