### ISSUE TITLE
Creating Graph with 10K nodes.

### ISSUE THREAD

**Issue by sujeet94** [swimlane/ngx-graph#274]
I am trying to create a graph with 10,000 nodes. the graph is not getting created and the tab is unresponsive. I verified my code which has minimal processing only fetching data and binding it to ngx-graph. (when testing with 1000 nodes it is taking about 6-7 sec approx).

**Comment by assafsun** [comment]
Wow! nice...

It also dependent on the amount of data and UI on each node.
I didn't tested ngx-graph with 10000 nodes, I know that for 500-1000, the loading time can be up to 4 seconds and then the performance is good.

Are you using a custom layout? or ngx-graph default?

**Comment by sujeet94** [comment]
I am using a custom svg layout.

**Comment by assafsun** [comment]
Sound like also limitation of our technology (working with SVG.

Nice idea to have 10000 nodes but I will need to close it as it sound like an extreme number of nodes.
