### ISSUE TITLE
When nodes and links Added dynamically, link and nodes cramped up at top left corner.

### ISSUE THREAD

**Issue by hit-en** [swimlane/ngx-graph#276]
**Describe the bug**
When we Add data(Links and Nodes) dynamically then graph not displayed properly.

**To Reproduce**
https://ngx-graph-demo-eeequk.stackblitz.io
1. Launch application using this link.
2. Click on 'Add Node' Button on top
3. Add around 20 to 25 nodes. sometime i'm able to reproduce issue with 17 to 20 nodes.
4. Check graph is cramped up on top left corner.

**Expected behavior**
Graph should be rendered properly.

**Screenshots**
Graph with issue.
![image](https://user-images.githubusercontent.com/59353854/71655873-01966d00-2d5f-11ea-9ab5-ac8549c9e65a.png)

Graph without issue.
![image](https://user-images.githubusercontent.com/59353854/71655803-afede280-2d5e-11ea-8e4e-140ea8af2629.png)

**Demo**
https://ngx-graph-demo-eeequk.stackblitz.io

**ngx-graph version**
6.1.0

**Additional context**
if we change browser zoom level to around 80% then graph rendered properly, if we reset zoom level to 100% again it cramped up.

**Comment by assafsun** [comment]
It worked fine when I tested it.
Please note the following:

1. The nodes that you see on the left side is a result of creating new nodes objects and passing them to ngx-graph rather from keeping them in a variable.
2. I didn't succeed to reproduce it but what you describe seems like a result on failure with the input data, I didn't checked the code but is there a possibility of adding a link without nodes or same node id?

**Comment by hit-en** [comment]
> It worked fine when I tested it.
> Please note the following:
> 
> 1. The nodes that you see on the left side is a result of creating new nodes objects and passing them to ngx-graph rather from keeping them in a variable.
> 2. I didn't succeed to reproduce it but what you describe seems like a result on failure with the input data, I didn't checked the code but is there a possibility of adding a link without nodes or same node id?

please try to add nodes in around 300 to 400 ms interval. it reproduced every times.
no i am not adding any links without nodes and not with the same node Id.

-> once graph is cramped up. if we change browser zoom level to around 80% from 100% then graph rendered perfectly and back to normal. and again if we change it to 100% zoom level, it again cramped up. this is my Observation.

**Comment by hit-en** [comment]
@assafsun, when graph cramped up. there is one warning message continuously printing on console.
> [Violation] 'requestAnimationFrame' handler took <N>ms

**Comment by hit-en** [comment]
i have debug the code and found that issue is in zoomToFit() method.
inside this method the breaking condition never occur at some point (when rendered graph width is more than page width).
> if (zoomLevel <= this.minZoomLevel || zoomLevel >= this.maxZoomLevel) 
> if (zoomLevel !== this.zoomLevel) 
so it recursively call zoomToFit() and update() and never comes out of it.

**Comment by assafsun** [comment]
following on your comment, can you please explain more?

Maybe we need to set the height to max and not reutrn?

Thanks.

**Comment by 1h6ydo** [comment]
I get a similar issue. At first it is cramped in one corner, then it slowly moves and then fits to the height, but not the width, producing a long, narrow graph.

I find that it does not happen if I set the height really big compared to the width. But if I set the width and height to the same number, or close to the same number, then it does this.

Difference for me is however I resize the window, it won't fix the graph. Only fixes if I increase the height. I also get no warning messages in console.

![image](https://user-images.githubusercontent.com/62040632/76370329-be72f000-62f3-11ea-8a67-a5ded22dc148.png)

![image](https://user-images.githubusercontent.com/62040632/76370306-aa2ef300-62f3-11ea-94d5-0ac4e657ad1b.png)

**Comment by assafsun** [comment]
I created a PR which fix the zoom issue which may help here.

In addition, does the animate input boolean is true or false?

My suggestion here is to wait and see if the next version with the zoom fix (mentioned in this thread) will help here. I want to believe that a new version will be release next week.

**Comment by 1h6ydo** [comment]
I did not specify the animate input so it would be whatever is default. 
Thanks. I will wait for the new version.

**Comment by assafsun** [comment]
Closing this issue as version 7.0.0 should fix it
