### ISSUE TITLE
Incompatible with rxjs 6 

### ISSUE THREAD

**Issue by suhailk4** [swimlane/ngx-graph#279]
Package "ngx-dag" has an incompatible peer dependency to "rxjs" (requires "^5.0.3", would install "6.5.4") the latest version of ngx-dag  is 0.0.2

**Comment by marjan-georgiev** [comment]
This project has been renamed to `ngx-graph` a while back. Please switch to `ngx-graph` and use the latest version. It is compatible with latest rxjs.
