### ISSUE TITLE
Disconnected independent graphs are rendered in random order

### ISSUE THREAD

**Issue by mthavaf** [swimlane/ngx-graph#281]
**Description**
Hi,

I am using ngx-graph to create a tree kind of structure as seen in the picture. 

![image](https://user-images.githubusercontent.com/16817872/72055500-f5775600-32f0-11ea-8647-8a729f97124d.png)

I have a tree in json and i am flattening it and giving it to the ngx-graph as it takes only array.
Currently it renders in random order. when i add one or more nodes to one of the tree again the order changes.

How can i make sure that the nodes will be in the order as it is in the tree?

**To Reproduce**
1. have a json in this format

{
            "nodeId": "1558431278693",
            "nodeName": "M-A: Andr",
            "webhookType": null,
            "button": null,
            "childNodes": [
                {
                    "nodeId": "1565006937949",
                    "nodeName": "TV How to",
                    "childNodes": [
                        {
                            "nodeId": "1577706465553",
                            "nodeName": "HT: TV How to",
                            "childNodes": []
                        }
                    ]
                },
                {
                    "nodeId": "1565324776409",
                    "nodeName": "TV Troubl",
                    "childNodes": [
                        {
                            "nodeId": "1577706269511",
                            "nodeName": "TV Troubl",
                        }
                    ],
                }
            ]
}
2. Flatten this and convert it to nodes and links array
3. it will be rendered in random order. if it doesn't please consider adding more nodes to the tree.
4. Please help

**Expected behavior**
nodes in the same order as it is in tree

**ngx-graph version**
    "@swimlane/ngx-graph": "6.2.0"

other dependencies version :
    "@ngrx/effects": "5.2.0",
    "@ngrx/router-store": "5.2.0",
    "@ngrx/store": "5.2.0",
    "@ngrx/store-devtools": "5.2.0",
    "@ngx-translate/core": "10.0.1",
    "@ngx-utils/cookies": "3.0.1",
    "@swimlane/ngx-charts": "7.3.0",
    "@swimlane/ngx-datatable": "11.3.2",
    "@swimlane/ngx-dnd": "3.2.0",

**Comment by mthavaf** [comment]
Hi Team,

can anyone help me with this issue?

**Comment by mthavaf** [comment]
Hi Team,

It would be really helpful if anyone can respond on this.

**Comment by assafsun** [comment]
Hi,

Does the nodes array that is passed to ngx-graph as inputs keeping the same order?

**Comment by mthavaf** [comment]
Hi,

I have used custom layout. Have copied dagre.ts from this repo and modified a bit.

**Comment by mthavaf** [comment]
The array passed is in correct order. 

In my case the first element is array is not the first element in the graph.

**Comment by mthavaf** [comment]
can anyone respond?

**Comment by assafsun** [comment]
Can you please try to set the order by the ID.
for example: nodes with ids: "a", "b", "c"...

**Comment by mthavaf** [comment]
ok i will try to do that. Thanks for the reply.

Can you clarify me on few things?
1. if i do not have "id" in each node what attribute of node will be picked as ID?
2. I am thinking to prefix node with their respective tree numbers. Do you think it will solve the problem?

**Comment by mthavaf** [comment]
can anyone clarify?

**Comment by mthavaf** [comment]
Hello,

Can anyone help me here?

**Comment by marjan-georgiev** [comment]
If you're using the dagre layout, head over to https://github.com/dagrejs/dagre to find out more about it and possibly open an issue with them.

**Comment by Karunakarankavi** [comment]
> **Description** Hi,
> 
> I am using ngx-graph to create a tree kind of structure as seen in the picture.
> 
> ![image](https://user-images.githubusercontent.com/16817872/72055500-f5775600-32f0-11ea-8647-8a729f97124d.png)
> 
> I have a tree in json and i am flattening it and giving it to the ngx-graph as it takes only array. Currently it renders in random order. when i add one or more nodes to one of the tree again the order changes.
> 
> How can i make sure that the nodes will be in the order as it is in the tree?
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. have a json in this format
> 
> { "nodeId": "1558431278693", "nodeName": "M-A: Andr", "webhookType": null, "button": null, "childNodes": [ { "nodeId": "1565006937949", "nodeName": "TV How to", "childNodes": [ { "nodeId": "1577706465553", "nodeName": "HT: TV How to", "childNodes": [] } ] }, { "nodeId": "1565324776409", "nodeName": "TV Troubl", "childNodes": [ { "nodeId": "1577706269511", "nodeName": "TV Troubl", } ], } ] } 2. Flatten this and convert it to nodes and links array 3. it will be rendered in random order. if it doesn't please consider adding more nodes to the tree. 4. Please help
> 
> **Expected behavior** nodes in the same order as it is in tree
> 
> **ngx-graph version** "@swimlane/ngx-graph": "6.2.0"
> 
> other dependencies version : "@ngrx/effects": "5.2.0", "@ngrx/router-store": "5.2.0", "@ngrx/store": "5.2.0", "@ngrx/store-devtools": "5.2.0", "@ngx-translate/core": "10.0.1", "@ngx-utils/cookies": "3.0.1", "@swimlane/ngx-charts": "7.3.0", "@swimlane/ngx-datatable": "11.3.2", "@swimlane/ngx-dnd": "3.2.0",

Can you share the whole code so that it will useful to detect
