### ISSUE TITLE
Animations not working on ngOnChanges

### ISSUE THREAD

**Issue by eafiontzi** [swimlane/ngx-graph#283]
We have developed a web component in Angular 8 (using Angular Elements) that makes use of ngx-graph, more specifically the organization Tree example (https://github.com/swimlane/ngx-graph/tree/master/src/docs/demos/components/ngx-graph-org-tree). 

The web component receives as input a json string (produced in the parent application that the component is used in) with all data needed for the graph, which can be accessed only in OnChanges lifecycle-hook. The graph is created just fine but the animations (zoom in, zoom out, moving etc) are not "live". What I mean by that is that each movement is produced after a mouse click (maybe something triggers them that way?). So I scroll to zoom and only when I click the mouse does the zooming effect appears in the application.

The issue appears to be connected with the specific hook, because I have tried using an example json input on the OnInit lifecycle-hook and the graph was fine, but when I moved the same code in the OnChanges hook it stopped behaving properly.

Have you encountered a similar behavior elsewhere? 

**Expected behavior**
The zooming and movement of the graph should work on the spot.

**Demo**
Due to the nature of the issue and the proprietary use of the application I cannot provide an online demo.

**ngx-graph version**
"@swimlane/ngx-graph": "^6.2.0"

**Additional context**
Angular version 8 in the web component that uses ngx-graph

**Comment by assafsun** [comment]
Sound very interesting, I will be happy to see more your use with ngx-graph and angular elements. 
Can you please share with me some code that will be able to debug?

**Comment by eafiontzi** [comment]
Thanks a lot for your quick response, due to time limitations I temporarily disabled all movements and zooming, I will let you know when I can provide test code.

**Comment by eafiontzi** [comment]
I was able to solve this issue after all, it was not related to the graph but an Angular issue. After reading those two articles:
-  https://medium.com/@isaacplmann/ngonchanges-only-runs-when-the-input-change-comes-from-a-template-binding-like-component-8797b759ba0b
- https://stackoverflow.com/questions/46076986/ngonchanges-working-only-when-there-is-an-action

I used the approach with the zone, more specifically I included the method capturing the data for the graph in the zone run like this:

`this.zone.run(() => this.getGraph(this.graphData));`
