### ISSUE TITLE
Cannot use ngx-graph-org-tree example without predefined width and height

### ISSUE THREAD

**Issue by eafiontzi** [swimlane/ngx-graph#284]
**Describe the bug**
I am using the organization tree example but do not know the exact height of the node, so I try using the node.dimension.height. Instead of calculating the correct dimensions, the graph gets width and height of 30 by default. 

**To Reproduce**
In the https://github.com/swimlane/ngx-graph/blob/master/src/docs/demos/components/ngx-graph-org-tree/ngx-graph-org-tree.component.html file remove [nodeWidth]=150
[nodeHeight]=100 (lines 7,8) and replace width="150" height="100" with [attr.width]="node.dimension.width" [attr.height]="node.dimension.height" in lines 20 and 21.

**Expected behavior**
The width and height get calculated based on the content of the node

**Demo**
https://codesandbox.io/s/silly-bose-n4dst?fontsize=14&hidenavigation=1&theme=dark

**ngx-graph version**
"@swimlane/ngx-graph": "^6.2.0"

**Additional context**
Angular 8

**Comment by marjan-georgiev** [comment]
If you don't define the node's dimensions, they default to 30 on the first render, and after that the graph measures the actual width and height of the rendered node, and feeds that back into the layout.

Since you are using the initial dimensions to set the foreignObject width and height properties, they get set to 30 and stay there.

**Comment by eafiontzi** [comment]
Thank you very much for your answer. 

I was expecting the graph to feed back the correctly calculated width and height, but does not seem to do so in the sandbox. 

Could you please explain a little more where in the code do I use the initial dimensions (30) to set the foreignObject width and height properties and which is the correct approach for dimensions to get updated in the layout after calculated?

**Comment by assafsun** [comment]
You can set the size for each node in the graph level (all nodes will be similar) or set a different size for every node.

In case you are using a foreign object, you can set it also in the HTML (I think it's required for foreign objects).

look at  https://github.com/swimlane/ngx-graph/blob/184ce5aea8accadd6b72756a8d470e9da1d2d652/src/docs/demos/components/ngx-graph-org-tree/ngx-graph-org-tree.component.html#L22
