### ISSUE TITLE
fontawesome icons do not show on custom template

### ISSUE THREAD

**Issue by eafiontzi** [swimlane/ngx-graph#285]
When using custom template the fontawesome icons do not show, while when using the ngx-graph-org-tree example I can see them. The only piece of code that changes is the nodes section in the app.component.html file.

**Demo**
With custom template and no appearance of fontawesome icons: https://codesandbox.io/s/patient-pine-mkq2j?fontsize=14&hidenavigation=1&theme=dark
With ngx-graph-org-tree example where we can see fontawesome icons: https://codesandbox.io/s/flamboyant-browser-0ml7t?fontsize=14&hidenavigation=1&theme=dark

**ngx-graph version**
"@swimlane/ngx-graph": "^6.2.0"

**Additional context**
Angular 8

**Comment by marjan-georgiev** [comment]
`fa-icon` is an HTML element, not an SVG. To use those in the graph templates, you need to wrap them in a `foreignObject` element, like in the org tree demo.

```
<svg:foreignObject width="150" height="100">
        <xhtml:div
          class="cardContainer"
          xmlns="http://www.w3.org/1999/xhtml"
          [ngStyle]="getStyles(node)"
        >
          <label class="name">{{node.label}}</label>
          <label>{{node.data.role}}</label>
          <label>{{node.data.office}}</label>
          <fa-icon [icon]="faCoffee"></fa-icon>
        </xhtml:div>
      </svg:foreignObject>
```

**Comment by marjan-georgiev** [comment]
See https://dev.w3.org/SVG/profiles/1.2T/publish/diff/extend.html for more info.

**Comment by eafiontzi** [comment]
Thank you for the explanation, I already got it working with foreignObject, the issue here is that foreignObject does not get recognized from Internet Explorer. I am pressuring towards dropping support for IE, fingers crossed...

**Comment by developerzzz** [comment]
can i do something similler to bar chart
