### ISSUE TITLE
rectangular height miscalculated for IE11

### ISSUE THREAD

**Issue by eafiontzi** [swimlane/ngx-graph#286]
**Describe the bug**
On internet explorer 11, the rectangular that holds the whole graph gets wrongly calculated height and weight parameters, which results in an huge vertical and horizontal scrolling. I have tried initializing the width and height by css but it gets overridden, I even tried changing the height and width afterwards with JavaScript but no change. If no correct calculation can be done, Is it possible to initialize those variables somewhere? Thank you very much in advance

**Expected behavior**
Calculate correctly height and width

**Screenshots**
![bugIE11](https://user-images.githubusercontent.com/14819444/72600399-34726080-391c-11ea-8535-71aa83956d10.PNG)

**ngx-graph version**
"@swimlane/ngx-graph": "^6.2.0"

**Additional context**
Angular 8

**Comment by assafsun** [comment]
I think in general, IE 11 has  some problems with ngx-graph.
Giving the fact that Microsoft browsers today are Edge and the new Edge, I think we can remove our support for IE 11, otherwise, we will not finish working only on that.

@marjan-georgiev for any comment

Closing it as Won't fix

**Comment by eafiontzi** [comment]
Thank you for your answer, I finally convinced them to drop support for IE as well. :)
