### ISSUE TITLE
Need help in layout of graph.

### ISSUE THREAD

**Issue by ChitrajanDhiman** [swimlane/ngx-graph#287]
I am trying to use ngx-graph in my project to draw a hierarchical graph. I have issue with links that connecting two nodes. I have tried all curve types, but not getting expected result.

Here is some code snippets:

**HTML**
<ngx-graph
      [links]="links"
      [nodes]="nodes"
      [layoutSettings]="layoutSettings"
      [curve]="curve"
      [draggingEnabled]="false"
      [panningEnabled]="true"
      [enableZoom]="false"
      [autoZoom]="true"
      [autoCenter]="false"
 >

<ng-template #nodeTemplate let-node>
          <svg:g class="node">
            <svg:rect [attr.width]="100" [attr.height]="50" fill ="#fff" stroke-width ="1" stroke = "#000" />
            <svg:text alignment-baseline="central"  [attr.x]="10" [attr.y]="node.dimension.height / 2">{{node.label}}</svg:text>
          </svg:g>
</ng-template>
</ngx-graph>

**TS**
curve: any = shape.curveLinear;

layoutSettings = {
    orientation: 'TB'
};

nodes: Node[] = [
  {
    id: 'first',
    label: 'Parent'
  }, {
    id: 'c1',
    label: 'Child 1'
  }, {
    id: 'c2',
    label: 'Child 2'
  }, {
    id: 'c3',
    label: 'Child 3'
  }
];

links: Edge[] = [
  {
    id: 'a',
    source: 'first',
    target: 'c1',
    label: 'is parent of'
  }, {
    id: 'b',
    source: 'first',
    target: 'c2',
    label: 'custom label'
  }, {
    id: 'c',
    source: 'first',
    target: 'c3',
    label: 'custom label'
  }
];

Output that I am getting is:
![output](https://user-images.githubusercontent.com/28748282/73173960-9c9b2080-412c-11ea-81d7-1e9089226e01.jpg)

Expected output is :
![expected](https://user-images.githubusercontent.com/28748282/73174010-b9375880-412c-11ea-8b6f-e57a41250fff.jpg)

Please help me in this issue.

**Comment by marjan-georgiev** [comment]
This doesn't look like a bug. You can see how to change curve types in the demo stackblitz here: https://stackblitz.com/edit/ngx-graph-demo

**Comment by ChitrajanDhiman** [comment]
@marjan-georgiev  I already tried all types of curve but not able to get desired result.

**Comment by sagarranarobomq** [comment]
@ChitrajanDhiman I also have a similar requirement do you have any lead?
