### ISSUE TITLE
ngx-graph with angular 9

### ISSUE THREAD

**Issue by danshif** [swimlane/ngx-graph#290]
**Describe the bug**
On angular v 9, when put svg in ng template' its dont show nothing on pape

**Comment by aki-ks** [comment]
I'm facing the same issue. Even the [example](https://swimlane.github.io/ngx-graph/#custom-templates#custom-templates) is no longer work.

**Comment by assafsun** [comment]
Can you please try with the version 7.0.0-rc.1? In case you used the latest official version 6.2.0
I think this is a version for testing Angular 9

**Comment by TheL0w3R** [comment]
> Can you please try with the version 7.0.0-rc.1? In case you used the latest official version 6.2.0
> I think this is a version for testing Angular 9

Can confirm that 7.0.0-rc.1 works completely fine for me.
Using Angular 9.0.4

**Comment by danshif** [comment]
Yes is working, Tanks!

בתאריך יום ד׳, 4 במרץ 2020, 1:03, מאת TheL0w3R ‏<notifications@github.com>:

**Comment by assafsun** [comment]
Thanks.
Closing this issue.

**Comment by GlitchEclipse** [comment]
I upgraded the version to 7.0.0-rc.1 and the ng-template just using the example code on the site will not load.this is off a fresh download and pasting the examples line for line. Angular version 9.1. Is this still a bug or should it be working?
