### ISSUE TITLE
Angular 9 support

### ISSUE THREAD

**Issue by manojdemel12d** [swimlane/ngx-graph#293]
I have been using the current module in my Angular 8 App so far without an issue. After upgrading the App to Angular v9 the graph stopped working.

The SVG panel seems to load but the nodes are empty.

**Comment by lisacopeland** [comment]
I had that problem until I upgraded to ngx-graph version 7.0.0-rc.1

**Comment by manojdemel12d** [comment]
> I had that problem until I upgraded to ngx-graph version 7.0.0-rc.1

Thank you. It worked

**Comment by eafiontzi** [comment]
Hello I have upgraded Angular to v9 (nodes were empty) and also ngx-graph to 7.0.0-rc.1 but all css on the graph nodes are lost, does this have to do with the graph update? Thank you in advance.

**Comment by lisacopeland** [comment]
Can you post a stack blitz on the gitter? I’d be happy to take a look

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by eafiontzi** [comment]
Thank you very much for that, for the time being I have downgraded because I have some deadlines to catch but I will take you up on your offer when I find time.
