### ISSUE TITLE
Support for angular ionic app

### ISSUE THREAD

**Issue by rohitbhoite** [swimlane/ngx-graph#294]
**Is your feature request related to a problem? Please describe.**
zoom functionality is not working when the ngx graph is used in angular ionic app

**Describe the solution you'd like**
Zoom functionality should work as it is working in browser

**Describe alternatives you've considered**

**Additional context**

**Comment by assafsun** [comment]
what's the limitation that you saw? please share more information

**Comment by rohitbhoite** [comment]
In ionic framework zoom is disabled by default. May be with Zoom in zoom out buttons this can be achieved

**Comment by assafsun** [comment]
The default value of enableZoom input is true. verifying that you didn't change it right?

**Comment by assafsun** [comment]
Closing this one as there was no reply.
