### ISSUE TITLE
Cluster cramped up at top left corner

### ISSUE THREAD

**Issue by havinhphu188** [swimlane/ngx-graph#296]
**Describe the bug**
Cluster cramped up at the top left corner

**Expected behavior**
Should have cluster node a1, a2

**Screenshots**

**Demo**
https://stackblitz.com/edit/ngx-graph-cluster-bug-demo-xwbf5k

**ngx-graph version**
6.0.1
**Additional context**

**Comment by assafsun** [comment]
Does the link works for you? I could not open it

**Comment by havinhphu188** [comment]
@assafsun Sorry, my bad. I have updated the link. I also find out that, this happen because I have used the layout type to be "dagre" instead of "dagreCluster". I have changed that and things work fine. So I will close this issue. Thanks for your support

layout: String | Layout = 'dagre'; ---> layout: String | Layout = 'dagreCluster';
