### ISSUE TITLE
DagreNode is undefined

### ISSUE THREAD

**Issue by YannisNaidja** [swimlane/ngx-graph#299]
Hi, i'm stuck with the error "DagreNode is undefined" with trying to draw graph dynamicly from other datas. I made sure to construct the node and links arrays with string data and I still get this error. But when i hard code the content of nodes and links array it is working, might just be a type issue but i don't see how to work it around.

Thanks for help in advance.

**Comment by lisacopeland** [comment]
Can you post some code in the Gitter? I’d be happy to look

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by marjan-georgiev** [comment]
Closing this. Please reopen with more details and a reproducible demo if you still have the issue.
