### ISSUE TITLE
Remove flicker caused by using templates

### ISSUE THREAD

**Issue by marjan-georgiev** [swimlane/ngx-graph#3]
Becase we use templates for nodes and links, the elements get redrawn on every update, which causes flicker in the chart. Need to investigate and find a way around it.

**Comment by wylfishwear** [comment]
any updates on this?

**Comment by assafsun** [comment]
@marjan-georgiev , Isn't the link animation solved it for the links?

**Comment by assafsun** [comment]
@marjan-georgiev This seems related to the issue that I saw with the data link.

The links are redrawn but not in the demo app but in my use.
I suspect that it's a result of using the redrawAnimation call with zone which result in multiple digest calls.

I'm closing this issue as it solved inside the demo app and will be solved for the data link.
New problems with it will be handled in a new issue.
