### ISSUE TITLE
Nodes and Clusters

### ISSUE THREAD

**Issue by EliMilya** [swimlane/ngx-graph#300]
Hi,
Can you please help me? Does the feature exist, maybe?

What can I do if I need a specific position of my clusters with nodes in them, or only nodes?

For example :
- I need to set position of "First Group" nodes in the left top corner of the window and the "Second Group" nodes I want to put in the right top corner of the window. The amount of nodes can changes accordingly to data that I get from backend ( It can be 10 nodes in each group or 50 in each), and I want to manage their positioning. 

So what do I have to write in code, what do you recommend ?

I tried to set in our object ::
{
      id: 'e',
      label: 'E',
      data: {
        x: 510,
        y: 50
      }
and then to get this [attr.x]=node.data.x, and [attr.y]=node.data.y in <ng-template #nodeTemplate let-node>, and with this approach nodes move but links stay at the same place. But all the way I think that this is not way that we must to use your library.

So please help me))))

**Comment by EliMilya** [comment]
Can anybody support?

**Comment by marjan-georgiev** [comment]
I'm not sure I understand what you're trying to achieve. A demo or a sketch might help.

**Comment by assafsun** [comment]
Closing this as there was not comment to Marjan response. Thanks

**Comment by arsh437git** [comment]
Hi , I want to reopen this as I have a similar issue 
![88e5c9ef-b535-441e-96c4-be21c1871564](https://user-images.githubusercontent.com/37994048/88479793-602b6e80-cf6f-11ea-9d08-f4f0d98ba77b.PNG)


I should have two groups with thier respective nodes.

**Comment by FengxiangZhao** [comment]
I really like this idea and it is exactly what I looking for.

**Comment by ilannn** [comment]
The bug/request here is that passing `position` and `dimension` to nodes & clusters has no effect.
See stackblitz example: https://stackblitz.com/edit/ngx-graph-demo-cqnamk?file=src/app/data.ts
![image](https://user-images.githubusercontent.com/21119949/107004656-462cdd00-6797-11eb-830a-0500e970a6e1.png)
![image](https://user-images.githubusercontent.com/21119949/107004684-4f1dae80-6797-11eb-8545-173c8bc6d708.png)
