### ISSUE TITLE
Possible missing edge

### ISSUE THREAD

**Issue by lisacopeland** [swimlane/ngx-graph#301]
**Describe the bug**
The graph in my sample app is missing an edge between two nodes

**To Reproduce**
run the stackblitz - there should be a line between the node labeled "start" and the one labeled "identifyservers", you will see that there is not one

**Expected behavior**
There should be a line between those two nodes and you will see that there is not. 

**Demo**
https://stackblitz.com/github/lisacopeland/ngx-graph-app

**ngx-graph version**
"^7.0.0-rc.1"

**Additional context**

**Comment by assafsun** [comment]
The link appears, please drag the node in order to see it.

![image](https://user-images.githubusercontent.com/33118325/77886152-0345d300-7271-11ea-84b6-1f542fe06f10.png)

**Comment by lisacopeland** [comment]
I was playing around the this and I saw that the line appears when you move the node around - why doesn’t the line appear initially? Is there some workaround I could try?

Sent from my iPhone

On Mar 30, 2020, at 12:27 AM, Assaf Shemesh <notifications@github.com> wrote:

﻿

The link appears, please drag the node in order to see it.

[image]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F33118325%2F77886152-0345d300-7271-11ea-84b6-1f542fe06f10.png&data=02%7C01%7C%7C652b8d4372c84772c13708d7d47bd45f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637211500612089299&sdata=ljkHAvho0zDE7rIeuwWzdHU6xrwMgZYEzamFI%2BoazWU%3D&reserved=0>

**Comment by assafsun** [comment]
The problem with your code is that there is no sync between the sizes of the passed elements into ngx-graph and the declare sizes for the layout.
As a result, dagre sets small size nodes where you override it and create bigger nodes.
Please add the following to your graph object
    [nodeWidth]="150"
    [nodeHeight]="55"

![image](https://user-images.githubusercontent.com/33118325/77886591-d219d280-7271-11ea-890f-05731eb554ff.png)

**Comment by assafsun** [comment]
@lisacopeland Please try to play with it and adjust your graph, if there is any additional problem, please open a new issue.

**Comment by lisacopeland** [comment]
Thank you so much! Adding nodeWidth and nodeHeight solved the problem! I am very much enjoying your product!
