### ISSUE TITLE
Labels do not show - incompatible with Angular 9

### ISSUE THREAD

**Issue by Gilwyad** [swimlane/ngx-graph#302]
Labels are not visible for lines nor nodes. Just check your website https://swimlane.github.io/ngx-graph/#/#quick-start , even tho labels are defined on links and nodes, it is not shown on the graph! I tried in an Angular 9 project and got the same behavior.

**Comment by lisacopeland** [comment]
labels are showing for me? Look at the demo app - https://stackblitz.com/edit/ngx-graph-demo
[https://c.staticblitz.com/assets/icon-664493542621427cc8adae5e8f50d632f87aaa6ea1ce5b01e9a3d05b57940a9f.png]<https://stackblitz.com/edit/ngx-graph-demo>
ngx-graph-demo - StackBlitz<https://stackblitz.com/edit/ngx-graph-demo>
Interactive demo for NGX-Graph
stackblitz.com

---------------------------------------------
For more information about boarding and training, please visit my website, www.sansebastianec.com<http://www.sansebastianec.com>


________________________________

**Comment by Gilwyad** [comment]
I see the labels on the app you linked, however I'm talking about the example on the website quick start section:

![no-labels](https://user-images.githubusercontent.com/1919041/77948664-0ae39700-72c6-11ea-862e-ee1fbcd3d95f.png)

It has labels defined but nothing shows up. It seems I'm missing steps to have the labels show up. I'm having trouble finding this in the documentation. The quickstart makes it seem all that is needed is the data in the picture above, but maybe this is wrong? Do I have to use [custom templates](https://swimlane.github.io/ngx-graph/#custom-templates#custom-templates) ?

**Comment by lisacopeland** [comment]
I think you do need custom templates for this
---------------------------------------------
For more information about boarding and training, please visit my website, www.sansebastianec.com<http://www.sansebastianec.com>


________________________________

**Comment by Gilwyad** [comment]
It still doesn't work. I think that the problem is that I'm using Angular 9 and ngx-graph only works partially.

```
npm WARN @swimlane/ngx-charts@12.1.0 requires a peer of @angular/animations@7.x || 8.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-charts@12.1.0 requires a peer of @angular/cdk@7.x || 8.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-charts@12.1.0 requires a peer of @angular/core@7.x || 8.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-charts@12.1.0 requires a peer of @angular/common@7.x || 8.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-charts@12.1.0 requires a peer of @angular/forms@7.x || 8.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-charts@12.1.0 requires a peer of @angular/platform-browser@7.x || 8.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-charts@12.1.0 requires a peer of @angular/platform-browser-dynamic@7.x || 8.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-graph@6.2.0 requires a peer of @angular/animations@6.x || 7.x || 8.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-graph@6.2.0 requires a peer of @angular/common@6.x || 7.x || 8.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-graph@6.2.0 requires a peer of @angular/core@6.x || 7.x || 8.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-graph@6.2.0 requires a peer of @angular/cdk@6.x || 7.x || 8.x but none is installed. You must install peer dependencies yourself.

```

I tried upgading your demo project to Angular 9 and got this error:

    Package "@swimlane/ngx-graph" has an incompatible peer dependency to "@angular/cdk" (requires "6.x || 7.x || 8.x", would install "9.2.0").

So when are you planning to release a version compatible with Angular 9?

**Comment by assafsun** [comment]
You can use today version of 7.0.0-rc.1 to test angular 9.

Official ngx-graph version will be release soon.

**Comment by Gilwyad** [comment]
Thanks, that's great news! I tried it and now I see the arrows and node labels, but still no line labels.

**Comment by lisacopeland** [comment]
If you send a stack blitz Or repo I’m happy to help

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Gilwyad** [comment]
So here's my test: 

https://github.com/Gilwyad/ngx-graph-with-angular9

I created a new Angular9 app, installed

npm install @swimlane/ngx-graph@7.0.0-rc.1 --save
npm install @angular/cdk --save

and added the example on https://github.com/swimlane/ngx-graph#custom-templates (and removed your custom ngx-tooltip). Same results, labels in nodes visible, but not on the lines.

**Comment by lisacopeland** [comment]
Gilwyad - please see my example app which has labels - http://stackblitz.com/github/lisacopeland/lisacopeland/ngx-graph-app

**Comment by Sandeep321** [comment]
@lisacopeland App on "stackblitz.com/github/lisacopeland/ngx-graph-app" doesnt even work. All I see is a button "Click here to change graph" and on click of it, I see below error in the console.

MygraphComponent.html:1 ERROR TypeError: Cannot read property '0' of undefined
    at MygraphComponent.onChangeGraph (mygraph.component.ts:49)
    at Object.eval [as handleEvent] (MygraphComponent.html:1)
    at handleEvent (view.ts:138)
    at callWithDebugContext (services.ts:629)
    at Object.debugHandleEvent [as handleEvent] (services.ts:376)
    at dispatchEvent (util.ts:135)
    at eval (element.ts:200)
    at HTMLButtonElement.eval (platform-browser.umd.js:sourcemap:758)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (ng_zone.ts:288)

**Comment by DavidDNA** [comment]
For those struggling with this issue, you need to define a template for the links:

`<ng-template #linkTemplate let-link>
          <svg:g class="edge">
            <svg:path class="line" stroke-width="2" marker-end="url(#arrow)">
            </svg:path>
            <svg:text class="edge-label" text-anchor="middle">
              <textPath class="text-path" [attr.href]="'#' + link.id" [style.dominant-baseline]="link.dominantBaseline"
                        startOffset="50%">
                {{link.label}}
              </textPath>
            </svg:text>
          </svg:g>
        </ng-template>`

Hope this helps someone!

**Comment by Vny29** [comment]
> For those struggling with this issue, you need to define a template for the links:
> 
> ```
> <ng-template` #linkTemplate let-link>
>           <svg:g class="edge">
>             <svg:path class="line" stroke-width="2" marker-end="url(#arrow)">
>             </svg:path>
>             <svg:text class="edge-label" text-anchor="middle">
>               <textPath class="text-path" [attr.href]="'#' + link.id" [style.dominant-baseline]="link.dominantBaseline"
>                         startOffset="50%">
>                 {{link.label}}
>               </textPath>
>             </svg:text>
>           </svg:g>
>         </ng-template>
> ```
> 
> Hope this helps someone!
By adding this code i am getting can't bind ngtemplateoutlet since it isnt known propetry of ng template

**Comment by Vny29** [comment]
Can't bind to ngtempalteoutletcontext since it isnt a known properry of ngtemplate

**Comment by lisacopeland** [comment]
If you put a repo up I can look at it if you still need help

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
