### ISSUE TITLE
NullInjectorError: No provider for LayoutService!

### ISSUE THREAD

**Issue by uttahb** [swimlane/ngx-graph#305]
**Describe the bug**
Getting this error
`NullInjectorError: No provider for LayoutService!`
**To Reproduce**
1. create a new angular project
2. install ngx-graph^7.0.0
3. import NgxGraphModule
4. Add <ngx-graph> component to your component
5. Open the browser
**Expected behavior**
Show the graph according to the input data
**Screenshots**

**ngx-graph version**
7.0.0

**angular version**
9.0.2

**Comment by assafsun** [comment]
Did you defined an input layout?

**Comment by assafsun** [comment]
Closing this as no reply from my reply on April 9.
