### ISSUE TITLE
Downloading generated svg image for offline viewing

### ISSUE THREAD

**Issue by hridayeshgupta-iticks** [swimlane/ngx-graph#307]
**Is your feature request related to a problem? Please describe.**
I am trying to download the generated svg file to send it on email. Currently it doesn't make sense to send link to webpage, till the project is complete. It would be better if I can download and send generate svg/png file.

**Describe the solution you'd like**
An option to save image.

**Describe alternatives you've considered**
I have copied generated svg from chrome to a svg file which does not seem to work.

**Additional context**
Please let me know if there is a workaround of this feature is already available. I could not find it in docs and anywhere else.

**Comment by marjan-georgiev** [comment]
This is not a feature that comes with the library, but it is possible to do using something like svgsaver: https://github.com/Hypercubed/svgsaver

We're already using svgsaver alongside ngx-graph, and it works pretty well.
