### ISSUE TITLE
PanningAxis type mismatch

### ISSUE THREAD

**Issue by linuxninja39** [swimlane/ngx-graph#308]
**Describe the bug**
Documentation indicates that the 'panningAxis' attribute is of type string. However, when setting it to a string, you get a type error. Examining the code indicates panningAxis is a 'PanningAxis' enum, which you've defined in lib/enum however this has not been exported, so you can't resolve the type.

**To Reproduce**
1. Add [panningAxis] attribute to a <ngx-graph> tag, and set to a string

**Expected behavior**
Should be able to set [panningAxis] to a PanningAxis enum

**Demo**
Provide an online demo (stackblitz, codesandbox, or similar) where the issue can be reproduced 

**ngx-graph version**
Specify the version of ngx-graph where this bug is present

**Comment by marjan-georgiev** [comment]
This is fixed in master, and will be released with v7.1. Thanks for reporting it!
