### ISSUE TITLE
Path / Node mismatch on bigger Nodes, Advisory

### ISSUE THREAD

**Issue by lkaupp** [swimlane/ngx-graph#309]
**Describe the bug**
I think its not directly a bug, but i have the following problem on bigger Nodes:

![image](https://user-images.githubusercontent.com/26430608/79963904-41a66a80-848a-11ea-8f09-9f141a36d84c.png)

My Nodes are smaller because of the nested foreignObject to display an HTML-Overlay over each node. In return the Path point exactly towards the edges of the nodes. Is it possible to anchor the paths towards the node center instead at the edges?

**To Reproduce**
1. Create a node with fixed size
2. Create a nested object with smaller size.
3. Link two nodes together
4. Move nodes around

**ngx-graph version**
Current Version

**Comment by assafsun** [comment]
The foreignobject and the node should be on the same size. why do you want that the nested object will be smaller?

**Comment by lkaupp** [comment]
Because the overlay is should be around the node on hover and that is only possible if the foreignObj is bigger than the node itself...

**Comment by assafsun** [comment]
@lkaupp , is this issue still relevant? I'm still don't understand which overlay should be bigger from the node?

**Comment by lkaupp** [comment]
its still an issue, i just did a hacky solution (stackoverflow post), but this dirty fix is not diserable. Well why i prefer a greater foreign obj is because that enables to print htm / css fancy objects at a side of the svg obj. CSS3 is capable of fancy things while svg has strengths in an other direction. I want to combine the strenghts of both worlds to accomplish my goal. On hover a CSS menue popup at the side of the svg node obj. For that reason, the foreign object has to be greater than the svg node obj. If there is an alternative, let me know. :)

**Comment by lkaupp** [comment]
well i use your great lib to automatically interconnect nodes. And im in need to display a menue at the side of that svg object and this can only be achived using a foreignObj and only if the fObj is greater than the actual node it is possible to see the generated html. The obj could be at the same size but than the menue would be only visible inside the node (hiding information of the node obj)

**Comment by assafsun** [comment]
Why not the menu and the inner node will be HTML? without mixing HTML and SVG, that way you will not need to align any wrappers sizes.

In addition, this issue is related to your node template input which the library don't handle, adding foreign object has advantages and disadvantages and it require design when adding it inside the node.
I don't think there is an action item for the library beside redesign your node template.
From the layout perspective, you created a nodes at a certain size and it follow it.

**Comment by lisacopeland** [comment]
Lukas - I am using angular material to display a menu when the user clicks (or you could make it happen on hover) on a node and it is quite easy - I have mat-button [matMenuTriggerFor]="clickMenu" in the svg:g element and the menu HTML below it - you can even use attributes on the menu to place it where you want it

**Comment by assafsun** [comment]
@lisacopeland, it's very interesting the menu button opening because from my experience with SVG and foreign object, the menu is not opened at the right location because of the reverse SVG grid.
If it works for you, I will be happy to get more information, does materiel tooltips also works?
Thanks.

**Comment by lisacopeland** [comment]
Yes I have material tool tips as well - let me share a stackblitz

**Comment by lisacopeland** [comment]
I don't know why but the stackblitz isn't working - this is the repo where my sample is - https://github.com/lisacopeland/ngx-graph-app - this may not solve your problem - the menu appears just below the node and I wasn't able to use the mat-menu attributes to change the position of the menus

**Comment by assafsun** [comment]
Ok, I will review it.

Thanks for the fast reply 🙂
