### ISSUE TITLE
Link from node to itself disappears if graph node is dragged

### ISSUE THREAD

**Issue by jurvi** [swimlane/ngx-graph#310]
**Describe the bug**
When a node has link to itself, link shows up fine at first. If node gets dragged, it breaks and more or less seems like gets stuck inside the node. Seems to work normally with panning though.

**To Reproduce**
1. Create two nodes
2. Create one link between those nodes, and another one with source and target being same node
3. Drag the node that has link to itself
4. See how the link arrow disappears

**Expected behavior**
Link stays properly visible after dragging as well.

**Demo**
https://stackblitz.com/edit/ngx-graph-demo-gacphd

**ngx-graph version**
7.0.1

**Additional context**
Also the link arrows connected to the moved node seem to lose curve when this happens. Could be related?

**Comment by assafsun** [comment]
Which layout are you using? You need to create a custom layout and update the updateEdge function. You can take the following file for testing. https://github.com/swimlane/ngx-graph/blob/e14c1c532bd2819f350382ac1826fb53dd23fd5f/src/docs/demos/components/ngx-graph-org-tree/customDagreNodesOnly.ts

**Comment by jurvi** [comment]
@assafsun Okay thanks, I've tried the custom layout option a bit now. I am able to get the update working somewhat OK, but still not as well as it looks in the original render. Can you point me to the place where the initial renders edge points are calculated?

**Comment by assafsun** [comment]
Sorry for the late response, please look at the following function which set the links point during drag
https://github.com/swimlane/ngx-graph/blob/e14c1c532bd2819f350382ac1826fb53dd23fd5f/src/docs/demos/components/ngx-graph-org-tree/customDagreNodesOnly.ts#L83

Closing this issue for now, if needed, let's reopen it.

Thanks.
