### ISSUE TITLE
Stretch the graph over the width of the page

### ISSUE THREAD

**Issue by Ionaru** [swimlane/ngx-graph#311]
**Is your feature request related to a problem? Please describe.**
When displaying a tall graph using the dagre layout with many nodes and few steps, the labels on the links between nodes overlap and labels on them become unreadable.

**Describe the solution you'd like**
The ability to stretch the graph over the width of the page.

**Describe alternatives you've considered**
I could use `Orientation.TOP_TO_BOTTOM` but this would make the link labels difficult to read as the are mostly vertical. It would also not fit on the page well because the labels in the nodes are quite long. Maybe there are some things I missed, do you have any tips to make this readable?

**Additional context**
Current issue:
![image](https://user-images.githubusercontent.com/3472373/80253844-58abaf00-867a-11ea-94e3-c7d9acfcc0f3.png)

Alternative solution:
![image](https://user-images.githubusercontent.com/3472373/80255415-22236380-867d-11ea-8db7-24d2c23bd5ab.png)

**Comment by assafsun** [comment]
Maybe play with dagre settings and extend the width of the graph which may help in the label width?

https://github.com/swimlane/ngx-graph/blob/e14c1c532bd2819f350382ac1826fb53dd23fd5f/projects/swimlane/ngx-graph/src/lib/graph/layouts/dagre.ts#L36

**Comment by cedricve** [comment]
Interesting. When removing the view attribute, the graph is actually not resized in regards to the parent container. Is his expected? As the documentation says that this should be the case.

**Comment by assafsun** [comment]
@Ionaru what's the status with this issue? any update?

**Comment by Ionaru** [comment]
I played with the settings in an attempt to get something readable and eventually settled on this:

```ts
export class IndustryGraphLayout extends DagreLayout {
    settings: DagreSettings = {
        orientation: Orientation.TOP_TO_BOTTOM,
        ranker: 'network-simplex',
        rankPadding: 300,
    };
}
```

**Comment by marjan-georgiev** [comment]
> Interesting. When removing the view attribute, the graph is actually not resized in regards to the parent container. Is his expected? As the documentation says that this should be the case.

The parent element of the component needs to have a width and height set on it, so the graph component can fill it.

See how the '.page' div on this demo does it:
```
.page {
  width: 100%;
  height: 100vh;
  overflow: hidden;
}
```

https://stackblitz.com/edit/ngx-graph-demo?file=src%2Fapp%2Fapp.component.scss
