### ISSUE TITLE
Color not applied

### ISSUE THREAD

**Issue by jmdavid** [swimlane/ngx-graph#312]
**Describe the bug**
I defined colors in my nodes but my colors are not applied, it shows random colors from color set instead.

**To Reproduce**
I have Angular 8, I installed nxgraph v.6 as last version gives an error with Angular < 9.

I defined my nodes like this:

```
this.nodes = [
    {
        id: 'start',
        label: 'Start',
        dimension: {
            width: 100,
            height: 40
        },
        data: {
            color: '#00FF00'
        }
    },
    ...
```
In my template, I have this:

```
<ng-template #nodeTemplate let-node>
    <svg:g class="node">
        <svg:rect [attr.width]="node.dimension.width" [attr.height]="node.dimension.height" [attr.fill]="node.data.color" />
        <svg:text alignment-baseline="central" [attr.x]="10" [attr.y]="node.dimension.height / 2">{{node.label}}</svg:text>
    </svg:g>
</ng-template>
```

**Expected behavior**
My color should be applied (green)

**Screenshots**
![nxgraph-bug](https://user-images.githubusercontent.com/1364785/80315335-d085f080-87c4-11ea-9bfe-ae64ee150461.png)

**ngx-graph version**
`"@swimlane/ngx-graph": "^6.2.0"`

Is there something I do wrong?  What is strange is that my dimensions are applied but not the color.

Thanks.

**Comment by AnilBairi** [comment]
Even I have the same issue.

**Comment by sweeneki** [comment]
As a work-around try using a dual class in the html with the second part of your class as the color:
 <svg:g class="node" [attr.class]="node.data.color">
Then in your scss have a separate element for each specific color you wish to use:
.green {
  color: green; 
}

**Comment by marjan-georgiev** [comment]
You can set a different property (i.e. `customColor`) and use that in your template:

```
export const nodes: Node[] = [
  {
    id: 'first',
    label: 'A',
    data: {
      customColor: '#ff0000'
    }
  }, {
    id: 'second',
    label: 'B'
  }, {
    id: 'c1',
    label: 'C1'
  }, {
    id: 'c2',
    label: 'C2'
  }
];
```

```
<svg:rect [attr.width]="node.dimension.width" [attr.height]="node.dimension.height" [attr.fill]="node.data.customColor || node.data.color" />
```


Example:
https://stackblitz.com/edit/ngx-graph-demo-f1ty26?file=src%2Fapp%2Fapp.component.html
