### ISSUE TITLE
Long link labels being hidden by nodes

### ISSUE THREAD

**Issue by allensutton** [swimlane/ngx-graph#313]
**Describe the bug**
When creating a graph of nodes and links, if the link labels are particularly long, the ends of the labels are cut off by the nodes on the ends of the link and are not completely visible.

**To Reproduce**
Create a graph diagram using dagre layout.  
Create labels for the links that are about 35 characters long.
Observe that the ends of the labels are hidden by the nodes.

**Expected behavior**
Links should stretch to the size of their labels so that they are not hidden by nodes

**Screenshots**
![image](https://user-images.githubusercontent.com/38480134/80427467-cd1e6200-88b5-11ea-8124-bf268f602a6f.png)

**Demo**
https://stackblitz.com/edit/ngx-graph-simple-example-fuh9ev

**ngx-graph version**
^6.2.0

**Additional context**
I attempted to use rankPadding: 300 in the layout settings, but while that will expand everything far enough to expose the labels, that makes it so that the links without labels are way too long and the graph becomes enormous.  Is there a setting I can put on a link to expand it to the size of the label?  At that point I'd be able to do something like if(edge.label) { someSetting = someValue }

**Comment by assafsun** [comment]
Maybe play with dagre settings and extend the width of the graph which may help in the label width?
Look at node padding (if it doesn't work, try the other padding attributes, I don't remember exactly)
https://github.com/swimlane/ngx-graph/blob/e14c1c532bd2819f350382ac1826fb53dd23fd5f/projects/swimlane/ngx-graph/src/lib/graph/layouts/dagre.ts#L36

**Comment by allensutton** [comment]
I tried nodePadding, edgePadding, and played around with marginX and marginY, and all it seemed to do was move the nodes further away vertically rather than spreading the nodes out horizontally.  I noticed that the edges connect to the center of the node and are sort of behind it on the Z axis.  It seems like I need something that says "print the label as if the SVG line is connected to the edge of the node" or some calculation to redraw everything 30 pixels to the left or right (depending on which side of the link you're on).  Another idea I had was to set the length of the edge to the label length + 30, but I'm not really sure how to do that.

**Comment by assafsun** [comment]
Intersting  to understand if dagre layout support it otherwise, I don't think we can sync the label with the length of the link.
It will require a custom solution.

Another option is maybe to use the midpoint template UI for this link and not the labels that ngx-graph provide
look at:
https://github.com/swimlane/ngx-graph/blob/e14c1c532bd2819f350382ac1826fb53dd23fd5f/src/docs/demos/components/ngx-graph-org-tree/ngx-graph-org-tree.component.html#L39

Closing this for now, please reopen if needed.

Thanks
