### ISSUE TITLE
NGX-Graph with Angular CLI 8.3.23

### ISSUE THREAD

**Issue by nathan30** [swimlane/ngx-graph#314]
**Describe the bug**
I can't run npm run build-prod or build-watch because of the following error (see screenshot)  

**To Reproduce**
Use @angular/cli 8.3.23

**Expected behavior**
No issue while running npm build-watch or npm build-prod

**Screenshots**
http://i.imgur.com/BOz1iDD.png

**ngx-graph version**
7.0.1

**Comment by mrshahidmehmood** [comment]
Did you find any solution for this bug? I am facing the same problem

**Comment by nathan30** [comment]
> Did you find any solution for this bug? I am facing the same problem

Yes, Use the 6.0.1 or 6.0.2 version

**Comment by mrshahidmehmood** [comment]
Thanks @nathan30 , can you tell me how to install this specific versions? I am kinda new to angular.

**Comment by nathan30** [comment]
> Thanks @nathan30 , can you tell me how to install this specific versions? I am kinda new to angular.

Two solutions : 
Change the version into your package.json or 
`npm install @swimlane/ngx-graph@6.2.0 --save`

**Comment by mrshahidmehmood** [comment]
Thank you so much :)
