### ISSUE TITLE
ngx-graph is not working in Safari?

### ISSUE THREAD

**Issue by datavisorfrankhe** [swimlane/ngx-graph#315]
**Describe the bug**
I opened the demo page in Safari, and no graph is being displayed in Safari at all. Is Safari supported?
Please help to info how to make ngx-graph working in safari?
Thanks

**Comment by assafsun** [comment]
@marjan-georgiev any idea?

**Comment by assafsun** [comment]
Did you tried to load a master branch on a local environment?

**Comment by datavisorfrankhe** [comment]
why your demo site is not working?
https://swimlane.github.io/ngx-graph/#quick-start
do you need to redeploy?

**Comment by marjan-georgiev** [comment]
Yeah, there seems to be an issue with the demo app. However, ngx-graph is working fine with Safari. The stackblitz opens and renders fine:
https://swimlane.github.io/ngx-graph/demos/interactive-demo#interactive-demo
