### ISSUE TITLE
Add a setting to set alignment of the nodes regardless of the number of links converging to it.

### ISSUE THREAD

**Issue by shivankpandey2** [swimlane/ngx-graph#316]
**Is your feature request related to a problem? Please describe.**
I need to show nodes as successor relationship between them, but there is no way I can align them linealy, instead it is randomly aligned depending upon the number of links 

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/62129840/81728978-e4aa3d00-94a8-11ea-8f0e-153b097f9e53.png)

I would like  these nodes to be aligned linearly( if in anyway we can make the y axis to be fixed)
I tried using custom layout but that didn't worked for me, I am able to fix the y-axis for the node.position, but the links are not getting aligned according to the node position.
What I assume , right now links are getting created first and then the nodes are arranged according to it.
FYI I have used dagre layout.

**Comment by mrshahidmehmood** [comment]
Hello, is there any update on this thread?

**Comment by shivankpandey2** [comment]
I am still waiting for the solution or atleast some suggestions 😕

**Comment by viratpan974** [comment]
Any updates on this, facing the same issue.

**Comment by atuls1** [comment]
I am also facing the same issue.

**Comment by marjan-georgiev** [comment]
I assume you are using the dagre layout. Dagre is an external layout engine and we do not have control over it: https://github.com/dagrejs/dagre

However, you could build a custom layout that does what you want. You can learn more about layouts here: https://swimlane.github.io/ngx-graph/layouts#custom-layouts
