### ISSUE TITLE
errors with Dagre layout

### ISSUE THREAD

**Issue by tonylodge** [swimlane/ngx-graph#317]
**Describe the bug**
For what ever reason, when ever I generate a dagre graph, the final nodes never seem to line up correctly. In the following example, I would expect the Sim-1 and MSISDN-2 to line up correctly under their parents (RFS-OTA and RFS-Voicemail), however for what ever reason they do not. It also appears that the where the attached edges are, they have not attached to the correct edge. I would have expected them to attach to the bottom of the node and not the side.

**To Reproduce**

**Expected behavior**
 I would expect the Sim-1 and MSISDN-2 to line up correctly under their parents (RFS-OTA and RFS-Voicemail), however for what ever reason they do not. It also appears that the where the attached edges are, they have not attached to the correct edge. I would have expected them to attach to the bottom of the node and not the side.

**Screenshots**
![image](https://user-images.githubusercontent.com/44750112/82629678-d950c300-9bc6-11ea-86bb-2815cde27942.png)

**Demo**
Provide an online demo (stackblitz, codesandbox, or similar) where the issue can be reproduced 

**ngx-graph version**
6.13.4

**Additional context**

**Comment by assafsun** [comment]
I'm guessing that this issue should be open on dagre project and not this project unless there is something that ngx-graph does. in case you know that dagre gives a different set of points that ngx-graph don't show, please reopen it.

Another debug option is to test the layout from left to right and see if it keep the same distance between nodes

Thanks,
