### ISSUE TITLE
Custom Diamond-shaped node with two connections

### ISSUE THREAD

**Issue by AnilBairi** [swimlane/ngx-graph#318]
Just started using ngx-graph, looks really good to use. Currently, I am trying to create a custom Diamond-shaped node with two links from that ie "Yes" and "No" - like in flowchart scenario where we create a conditioning step. I could create a diamond using the SVG element and placed it in the graph layout. So, far no issues. later when I try to connect two nodes from this diamond-shaped node I have a problem., ie two nodes are linked from the same connection point but I want two nodes to be connected from two different points of a diamond-shaped node. I am bit new to this SVG elements. Please let me know if way to achieve this? Mentioning below the current diagram and expected diagram in pictorial representation.

![image](https://user-images.githubusercontent.com/52968923/83600632-9c081000-a58c-11ea-86ac-6a1b7471756f.png)

**Comment by WillPoulson** [comment]
I'd also like this functionality. I use this package for condition flows and it'd be great to get them to display like the expected example.

**Comment by Calidus** [comment]
You would need to create a custom layout.

https://swimlane.github.io/ngx-graph/layouts#custom-layouts

**Comment by assafsun** [comment]
This is a case for custom layout which is not planned for now. Thanks.
We do plan to invest in creating custom layouts but I don't think this specific case will be one of them
