### ISSUE TITLE
panToNode, graph not panned(rendered?) until mouse is moved

### ISSUE THREAD

**Issue by doorman02** [swimlane/ngx-graph#319]
I am using panToNode to navigate to a specific node. This seems to work fine except the panning doesn't always occur immeditately. Unless if I move the mouse the graph pans into right position. I am actually updating the graph before panning. I have also tried to put the panning a few milliseconds after the graph has been updated. I am wondering if the browser is re-rendering the content after I move the mouse, is there maybe a way to force re-rendering of the graph or the browser window?

ngx-graph 7.0.0

**Comment by doorman02** [comment]
I managed to fix this by simulating the mouse movement after panning. Not a nice fix but it works. Of course it would be nicer if this wouldn´t be an issue.

```
@ViewChild('graph', { read: ElementRef }) graph:ElementRef;

 private mouseMoveEvent = new MouseEvent('mousemove', {
    clientX: 0,
    clientY: 0,
    bubbles: true,
    cancelable: true
  });

  public panToNode(id: any) {
    this.panToNodeObservable.next(id);
    //  Fix to re-render graph on panning
    this.graph.nativeElement.dispatchEvent(this.mouseMoveEvent);
  }
```

**Comment by assafsun** [comment]
Can you please try to update the graph by using the update input?

**Comment by baltie** [comment]
I had the same problem with panTo. Since I was already accessing GraphComponent directly, I went ahead and called `this.graph.cd.markForCheck();`. That solved the problem. `this.graph` is my GraphComponent ViewChild. `cd` is the ChangeDetectorRef of the graph.

**Comment by marjan-georgiev** [comment]
You should be able to trigger an update via the `update$` input as well. You can pass that input, and just emit on it, which will trigger the chart to update itself.

**Comment by rrowlands** [comment]
I'm going to suggest that this ticket remain "open" as it is not resolved. Even though a workaround has been provided.

**Comment by deveshInn** [comment]
What worked for me is this:
  @ViewChild(GraphComponent) ngxGraph!: GraphComponent;

//trigger update of the graph just after you pan to node
      this.panToNode$.next(id);
      this.ngxGraph?.update(); // Force re-render
