### ISSUE TITLE
ng-template custom node is not visible

### ISSUE THREAD

**Issue by GlitchEclipse** [swimlane/ngx-graph#321]
I upgraded the version to 7.0.0-rc.1 and ng-template  example code on the demonstration will not load. If I remove the ng-template code I get the colored points again. This is off a fresh download and copying the examples from online. Angular version 9.1. Is this still a bug or should it be working? I read comments on Angular version 9.0.4 and version 7.0.0-rc.1 resolving this issue, but not for me. 

Also is there a way to interactively connect and disconnect the links to the nodes from the graph? Thanks.

**Comment by marjan-georgiev** [comment]
This should be fixed in the coming 7.1 release.
