### ISSUE TITLE
Reset graph and rebuild it

### ISSUE THREAD

**Issue by nathan30** [swimlane/ngx-graph#323]
Hi,

I want to reset my graph before rebuilt it. 

here is my code to do it now 
`
this.nodes = [];
this.links = [];
this.update$.next(true)
`
The problem is, when I rebuilt it I didn't have more than 1 level of depth. Here is before : 

[Before](https://i.imgur.com/Wrr8LKs.png)

And after (I just need to remove the N+4 links and target nodes)

[After](https://i.imgur.com/r3npV4Y.png)

I check my links and nodes array and I've seend something weird. My first nodes are well construct but the nodes for second and third level didn't have all the metadata like 'transform', 'position' etc..

Here is an example of the nodes before destruction : 

[Before](https://i.imgur.com/Jk5MaAP.png)

And the same node after rebuild (the first 3 nodes are great): 

[After](https://i.imgur.com/P0zml5h.png)

Any clues ? (Notice : the same functions are used to build and rebuilt)

**Comment by Calidus** [comment]
I think the easiest way to fresh the graph is to use the spread operator. You don't need to use ```update$``` if you making a new array.

```this.nodes = [...this.nodes]```

**Comment by marjan-georgiev** [comment]
Can you create a stackblitz with your example? @Calidus is correct in his suggestion. As long as you pass the same models, the graph will be rerendered in the same way.

**Comment by marjan-georgiev** [comment]
Closing due to no reply.
