### ISSUE TITLE
 Can `link label` replace text with font icons?

### ISSUE THREAD

**Issue by zmzimpl** [swimlane/ngx-graph#326]
![image](https://user-images.githubusercontent.com/27490895/85944313-61657d80-b968-11ea-9331-1b2855615d79.png)

Like this, I need to set the connection relationship between the tables, I try to replace textPath with `<svg class="icon" aria-hidden="true">
    <use xlink:href="#icon-left_join"></use>
</svg> `Such a font icon, but it seems not feasible.

**Comment by assafsun** [comment]
I'm not sure if SVG support it.

In case you want to add a UI on the middle of the links, I suggest to use the linkMidPoint option and maybe load a foreign object with your icon?
https://github.com/swimlane/ngx-graph/blob/e14c1c532bd2819f350382ac1826fb53dd23fd5f/src/docs/demos/components/ngx-graph-org-tree/ngx-graph-org-tree.component.html#L39

**Comment by marjan-georgiev** [comment]
You can add custom SVG in the link template instead of the label, as shown here:

https://stackblitz.com/edit/ngx-graph-demo-1szjbk?file=src%2Fapp%2Fapp.component.html

![image](https://user-images.githubusercontent.com/8687/87030855-84065a80-c1e2-11ea-92ef-0b9a88678844.png)
