### ISSUE TITLE
Link without a target that follow the mouse pointer

### ISSUE THREAD

**Issue by rangitha** [swimlane/ngx-graph#328]
I'm implementing some custom behaviour on top of my graph where the user can add/remove nodes and reconnect existing nodes. I make use of node and link templates with custom mouse events to accomplish most of this functionality programatically. 

However, I couldn't find a solution to provide visual feedback when drawing links between nodes. I'd like to show the intermediate step where a link is only connected on one side while the other follows the mouse pointer until the drag completes and the link is updated.

Is there a hack to achieve something like this?

**Comment by marjan-georgiev** [comment]
Yes, it's possible. You can project any additional SVG into the graph to build these customisations. Just add your custom SVG inside the ngx-graph component (outside the templates), and write the logic in your component.

Here's an example of what you're trying to achieve:
https://stackblitz.com/edit/ngx-graph-demo-23yiqf?file=src%2Fapp%2Fapp.component.ts

Start dragging from the red circles.

**Comment by Calidus** [comment]
@marjan-georgiev The demo is great, it gave me a couple ideas to try out. One question, could you explain the ```startingDragPosition``` code? Why isn't ```startingDragPosition``` the same as ```currentDragPostion``` in ```onNodeCicleMouseDown```?

```
this.startingDragPosition = {
      x: (event.layerX - this.graphEl.panOffsetX) / this.graphEl.zoomLevel,
      y: (event.layerY - this.graphEl.panOffsetY) / this.graphEl.zoomLevel
    };
this.currentDragPosition = {
      x: node.position.x + node.dimension.width / 2,
      y: node.position.y
    };
```

**Comment by marjan-georgiev** [comment]
Sure. The starting drag position is the beginning of the line, and the current drag position is the end. When you start dragging, we set them both to the same point, and then as you move your mouse we only update the current drag position

**Comment by Calidus** [comment]
Sorry I wasn't clear I was wondering why the code if different between the two, but they seem to yield the same results.

**Comment by marjan-georgiev** [comment]
It's just about where you want the line to start relative to the node's center. They can be the same point.

**Comment by ivanmpe** [comment]
@marjan-georgiev have idea of how draw link with draggableEnabled = true ?
