### ISSUE TITLE
Angular material 10

### ISSUE THREAD

**Issue by MartinoMensio** [swimlane/ngx-graph#332]
Hi,

**Is your feature request related to a problem? Please describe.**
I would like to upgrade my project to Angular material 10, and when I run `ng update @angular/material` it says:

```text
Package "@swimlane/ngx-graph" has an incompatible peer dependency to "@angular/cdk" (requires "6.x || 7.x || 8.x || 9.x", would install "10.0.2").
```

I can see in [this file](https://github.com/swimlane/ngx-graph/blob/b51d9067e7e568bfbaafd8d65fdeb4966f5e845a/projects/swimlane/ngx-graph/package.json) it is required angular/cdk with a lower version.

**Describe the solution you'd like**
I would like to know if the compatibility with Angular material 10 will be developed. I could help with that, but maybe someone else already did something.

**Describe alternatives you've considered**
Sticking to Angular material 9, or use the --force option

**Additional context**
.

Cheers,
Martino

**Comment by marjan-georgiev** [comment]
This should be resolved.
