### ISSUE TITLE
Ivy Breaks on latest release 

### ISSUE THREAD

**Issue by httpete** [swimlane/ngx-graph#333]
**Describe the bug**
ERROR in ./node_modules/@swimlane/ngx-graph/__ivy_ngcc__/fesm2015/swimlane-ngx-graph.js
Module not found: Error: Can't resolve '@swimlane/ngx-charts' in '/home/peters1/p4/um/node_modules/@swimlane/ngx-graph/__ivy_ngcc__/fesm2015'
 @ ./node_modules/@swimlane/ngx-graph/__ivy_ngcc__/fesm2015/swimlane-ngx-graph.js 3:0-148 19:0-47 1054:50-68 1228:24-47 1794:26-37 1996:33-47 2027:43-64 2207:14-28 2365:163-180 2370:144-159 2502:19-33 2530:215-232 2534:26-43 2540:141-156 2544:26-41
**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo**
Provide an online demo (stackblitz, codesandbox, or similar) where the issue can be reproduced 

**ngx-graph version**
Specify the version of ngx-graph where this bug is present

**Additional context**

**Comment by httpete** [comment]
this works on 7.0.1 fine btw.

**Comment by marjan-georgiev** [comment]
Taking a look

**Comment by marjan-georgiev** [comment]
@httpete I can't seem to reproduce on angular 10.0.5. Could you create a repo with a demo project and send it over please?

**Comment by marjan-georgiev** [comment]
Oh, can you check if you have `@swimlane/ngx-charts` installed? It is a dependency of ngx-graph, and that's what the error seems to be about.

**Comment by httpete** [comment]
I have to import both packages just to use ngx-graph? Seems like a lot of direct dependencies for something we don't use? Why did this happen in 7.1.1 and not 7.0.1 dyt?

**Comment by marjan-georgiev** [comment]
Not sure why. ngx-charts has always been a dependency of ngx-graph (we're actually planning to remove it - see https://github.com/swimlane/ngx-graph/issues/330), but looks like it stopped being automatically installed?

**Comment by marjan-georgiev** [comment]
Also, you shouldn't have to import the NgxChartsModule, ngx-graph imports it internally. Just need to have it installed.

**Comment by httpete** [comment]
It works just as you said. Thanks!
