### ISSUE TITLE
ngx-graph 7.1.1 breaks autozoom and centering of graph

### ISSUE THREAD

**Issue by alindberg** [swimlane/ngx-graph#334]
**Describe the bug**
Upgrading from ngx-graph 7.0.1 to 7.1.1 has broken both zoom and centering.

After manually centering and setting the correct zoom to display the entire graph, executing the 'center' function undoes all manual fixes.  Previously the 'center' function would center graph and adjust the zoom to fit in the view-port.

**To Reproduce**
Upgrade ngx-graph to 7.1.1

**Expected behavior**
Center and Zoom should work as before.

**Screenshots**
before update:
![image](https://user-images.githubusercontent.com/9355648/88343508-2d7f3d00-cd07-11ea-9507-7a4d981b6feb.png)

after updates.  Notice how it is off-centered and larger that then 'Before' version:

![image](https://user-images.githubusercontent.com/9355648/88343551-425bd080-cd07-11ea-8a6e-d447b2459b0d.png)

**Demo**
Will provide demo if necessary

**ngx-graph version**
v 7.1.1

**Additional context**
Angular CLI: 9.1.12
Node: 12.18.2
OS: linux x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/cdk                      9.2.4
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.6.0
typescript                        3.8.3
webpack                           4.42.0

**Comment by alindberg** [comment]
Example StackBlitz:

> [App Only](https://angular-9-ngx-graph-center-zoom-issue.stackblitz.io)

> [Editor and App](https://stackblitz.com/edit/angular-9-ngx-graph-center-zoom-issue)

**Comment by alindberg** [comment]
Just an FYI.  If you simply replace ngx-graph 7.1.1 with ngx-graph 7.0.1, all works as it shouldl

**Comment by marjan-georgiev** [comment]
Thanks for reporting it. Will be taking a look.

**Comment by OliverUlm** [comment]
I don't have as big of a difference as shown in the screenshot here but I just downgraded from 7.1.1 to 7.1.0 in order to have auto-zoom actually show the whole graph.

So I guess the issue got introduced in v7.1.1 and not v7.1.0

**Comment by alindberg** [comment]
I never installed 7.1.0 so I can't comment. I do know that 7.0.1 does not have the issue..

Thank you for having a look.

**Comment by alindberg** [comment]
**Follow-up question for anyone with the answer** - Where in the ngx-graph library are the paths and marker locations calculated?  As you can see from the examples on StackBlitz, when a node is moved, not only are the paths changes to straight lines, the markers all converge on the center of the node.  Prior to moving the node, the markers are distributed across the bottom (or top) of the node.

Thanks.

**Comment by alindberg** [comment]
### An additional observation

When adding the **`MiniMap`** viewer, the centering calculation seems to change.  You can see from the attached images than without the **`MiniMap`** enabled the rendered graph is off center (down to the right)

![image](https://user-images.githubusercontent.com/9355648/89806020-1d839d80-dafc-11ea-84c0-63446225a330.png)

when the **`MiniMap`** is enabled and set to the **`upperLeft`** or **`upperRight`** the graph is centered more to the **`upperLeft`**

![image](https://user-images.githubusercontent.com/9355648/89806127-41df7a00-dafc-11ea-8370-6c49eb535f8a.png)

![image](https://user-images.githubusercontent.com/9355648/89806259-66d3ed00-dafc-11ea-8fd5-f9275143efec.png)

**Comment by marjan-georgiev** [comment]
Released 7.1.2 which should fix this. Please let me know if you still see issues.

**Comment by OliverUlm** [comment]
@marjan-georgiev thank you for the update. I just upgraded to 7.1.2 and the behavior is now as follows:

IE11 - autozoom works (as in 7.0.1)
Firefox, Chrome and Chromium Edge - same issue as before.

Firefox:

![image](https://user-images.githubusercontent.com/7785366/93771521-e84f8c80-fc1d-11ea-9f47-ee82d88fb11e.png)

IE11
![image](https://user-images.githubusercontent.com/7785366/93771555-f6051200-fc1d-11ea-98e6-c55218e90da9.png)

Curiously enough - as soon as I resize the browser window it snaps into place on the other browsers as well.

Please let me know if I can provide any further info in diagnosing the issue.

**Comment by marjan-georgiev** [comment]
@OliverUlm thanks for the quick feedback. That's interesting, are you seeing that same behavior on firefox and chrome in 7.0.1?

A stackblitz would be helpful if you're able to create one.

**Comment by OliverUlm** [comment]
@marjan-georgiev I can't quite repo it on stackblitz - I assume that might be due to stackblitz dynamically loading the rendered output when loaded.

I now tried to display the graph only with a one second timeout (using a variable in a ngIf that is set after the timeout) and doing this it's working on Chrome too. Then only Firefox shows the issue. So something like this:

`<ngx-graph *ngIf="showGraph" #graph`

`setTimeout(() => this.showGraph = true, 1000);`

**Comment by marjan-georgiev** [comment]
Have you tried triggering the `update$` input after the graph gets rendered? It should force the graph to update itself.

**Comment by OliverUlm** [comment]
No, I have not. Anyway I would wait for feedback from other users. I have a solution that is working for me now.
