### ISSUE TITLE
Running NPM install throws 404

### ISSUE THREAD

**Issue by Deodatious** [swimlane/ngx-graph#336]
**Describe the bug**
Trying to install swimlane graphs throws a 404 error '@swimlane/ngx-graph@^7.1.1' is not in the npm registry. (We tried this with version 7.0.1 too)
This used to work, but since today it started throwing this error when we try and install swimlane.

**To Reproduce**
1. Run command npm i @swimlane/ngx-graph

**Expected behavior**
It should install swimlane for the current specified version in the package.json file (or new installation if it's a new project)

**Screenshots**
![image](https://user-images.githubusercontent.com/8483374/89516298-8dcab000-d7d8-11ea-815e-5729e75315c9.png)

**ngx-graph version**
7.0.1 AND 7.1.1

**Additional context**
This used to work fine

**Comment by marjan-georgiev** [comment]
There seems to be a problem with npm right now related to scoped packages:
https://status.npmjs.org/

Please try again once they resolve the issue.
