### ISSUE TITLE
How to create a flowchart builder application using ngx-graph

### ISSUE THREAD

**Issue by avash156** [swimlane/ngx-graph#337]
**Is your feature request related to a problem? Please describe.**
I want to build a flowchart using different shapes that I can drag and connect using ngx-graph in angular 10.Please suggest.

**Describe the solution you'd like**
Need an example for the same in angular 10

**Describe alternatives you've considered**

**Additional context**

**Comment by marjan-georgiev** [comment]
This is possible. Take a look at the examples in our demo. If you have any specific questions, please open a new issue.
