### ISSUE TITLE
Change orientation of nodes

### ISSUE THREAD

**Issue by nathan30** [swimlane/ngx-graph#347]
Hi,

Is it possible to choose if a node will be put on the right or left or the original Node ?

For exemple, how could I put the ARCO node on the left of BRUNEL and the VILLENEUVE node on the right of BRUNEL ?

https://i.imgur.com/Lp30Y8z.png

Thanks in advance

**Comment by marjan-georgiev** [comment]
This is controlled by the layout that you use. By default we use dagre (https://github.com/dagrejs/dagre), but we also allow using [custom layouts](https://swimlane.github.io/ngx-graph/layouts#custom-layouts), so you can control how the graph is layed out.
