### ISSUE TITLE
How to resolve errors on application start?

### ISSUE THREAD

**Issue by AngryBotIY** [swimlane/ngx-graph#351]
There is errors in my console when I trying to `ng start`:

![image](https://user-images.githubusercontent.com/51003204/94166508-0faf8f00-fe94-11ea-86dd-8ade9f3445b1.png)

I just follow `Introduction` steps at [ngx-graph](swimlane.github.io/ngx-graph/) and see this 👆

I use:

![image](https://user-images.githubusercontent.com/51003204/94167018-ac722c80-fe94-11ea-8a2f-24a279379a9f.png)

**Comment by nubinub** [comment]
You are using an "old version" of Angular which isn't compatible with the latest version of the library. You should upgrade your Angular version, or downgrade the library version to ^6.0.0.

**Comment by AngryBotIY** [comment]
So.... I don't need to wait answer here more.
