### ISSUE TITLE
Double click on node detection

### ISSUE THREAD

**Issue by lukasmatta** [swimlane/ngx-graph#352]
Hello,
I am successfully using (select) event on my graph to detect a single click on a node. However, I would like to add a double click event with different functionality. Is it anyhow possible to detect double click on a node?

Thanks.

**Comment by hmmdeif** [comment]
Add a `(dblclick)` input to your node template:

```
<ng-template #nodeTemplate let-node>
    <svg:g class="node" (click)="click(node)" (dblclick)="dblclick(node)">
        <svg:rect
        [attr.width]="node.dimension.width"
        [attr.height]="node.dimension.height"
        [attr.fill]="node.data.color"
        />
        <svg:text alignment-baseline="central" [attr.x]="10" [attr.y]="node.dimension.height / 2">
          {{node.label}}
        </svg:text>
    </svg:g>
</ng-template>
```

**Comment by lukasmatta** [comment]
@hmmdeif 

Thanks for helping me.

**Comment by tillias** [comment]
@lukasmatta sorry for pinging you in closed ticket, but do you have any example how to import svg namespace correctly? Related to https://github.com/visjs/vis-network/issues/1085
