### ISSUE TITLE
Documentation regarding event handling

### ISSUE THREAD

**Issue by tillias** [swimlane/ngx-graph#353]
**Is your feature request related to a problem? Please describe.**
I can't find any documentation or example how to handle events. Is click on node supported for example?

**Describe the solution you'd like**
Some documentation is needed

**Describe alternatives you've considered**
vis-network

**Comment by lukasmatta** [comment]
I agree that the documentation could be more clear about the events. 

From what I know, you have two options:
1. You can use `(select)` event on `<ngx-graph>` component to catch a user clicking on a node. 
2. You can place events directly on `<svg:g class="node">` element, if you define custom templates for node. Eventually, it would look like this (note that you can also use double click event): 
`<svg:g class="node"
    (click)="onNodeClick($event)"
    (dblclick)="onNodeDoubleClick($event)">`

Regarding the documentation, I would suggest updating the example code stated in the README.md file with these events.
