### ISSUE TITLE
ERROR in (1,1): Directive GraphComponent, Expected 1 arguments, but got 0.ERROR in (1,1): Directive GraphComponent, Expected 1 arguments, but got 0.

### ISSUE THREAD

**Issue by HarshStreamingo** [swimlane/ngx-graph#355]
**i am using ngx-graph to create DAG, while doing ng build --prod , i am receiving an Error:**

ERROR in (1,1): Directive GraphComponent, Expected 1 arguments, but got 0.
src/app/sub-pages/sub-page-graph/sub-page-graph.component.html(14,5): Directive GraphComponent, Expected 1 arguments, but got 0.

using angular version :8.3.2
swimlane/ngx-graph": "^6.1.0",

**Comment by marjan-georgiev** [comment]
This looks like a configuration issue. If you still have this problem, please open an new issue and provide a demo through stackblitz.
