### ISSUE TITLE
Project with 8.0.0-rc1 can't be build missing dependency d3-scale.

### ISSUE THREAD

**Issue by amelnikoff** [swimlane/ngx-graph#367]
Project using 8.0.0-rc1 can't be build, it requires d3-scale.

**To Reproduce**
1. Add dependency "@swimlane/ngx-graph": "^8.0.0-rc.1" to your angular project
2. Run npm install && ng build --prod
3. See error in console:
```
 ERROR in The target entry-point "@swimlane/ngx-graph" has missing dependencies:
 - d3-scale
```

**Expected behavior**
Don't know what is the best solution, easiest I think is to document at least this dependency

**Comment by aphedges** [comment]
I just tried installing `8.0.0-rc1` (I want to update to Angular 11), and I encountered this problem, too. I did a little bit of digging, and I think I know what went wrong: [`projects/swimlane/ngx-graph/src/lib/utils/color.helper.ts`](https://github.com/swimlane/ngx-graph/blob/0135be7b15043b2631fb8e2517f97fd3c19b8729/projects/swimlane/ngx-graph/src/lib/utils/color.helper.ts) imports from `d3-scale` but no dependency for `d3-scale` is in `package.json`. However, `d3-scale` is a dependency of `ngx-charts`, and after #363 removed `ngx-charts`, `d3-scale` was not installed anymore. `ngx-charts` specifically required `"d3-scale": "^3.2.1"`, so `ngx-graph` should likely use that requirement instead.

I would try to make a PR for this myself, but I'm really confused about how development works with the two `package.json`s. If you want out-of-organization PRs, then some simple contribution documentation might be useful.

**Comment by sweeneki** [comment]
Hi Alex

We’re you able to successfully upgrade to Angular 11 and NGX-Graph 8.0.0-rc.1? Have you heard if there will be a formal Graph version released?

Many thanks,

Kieran
Sent from my iPhone

On Feb 20, 2021, at 22:04, Alex Hedges ***@***.***> wrote:

﻿
I just tried installing 8.0.0-rc1 (I want to update to Angular 11), and I encountered this problem, too. I did a little bit of digging, and I think I know what went wrong: projects/swimlane/ngx-graph/src/lib/utils/color.helper.ts imports from d3-scale but no dependency for d3-scale is in package.json. However, d3-scale is a dependency of ngx-charts, and after #363 removed ngx-charts, d3-scale was not installed anymore. ngx-charts specifically required "d3-scale": "^3.2.1", so ngx-graph should likely use that requirement instead.

I would try to make a PR for this myself, but I'm really confused about how development works with the two package.jsons. If you want out-of-organization PRs, then some simple contribution documentation might be useful.

**Comment by aphedges** [comment]
@sweeneki, I was able to successfully upgrade to Angular 11 after the change.

As for a formal release, I have no clue. I'm just a user of the library. However, I haven't seen any comments by the maintainers since February, and there haven't been any PRs merged since April, so I don't have high hopes for a fixed release anytime soon.

**Comment by owfilip** [comment]
Well, I have the issue on Windows, but same lib built on Mac does not report any missing dependency. Anyway, try `npm i --save d3` as a workaround.

**Comment by DaSchTour** [comment]
There is a bug reported for a release candidate and then a major release is done without fixing the issue. Please be more careful when releasing new versions and check new issues. Thanks.
