### ISSUE TITLE
Reference of the hoveredVertical property on a line chart component.

### ISSUE THREAD

**Issue by ontiverosvzla** [swimlane/ngx-graph#368]
First of all, thanks for the great library and work that you guys have done and keep doing.

I am implementing a widget using the Line Chart component from the library. I can see from the repository that the tooltip anchor is just being activated (displayed) after hovering over the tooltip area component and some calculations are done. 
I need to react to those hovering events and display/hide other parts (below the chart) that are aligned with each tooltipAnchor (x axis).

My question is, is there a way that I can get the active tooltip anchor information every time they are shown/hidden ?, I see there is an activate event emitter but that happens when hovering on top of the line circle.

Again, thanks for the great work.

Best regard.

**Comment by marjan-georgiev** [comment]
Hi @ontiverosvzla. Thanks for the kind words. I believe you meant to open this in https://github.com/swimlane/ngx-charts. This one is a different projects for visualising graphs.

The charts don't currently support this. You could try getting into the internals of the component via ViewChild
https://blog.angular-university.io/angular-viewchild/

**Comment by ontiverosvzla** [comment]
Ugh, great, I thought I was under ngx-charts repository.

Thanks, will close and move to the other repository.
