### ISSUE TITLE
Node Template containing Angular Componet

### ISSUE THREAD

**Issue by florianeichin** [swimlane/ngx-graph#369]
**Describe the solution you'd like**
For a more complex use case it would make sense to have the ability to create more complex node templates. For instance in our case it would make sense to have an Angular component as a Node. Or is this already possible?

**Comment by marjan-georgiev** [comment]
This is already possible. You can use angular components inside a node template. Of course, this is SVG, so your components are HTML, you will need to wrap them in a `foreignObject` element
