### ISSUE TITLE
Node Connector Options

### ISSUE THREAD

**Issue by LincolnBanry** [swimlane/ngx-graph#374]
I am working on a relationship map, the current node connector options (ie - dagre cluster, bundle [et al] 1st example below) are not meeting the needs of the project.

I am looking to make my connectors more like the 2nd example below, but the last example is acceptable as well. 

We have tried everything we can think of, but we are new to ngx-charts and there is a large learning curve. I have looked through other issues and don't see anything there that has helped.

Mainly we want clear connectors that are compact and but more importantly that don't go behind other elements.

Any suggestions?

Thank you in advance.

![Current Option](https://user-images.githubusercontent.com/78451566/106958248-f34b1b00-66ed-11eb-92fc-6f75ad987a39.png)

![Desired Example](https://user-images.githubusercontent.com/78451566/106958281-fd6d1980-66ed-11eb-9dca-9b27f41b11de.png)

![Acceptable Option](https://user-images.githubusercontent.com/78451566/106958368-1d9cd880-66ee-11eb-94a9-123e7c70103b.png)

**Comment by marjan-georgiev** [comment]
This can be achieved by modifying the edge points on the layout. We have a demo (organisational tree) that does this, which can be seen here: https://swimlane.github.io/ngx-graph/demos/examples#organization-tree

The code for it is here: https://github.com/swimlane/ngx-graph/tree/master/src/docs/demos/components/ngx-graph-org-tree

In here: https://github.com/swimlane/ngx-graph/blob/master/src/docs/demos/components/ngx-graph-org-tree/customDagreNodesOnly.ts#L91-L113

you can see how we define the anchor points of the edges. You can insert as many additional points per edge as you want, and the line will go through them. Then you can smooth the line using different interpolation functions.
