### ISSUE TITLE
Browser not loading when using SVG

### ISSUE THREAD

**Issue by S3RRA** [swimlane/ngx-graph#375]
I`ve faced this issue in Chrome and Edge. I copy the examples from the docs, the quickstart graph at: "https://swimlane.github.io/ngx-graph/#quick-start" works alright, meanwhile when I try the SVG example at: "https://swimlane.github.io/ngx-graph/custom-templates#custom-svg" when running ng serve browser falls. In Chrome and Edge I`ve found the same error: "Error code: STATUS_ACCESS_VIOLATION". Strangest thing is that I´m able to see the SVG graph example in my app for a sec before it brakes at browser.

I´ve tried with several versions and neither of them worked:
CLI : 9.0.4 - swimlane/ngxgraph : 8.0.0-rc.1 - angular/cdk : 9.2.4
CLI : 9.0.4 - swimlane/ngxgraph : 7.0.0-rc.1 - angular/cdk : 9.2.4
CLI : 9.1.6 - swimlane/ngxgraph : 8.0.0-rc.1 - angular/cdk : 9.2.4
CLI : 9.1.6 - swimlane/ngxgraph : 7.0.0-rc.1 - angular/cdk : 9.2.4

At console after executing ng serve always Compiles Succesfully.

![image](https://user-images.githubusercontent.com/46560921/108639433-c429fd00-7494-11eb-8b99-0b051ace394c.png)
![image](https://user-images.githubusercontent.com/46560921/108639449-d6a43680-7494-11eb-8736-8a8917599ee8.png)

**Comment by S3RRA** [comment]
![Video_1614073125](https://user-images.githubusercontent.com/46560921/108819683-70fe9a00-75bb-11eb-861d-bc32ae4e748e.gif)

**Comment by lauti337r** [comment]
Having the same issue
