### ISSUE TITLE
Angular 11  swimlane/ngx-graph@7.2.0  obsolete dependence

### ISSUE THREAD

**Issue by VasylSemkiv** [swimlane/ngx-graph#383]
**Describe the bug**
Peer warnings thrown when `npm install`:
npm WARN @swimlane/ngx-graph@7.2.0 requires a peer of @angular/animations@6.x || 7.x || 8.x || 9.x || 10.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-graph@7.2.0 requires a peer of @angular/common@6.x || 7.x || 8.x || 9.x || 10.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-graph@7.2.0 requires a peer of @angular/core@6.x || 7.x || 8.x || 9.x || 10.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-graph@7.2.0 requires a peer of @angular/cdk@6.x || 7.x || 8.x || 9.x || 10.x but none is installed. You must install peer dependencies yourself.

**Expected behavior**
No warnings should be thrown.

**Comment by cdupetit** [comment]
Hello,
Do you have any release date on this issue ?
It cause issue on angular update process.
Thanks in advance.
Regards

**Comment by vrxj81** [comment]
8.0.0-rc1 doesn't have these obsolete dependencies

**Comment by OliverUlm** [comment]
Is there any planned release date for 8.0.0? Or are their any known issues with 8.0.0-rc1 that are currently being worked on?

**Comment by JonasSL** [comment]
I'm also waiting for this library to be updated - any news?
