### ISSUE TITLE
Custom Layout...Links not rendering

### ISSUE THREAD

**Issue by jefrog1844** [swimlane/ngx-graph#386]
**Describe the bug**
Trying to implement a custom layout class to generate a boundary diagram.  Nodes are rendered fine, but cannot get the links to even show in the DOM when inspecting the rendered page.

**To Reproduce**
`
************custom layout*****************************
import { Graph, Layout, Edge, Node } from '@swimlane/ngx-graph';

export class BlockDiagramLayout implements Layout {

    public run(graph: Graph): Graph {

        graph.nodes[0].position = { x: 50, y: 100 };
        graph.nodes[1].position = { x: 350, y: 100 };
        graph.nodes[2].position = { x: 350, y: 25 };
        graph.nodes[3].position = { x: 350, y: 175 };

        for (const edge of graph.edges) {
            this.updateEdge(graph, edge);
        }

        return graph;
    }

    public updateEdge(graph: Graph, edge: Edge): Graph {
        if (!edge.points) {
            const sourceNode = graph.nodes.find(n => n.id === edge.source);
            const targetNode = graph.nodes.find(n => n.id === edge.target);

            const startingPoint = {
                x: sourceNode?.position?.x,
                y: sourceNode?.position?.y
            };
            const endingPoint = {
                x: targetNode?.position?.x,
                y: targetNode?.position?.y
            };

            edge.points = [startingPoint, endingPoint];

        }
        return graph;
    }
}

***********app.component.ts************
 public nodes: Node[] = [
    {
      id: 'first',
      label: 'A',
      position: { x: 50, y: 100 }
    },
    {
      id: 'second',
      label: 'B',
      position : { x: 350, y: 100 }
    },
    {
      id: 'third',
      label: 'C',
      position : { x: 350, y: 25 }
    },
    {
      id: 'fourth',
      label: 'D',
      position : { x: 350, y: 175 }
    }
  ];

  public links: Edge[] = [
    {
      id: 'a',
      source: 'first',
      target: 'second',
      label: 'is parent of',
      points: [{x: 50, y: 50}, {x: 100, y: 100}]
    },
    {
      id: 'b',
      source: 'first',
      target: 'third',
      label: 'custom label'
    },
    {
      id: 'c',
      source: 'first',
      target: 'fourth',
      label: 'custom label'
    }
  ];

  public layout: Layout = new BlockDiagramLayout();

***************app.component.html**************

<ngx-graph
[view]="[800, 800]"
[links]="links"
[nodes]="nodes"
[layout]="layout"
[panOnZoom]="true"
[autoZoom]="true"
[autoCenter]="true"
[draggingEnabled]="true"
[panningEnabled]="true"
[enableZoom]="true"
>
<ng-template #nodeTemplate let-node>
  <svg:g>
    <svg:rect class="node" width="100" height="25"/>
  </svg:g>
</ng-template>

<ng-template #linkTemplate let-link>
  <svg:g class="edge">
    <svg:path class="line" stroke-width="2" marker-end="url(#arrow)"></svg:path>
    <svg:text class="edge-label" text-anchor="middle">
      <textPath
        class="text-path"
        startOffset="50%"
      >
        {{link.label}}
      </textPath>
    </svg:text>
  </svg:g>
</ng-template>

</ngx-graph>

`

**Expected behavior**
Links to be rendered from first to second, first to third, and first to fourth

**Screenshots**
I'm  building a boundary diagram like the following:
![boundary-diagram](https://user-images.githubusercontent.com/54285243/114305600-6da56c00-9a9e-11eb-8806-61b09a819f08.png)

**Demo**
n/a

**ngx-graph version**
7.2.0

**Additional context**

**Comment by jefrog1844** [comment]
resolved

**Comment by NguyenTrungMax** [comment]
Hi @jefrog1844 .
I have same issuse, can you suggest me how to draw boundary among nodes and links.
And  where I put it in.
Thank you so much
