### ISSUE TITLE
How to copy the content of a node in ngx-graph?

### ISSUE THREAD

**Issue by PayalGuptaG** [swimlane/ngx-graph#388]
I need help in copying the content of a node in ngx graph module. When I click on the node, it just moves around and I can't copy its content. Is there any way to copy to content?

**Comment by PayalGuptaG** [comment]
Can anyone please help on this??

**Comment by yash0412** [comment]
Content as in? You want to copy the node's label?

**Comment by PayalGuptaG** [comment]
yes..I have fixed it now.

**Comment by PayalGuptaG** [comment]
I used this in my .css file:
.node-text {
  -moz-user-select: text;
  -ms-user-select: text;
  -webkit-user-select: text;
  user-select: text;
}
