### ISSUE TITLE
Improve enter/exit animations

### ISSUE THREAD

**Issue by marjan-georgiev** [swimlane/ngx-graph#4]
Enter and exit animations should be fade in/fade out for nodes, instead of slide in.

**Comment by KingDarBoja** [comment]
@marjan-georgiev Hi there!

Just curious what you mean by enter and exit animations for nodes, so far, I tried making this using this code block based on the current `redrawLines` method:

```ts
  redrawNodes(_animate = true): void {
    this.nodeElements.map(nodeEl => {
      const node = this.graph.nodes.find(nod => nod.id === nodeEl.nativeElement.id);

      if (node) {
        const nodeSelection = select(nodeEl.nativeElement).select('.node');
        nodeSelection
          .style('opacity', 0)
          .transition()
          .style('opacity', 1)
          .duration(_animate ? 500 : 0)
      }
    });
  }
```

And adding it to the `requestAnimationFrame` call. But not sure if you want to apply it to only the nodes being inserted or for all of them.

Cheers!

**Comment by marjan-georgiev** [comment]
This is for the nodes that are inserted/removed from the graph. We need different transitions for moves/layout updates.

**Comment by KingDarBoja** [comment]
Ahh.. makes sense. But that would require drawing only the new nodes by comparing the node array so the graph doesn't get re-render on every update.

By the way, what does this line?
[textPathSelection](https://github.com/swimlane/ngx-graph/blob/master/projects/swimlane/ngx-graph/src/lib/graph/graph.component.ts#L557)

I feel like it does nothing right now unless the desired behaviour is target the edge-label. In that case, it should be:
```ts
const textPathSelection = select(linkEl.nativeElement).select('.edge-label');
```

Cheers!

**Comment by assafsun** [comment]
@marjan-georgiev @KingDarBoja I'm closing this issue as it seems that it's no longer relevant. In case we will have a new request for any animation, let's open a new issue.

Please update me if you think otherwise.
