### ISSUE TITLE
Issues with mousewheel directive + Angular 5

### ISSUE THREAD

**Issue by kenisteward** [swimlane/ngx-graph#40]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Using the graph I get this error
![Bug](https://user-images.githubusercontent.com/12831669/33395747-7dad1b3c-d514-11e7-9eb1-7a2494714bdf.PNG)

I have tracked it down to when core.js of Angular tries to instantiate the directive it is unable to find the output binding mouseWheelUp/mouseWheelDown as it says they are undefined.

Related issue

https://github.com/swimlane/ngx-datatable/issues/1104

which seems to have been solved
**Expected behavior**
component displays without the error

**Reproduction of the problem**
I currently can't reliably reproduce this error.

Specifics for my setup which I have tried to repro but can't outside of my specific env.

Using ngx-graph inside of a @ng-bootstrap/ng-boostrap modal.
Using ngx-graph outside of said modal on the same routed component page

**Please tell us about your environment:**

NPM
Windows
Vscode
Angular CLI "1.5.0"
Angular "5.0.2" (with aot compilation)

* **ngx-graph version:** x.x.x
4.0.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS 2.4.2

**Comment by kenisteward** [comment]
Retested with latest TS and still doesn't work.  might have to be done in the library itself

**Comment by kenisteward** [comment]
@isaacplmann it turns out we need to build the project itself with TS 2.4.2 or you get some incorrect build issues!  I've submitted a PR that corrects this and the #41 issue

on a related note, the build process should be updated to be compatible with the Angular Library suggested build structure.  This means some changes need to be made to not include the extra JS files and compile and roll them all into the bundle.

This happens currently but the way the exports happens it doens't compile fully correctly.  I can look further into this and update the project but it would take some time.

Right now when i compile it with my project it is using all the other .js files instead of the index.js bundle only unfortunately.

Also related, I don't know what your policies on deployment are but would it be helpful to just deploy the release folder instead of all the sources as well?

**Comment by isaacplmann** [comment]
I'm assuming that this is fixed for you, @kenisteward, since you submitted the PR that was merged.

**Comment by kenisteward** [comment]
Yup I should have closed this sorry!

**Comment by isaacplmann** [comment]
Np, just tidying up a bit.
