### ISSUE TITLE
Multi line text

### ISSUE THREAD

**Issue by cb1544** [swimlane/ngx-graph#416]
Hello,

Is there a way to wrap the text in the node's labels. 
I tried so many things but nothing seems to be working. 
I want the text to be in multi lines 

Do you have an example please ? 

Thank  you!

Best,
Camelia

**Comment by abishek** [comment]
I had a requirement where my node text was dynamic. So I hacked up a solution like this:

In the node template,
```
      <ng-template #nodeTemplate let-node>
        <svg:g class="node" xmlns="http://www.w3.org/2000/xhtml">
          <svg:foreignObject [attr.width]="node.dimension.width" [attr.height]="node.dimension.height">
            <xhtml:div class="cardContainer" xmlns="http://www.w3.org/1999/xhtml">
              <label class="name">{{ node.label }}</label>
            </xhtml:div>
          </svg:foreignObject>
        </svg:g>
      </ng-template>
```

And when I set the node text, I heuristically add a height and width dimension instead of the defaults. When adding the node, I set the dimension object to the node like this

```
node.dimension = {
   height: xxx,
   width: yyy
}
```

Hope this helps.

**Comment by cb1544** [comment]
Thank you @abishek 
It worked. But I lost the colors

<ng-template #nodeTemplate let-node>
    <svg:g class="node" xmlns="http://www.w3.org/2000/xhtml"
    (click)="onNodeClick($event)"
      (dblclick)="onNodeClick($event)"
      ngx-tooltip
      [tooltipPlacement]="'top'"
      [tooltipType]="'tooltip'"
      [tooltipTitle]="node.tooltipText">
      <svg:foreignObject [attr.width]="300" [attr.height]="50" [attr.fill]="node.data.color">
        <xhtml:div class="cardContainer" xmlns="http://www.w3.org/1999/xhtml">
          <label class="name">{{ node.label }}</label>
        </xhtml:div>
      </svg:foreignObject>
    </svg:g>
  </ng-template>

It seems that the colors are working when using svg:rect but not svg:foreignObject 

Any idea how to keep the colors please ?

Thank you so much for your help  !
