### ISSUE TITLE
AOT Build fails

### ISSUE THREAD

**Issue by Gimly** [swimlane/ngx-graph#42]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
The AOT build fails with the following error:

```
ERROR in TypeError: Cannot read property 'version' of null
```

It seems to be related to this pull request in ngx-charts: https://github.com/swimlane/ngx-charts/pull/639

**Expected behavior**
AOT shouldn't fail

**Reproduction of the problem**
Run `ng build --prod`

* **ngx-graph version:** 4.0.0

* **Angular version:** 5.0.0

* **Browser:** [all]

* **Language:** TypeScript 2.6.2

**Comment by kenisteward** [comment]
@gimly I've mad some resolutions in #43 

In general I'd suggest you build with TS 2.4.2 as I've found building libraries with > 2.6 cause unwanted issues with the compiler e.g. not including auto set variables like
```
class blah () {
  autoset = 'autoset'
}
```


For some reason with NG 5 and TS 2.6 it doesn't properly generate the set inside of the function as it should.  works fine with 2.4.2 though!

**Comment by isaacplmann** [comment]
Compiling your app with typescript 2.6 should work fine.  The problem comes when a library is compiled with something higher than 2.4.2.  So it will need to be fixed on our end.  I haven't tracked down if it is problem with just `ngx-graph` or it is also in `ngx-charts`.  I hope to have some time to look into it on Monday.

**Comment by isaacplmann** [comment]
FWIW, I'm using `ngx-charts-dag@3.0.1` in my app and that compiles with aot just fine.

**Comment by kenisteward** [comment]
@Gimly  Please try using 4.0.1 released 2 days ago.

**Comment by isaacplmann** [comment]
Thanks, @kenisteward. I forgot to mention it in this issue when I released that version.

**Comment by kenisteward** [comment]
@isaacplmann np +1
