### ISSUE TITLE
Can we get an 8.0 release published to npm

### ISSUE THREAD

**Issue by smeierhofer** [swimlane/ngx-graph#424]
The 8.0 RC 1 has been the most recent release for some time. Is there a timeline to get an official 8.0 release?
I am asking because our organization would like us to use only official releases rather than an RC, which is what we are currently using.

**Comment by smeierhofer** [comment]
The 8.0 RC 1 has been the most recent release for some time. Is there a timeline to get an official 8.0 release?
I am asking because our organization would like us to use only official releases rather than an RC, which is what we are currently using.

**Comment by marjan-georgiev** [comment]
8.0.0 has been published, with support for angular 13.
