### ISSUE TITLE
Help needed: Using circle instead of rect

### ISSUE THREAD

**Issue by panpan0000** [swimlane/ngx-graph#44]
**Using circle instead of rect**
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[*] support request => Please do not submit support request here
```

**Current behavior**
currently, the sample use  `<svg:rect>` which works well.
but if I want to use customized icon  or circle. 
I can't align the lines with the circle center...
![image](https://user-images.githubusercontent.com/14049268/34025324-2e0918e2-e18a-11e7-901b-f038d804629e.png)

**Expected behavior**
how to make the lines always connected with the circle center ?

**Comment by isaacplmann** [comment]
try this:

```
        <ng-template #nodeTemplate let-node>
          <svg:g class="node" ngx-tooltip [tooltipPlacement]="'top'" [tooltipType]="'tooltip'" [tooltipTitle]="node.label">
            <svg:circle [attr.r]="node.width/2" [attr.cx]="node.width/2" [attr.cy]="node.width/2" [attr.fill]="node.options.color" />
            <svg:text alignment-baseline="central" [attr.x]="10" [attr.y]="node.height / 2">{{node.label}}</svg:text>
          </svg:g>
        </ng-template>
```

Not perfect, but it gets you closer.

![screen shot 2017-12-15 at 10 16 27 am](https://user-images.githubusercontent.com/861504/34048269-1af9bea4-e181-11e7-9ae9-d653d2f55750.png)

**Comment by panpan0000** [comment]
Yes. @isaacplmann .  
although after drag the ball , the line doesn't not points to the center of balls. but anyhow , it's good at the beginning .
thank you.
![image](https://user-images.githubusercontent.com/14049268/34089121-f6696890-e3e8-11e7-8e9f-772404d502fa.png)
