### ISSUE TITLE
compatibility ploblem with angular4

### ISSUE THREAD

**Issue by changev** [swimlane/ngx-graph#45]
**I'm submitting a issue of ngx-graph && angular4**  
```
[ ] bug report => search github for a similar issue or PR before submitting
[√ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
ngx-graph depends on angular5, so when use it in auglar4, aot builds failed with
```
Error: Metadata version mismatch for module ./node_modules/@swimlane/ngx-graph/release/ngx-graph.module.d.ts, found version 4, expected 3

```
But when we use version 3.0.0, this issue appears: https://github.com/swimlane/ngx-graph/issues/20 

**Expected behavior**
There's a version that supports angular4

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-graph version:** latest

* **Angular version:** 4.4.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by isaacplmann** [comment]
This [comment](https://github.com/swimlane/ngx-graph/issues/20#issuecomment-347892907) says that the 3.0.0 error is solved in 3.0.1.  Try that version.

**Comment by changev** [comment]
@isaacplmann thank you !

but v3.0.1 also bring this error ```Error: Metadata version mismatch for module ./node_modules/@swimlane/ngx-graph/release/ngx-graph.module.d.ts, found version 4, expected 3```

**Comment by isaacplmann** [comment]
Ok, it looks like 3.0.1 was incorrectly compiled with Angular 5.  You have 2 options at this point:

1. Work around the 3.0.0 bug. If I remember correctly that error message doesn't actually break any functionality.

2. Upgrade to Angular 5.x and the latest ngx-graph version. Upgrading to Angular 5 was really easy for me - there are only a couple search and replace changes to make.

**Comment by changev** [comment]
@isaacplmann  Thank you.
unfortunately 3.0.0 breaks after aot build.
```
main.b45e21b5165ccf6e82aa.bundle.js:158 ERROR TypeError: Cannot read property '_in' of undefined
```

seems it can't build links.

**Comment by assafsun** [comment]
Closing this issue because ngx-graph is working with Angular 6.
If this issue still relevant, please reopen it or submit a new issue.
Thanks.
