### ISSUE TITLE
Angular 14 Not supported

### ISSUE THREAD

**Issue by JohnGalt1717** [swimlane/ngx-graph#459]
**Describe the bug**
Errors on build, including warnings about optimization bailouts.

**To Reproduce**
Upgrade project to v14.0.x

**Expected behavior**
Should work, with no warnings.

**ngx-graph version**
8.0.1

**Comment by Kr0san89** [comment]
It is resolved just not closed. Use latest Version and you should be good

**Comment by hmirsky** [comment]
Awesome. Thanks for the quick reply!

**Comment by marjan-georgiev** [comment]
Apologies. Closing the issue.
