### ISSUE TITLE
Add Filtering based on link and/or node types

### ISSUE THREAD

**Issue by Pranayku** [swimlane/ngx-graph#47]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Currently we are not able to filter based on link type or node type. However we can write our own flavor filtering criteria, but having a default functionality will really be a great addition

**Expected behavior**
There should be default filter functionality

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-graph version:** x.x.x

* **Angular version:** x.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by isaacplmann** [comment]
What would a filter UI look like?  What field(s) would it filter on?  It seems like it is very dependent on what your data is.

This seems like a feature that is better left to the developer using the chart to manage their own data.

**Comment by assafsun** [comment]
I agree. what is a filter on graph? do we want to show only nodes? only flows? only a certain node with the links that are attached to it? 
Each developer should set it's own filtering for his search functionality for example and set it.

**Comment by assafsun** [comment]
@marjan-georgiev what do you think?

**Comment by marjan-georgiev** [comment]
I agree, this is something that should be done outside of the component. Close this issue.
