### ISSUE TITLE
Basic example or more docs.

### ISSUE THREAD

**Issue by chalex1** [swimlane/ngx-graph#49]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here
```
Hi guys!
Looks like your work is very cool.
Please, can you give more details about how to use it. Some basic example.
or may be I miss some docs. Do you have extra documentation exept readme.md on the first page?
Thank you!

**Comment by isaacplmann** [comment]
You're right, the documentation could use some fleshing out.  The [demo](https://swimlane.github.io/ngx-graph) shows what some of the options do.  And the source code for the demo is [here](https://github.com/swimlane/ngx-graph/tree/master/demo).  As you explore and learn how it works, would you mind writing a PR to improve our docs?  I'd be happy to help explain things that you get stuck on.

**Comment by Konnoke** [comment]
I too would welcome some more documentations and examples!

**Comment by isaacplmann** [comment]
@Konnoke what specific scenarios are you looking for?  What are you trying to do?  I'll talk you through your use case over on [gitter](https://gitter.im/swimlane/ngx-graph) if you make a PR with what you learn.

**Comment by ajh187** [comment]
@isaacplmann I would just be looking for a more simple node and link connection to the actual visual. As it currently is the connections seem to be a bit abstract. If there was a more Simple UI that just has the very basics with the nodes and link file/json (or whatever it is) I believe it would be a lot more helpful for people starting out.

**Comment by mikeVaz0vsky** [comment]
Hello!

Looks like your work is very cool. But your url (https://github.com/swimlane/ngx-graph/tree/master/demo) the source code for the demo not found :(
I want docs/info/code for this lib

**Comment by fabianooc87** [comment]
> You're right, the documentation could use some fleshing out. The [demo](https://swimlane.github.io/ngx-graph) shows what some of the options do. And the source code for the demo is [here](https://github.com/swimlane/ngx-graph/tree/master/demo). As you explore and learn how it works, would you mind writing a PR to improve our docs? I'd be happy to help explain things that you get stuck on.

Hi, I'd like to download the source code for the demo, but the link is off. Is there another link where i can download it? 
Thanks!

**Comment by jlarso11** [comment]
Hi, I would love to get the demo code as well but the link appears to be broken.  Thanks

**Comment by marjan-georgiev** [comment]
Here's the demo for the current stable release (5.x): https://github.com/swimlane/ngx-graph/tree/5.x/demo

The master branch is the code for the upcoming 6.0.0 release.

**Comment by jlarso11** [comment]
@marjan-georgiev  - Thanks!
