### ISSUE TITLE
Curve is not a function

### ISSUE THREAD

**Issue by Lemonify** [swimlane/ngx-graph#50]
Hello,

**I'm submitting a ...** 
```
[ x ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Links between nodes are not drawn at all, because of this error:

`TypeError: curve is not a function
    at line (line.js:21)
    at GraphComponent../src/index.ts.GraphComponent.generateLine (index.js:38714)
    at _loop_1 (index.js:38562)
    at GraphComponent../src/index.ts.GraphComponent.draw (index.js:38579)
    at index.js:38681
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4744)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (zone.js:192)
    at webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:499)`

It seems it's missing some dependencies, although I've got D3 4.13.0 installed. Maybe wrong version?

**Expected behavior**
Links between nodes drawn correctly without errors.

**Reproduction of the problem**
I used the provided example just with nodes, links and SVG templates and example data. Without any more attributes and options.

**Please tell us about your environment:**
Windows 10, Apache, PhpStorm

* **ngx-graph version:** 4.0.2

* **Angular version:** 5.0.0

* **Browser:** All

* **Language:** TypeScript 2.4.2

**Comment by isaacplmann** [comment]
You need to assign a curve function to the `<ngx-graph>` component.

```
// component.ts file
import * as shape from 'd3-shape';

@Component({...})
export class WhateverComponent {
  // ...

  curve: any = shape.curveLinear; // or some other function from d3-shape
}

// component.html
<ngx-graph [curve]="curve" ...><ngx-graph>
```

**Comment by Lemonify** [comment]
Thank you very much for you help. Now it's working nicely :) Feeling bit silly it was that easy.

**Comment by isaacplmann** [comment]
Glad to help.

**Comment by CoreyCole** [comment]
Should this be added to readme?

**Comment by ao10** [comment]
@CoreyCole I think that it would be helpful to add to the readme.

**Comment by CoreyCole** [comment]
opened PR adding more guidance to readme
https://github.com/swimlane/ngx-graph/pull/115

**Comment by CoreyCole** [comment]
See updated file here: https://github.com/swimlane/ngx-graph/blob/50483f33db51886aede9c5bb8204a4e578557c68/README.md
