### ISSUE TITLE
Support for Elk compund nodes not available

### ISSUE THREAD

**Issue by bsarkadi** [swimlane/ngx-graph#515]
**Describe the bug**
Support for Elk compund nodes was listed as a new feature in 8.1.0, but it's not available as of 8.2.1.

**To Reproduce**
Choosing elk layout results in error.

**Expected behavior**
Elk layout and compound nodes should work.

**Screenshots**

**Demo**
Provide an online demo (stackblitz, codesandbox, or similar) where the issue can be reproduced 

**ngx-graph version**
8.2.1.

**Additional context**

**Comment by steveblue** [comment]
You can provide a custom layout for Elk and ngx-graph does support compoundNodes. We do not provide Elk with the library, but it is possible to integrate Elk with ngx-graph.
