### ISSUE TITLE
Angular 17 support

### ISSUE THREAD

**Issue by argalasjr** [swimlane/ngx-graph#533]
**Describe the bug**
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"10.x || 11.x || 12.x || 13.x || 14.x || 15.x || 16.x" from @swimlane/ngx-graph@8.2.3
npm ERR! node_modules/@swimlane/ngx-graph
npm ERR!   @swimlane/ngx-graph@"^8.2.3" from the root project

**Expected behavior**
Support Angular 17

**ngx-graph version**
8.2.3

**Comment by Kr0san89** [comment]
created already a PR https://github.com/swimlane/ngx-graph/pull/532

**Comment by Malwinderkaur** [comment]
@marjan-georgiev could we please get release for this PR [#532]. Currently the library is not working with Angular 17

**Comment by bsarkadi** [comment]
Any update on when this can be released?

**Comment by RamiKassouf** [comment]
Please update this

**Comment by devisw0** [comment]
Any update for Angular 17?

**Comment by ykoitzsch** [comment]
it seems to be working just fine with Angular 17 (at least from what I have seen so far but of course the warning is quite annoying). So a fix for this would be great.

**Comment by amitkachi** [comment]
Any update on this? i see PR is already approved! but not merged

> created already a PR #532 in the main time in package.json ` "overrides": { "@swimlane/ngx-graph": { "@angular/animations": "~17.0.0", "@angular/cdk": "~17.0.0", "@angular/common": "~17.0.0", "@angular/core": "~17.0.0" } }`

Any update on this? i see PR is already approved! but not merged

**Comment by labeled** [comment]
Bump, Angular 18 is releasing in a few weeks as well.

**Comment by FARINE-KHAN** [comment]
> it seems to be working just fine with Angular 17 (at least from what I have seen so far but of course the warning is quite annoying). So a fix for this would be great.

can you explain as m facing same error

**Comment by steveblue** [comment]
ngx-graph 9.0.0 now supports Angular 18.
