### ISSUE TITLE
How can I disable zooming?

### ISSUE THREAD

**Issue by WuglyakBolgoink** [swimlane/ngx-graph#54]
Is it possible?

**Comment by isaacplmann** [comment]
No, but I would like this feature too.  I'd welcome a PR.  A simple `enableZoom` input that is checked inside the `onZoom` function should do it.  If you can't make a PR, I'll get to it when I can.

**Comment by gergo0206** [comment]
I created a pull request for this feature.
It can be found here: #64

**Comment by CoreyCole** [comment]
It is now possible
```html
<ngx-graph
    <!-- inputs -->
    [enableZoom]="false"

    <!-- rest of graph -->
</ngx-graph>
```

This works, but now the scroll wheel does nothing. I have other content on the page above my graph and I cannot scroll up to it. @gergo0206 do you know about this or am I doing something wrong?

**Comment by CoreyCole** [comment]
I opened a different issue about this scrolling problem https://github.com/swimlane/ngx-graph/issues/110

**Comment by assafsun** [comment]
l'm closing this issue because it seems that the open issue from this thread is tracked in #110 

Let me know if I missed something.
