### ISSUE TITLE
Issues with angular 5.2.6 

### ISSUE THREAD

**Issue by JuxtopiaCAMMRAD** [swimlane/ngx-graph#56]
I used npm to install ngx-graph
I included NgxGraphModule  in app.module

import { NgxGraphModule } from '@swimlane/ngx-graph';
imports: [
    NgxGraphModule,
...]

I included d3 and dagre in my cli.json

 "scripts": [
                "../node_modules/d3/build/d3.min.js",
                "../node_modules/dagre/dist/dagre.min.js"
            ],

However it seems angular is still not recognizing ngx-graph directives 
"TypeError: Cannot read property 'nodes' of undefined"

Are there any additionally required dependencies besides ngx-graph, d3 and dagre?  
Has anyone else had similar issues with ngx-graph and angular 5.2.6?

**Comment by isaacplmann** [comment]
You don't need to include d3 or dagre in the `angular-cli.json`, but that won't hurt anything.

My guess is that you copied the demo code from the readme and you don't have an object called `hierarchialGraph` in your component.  The demo code assumes that you have a public member of your component class that looks like this (excuse the formatting):

```
  public hierarchialGraph = {
    links: [  {
    source: 'start',
    target: '1',
    label: 'links to'
  }, {
    source: 'start',
    target: '2'
  },
],
  nodes: [  {
    id: 'start',
    label: 'start'
  }, {
    id: '1',
    label: 'Query ThreatConnect',
  }, {
    id: '2',
    label: 'Query XForce',
  }
],
  };
```

**Comment by assafsun** [comment]
@JuxtopiaCAMMRAD  Thanks for your input, I'm closing this item after it was open for a long time. please update for any problem.
