### ISSUE TITLE
create node content

### ISSUE THREAD

**Issue by manvfx** [swimlane/ngx-graph#60]
how to create custom content for node?
for example image or icon with text.

**Comment by isaacplmann** [comment]
Check out the `nodeTemplate` on the [readme](https://github.com/swimlane/ngx-graph)

**Comment by obi5747** [comment]
Can you please show an example of a custom node content with an image/icon?

**Comment by manvfx** [comment]
yes exactly

**Comment by naveenr2112** [comment]
Hi, How do I specify the reduce the distance between two nodes ?
![screenshot_5](https://user-images.githubusercontent.com/14159191/39736439-92788310-529d-11e8-9e93-889cfe50dc2d.png)

**Comment by lucianomilen** [comment]
I, on the other hand, need to **increase** the distance between two nodes, since the label text written on the `path` is kinda big. The current behaviour puts the _overflowing_ text behind the nodes.
Is it possible to increase the distance between two nodes to fit the `label` of the edges?

**Comment by marjan-georgiev** [comment]
@lucianomilen that will be added in the next major version (6.0.0), along with the option to define custom layouts.

**Comment by marjan-georgiev** [comment]
Custom layouts are available for preview in the master branch. Closing this issue.
