### ISSUE TITLE
simple graph

### ISSUE THREAD

**Issue by manvfx** [swimlane/ngx-graph#61]
how to create simple ngx-graph in angular-cli step by step?

**Comment by n3xus** [comment]
+1 Demo Example is too bloated for beginners

**Comment by isaacplmann** [comment]
PRs welcome.  When you figure it out, pass on your knowledge to the next person.

**Comment by shantanoo-desai** [comment]
Hi all,

I am working towards creating a simple demo for this issue. Is it wise to create use this same issue for any issues I might stumble into?

**Comment by shantanoo-desai** [comment]
@isaacplmann I was rather thinking of creating a post explaining step by step stuff with a repo to back it up. I might take time. But I think it would be wise to open new issues so other stumbling on similar issues can hack their way through.

**Comment by assafsun** [comment]
I'm closing this issue as duplicate to #49 which also request a simple graph and more documentation.
Please update if  missed any items in this thread
