### ISSUE TITLE
change arrow for other node

### ISSUE THREAD

**Issue by manvfx** [swimlane/ngx-graph#62]
how to change arrow to link other node with drag and drop?

**Comment by assafsun** [comment]
You can drag the nodes but  dragging one link to point to another node is not supported yet.

**Comment by assafsun** [comment]
Agree. it will be nice functionally to add or delete nodes from the graph and adding UI for it.

Go for it and create a PR ;)

**Comment by assafsun** [comment]
@marjan-georgiev  I think you had some major progress with this request.

**Comment by alindberg** [comment]
I am using `ngx-graph` to display relationships between items that have three types of dependency, 1) tested in both directions, 2) tested from Parent to Child and 3) tested from Child to Parent.  To do this I created two types of end markers (a 1/2 circle and an arrow).  I also styled the connector line to reflect the item tested 'TO'.  Then using `*ngSwitchCase` select the correct combination of line style and end marker.

The `line` and `end-marker` style was returned using a function `pathStyle`:

Note - I had to append a string constant to my node's ID value because they are integers and `ngx-graph` wants a string, not a number...

`HTML`

    <ng-template #defsTemplate>
        <svg:marker id="EndMarker" viewBox="0 0 8 8" refX="4" refY="4"
            markerUnits="strokeWidth"
            markerWidth="4" markerHeight="4"
            stroke="green" stroke-width="0" fill="green"
        >
            <svg:circle cx="4" cy="4" r="4"/>
        </svg:marker>
        <svg:marker id="arrow"
            markerWidth="20" markerHeight="20" viewBox="0 0 50 50"
            refX="18" refY="5"
            markerUnits="strokeWidth"
            strok-width="2"
            orient="auto-start-reverse"
        >
            <svg:rect x="5" y="4" width="10" height="2" class="arrow-shield"/>
            <svg:polygon points=" 0,0 2.5,5 0,10 14,5 " fill="black"/>
            <svg:circle cx="18" cy="5" r="4" fill="green" stroke-width="0"/>
        </svg:marker>
    </ng-template>
    <ng-template #nodeTemplate let-node>
        <svg:g class="node"
            ngx-tooltip
            [tooltipPlacement]="'top'"
            [tooltipType]="'popover'"
            [tooltipTitle]="node.label"
        >
            <svg:rect
                [attr.width]="node.dimension.width"
                [attr.height]="node.dimension.height"
                [attr.fill]="node.data.color"
                [id]="nodeID(node.id)"
                style="stroke-width: 3; stroke: rgb(0,0,0);"

            />
            <svg:text alignment-baseline="central"
                [attr.x]="10"
                [attr.y]="(node.dimension.height / 4)">
                    {{node.label}}
            </svg:text>
            <svg:text alignment-baseline="middle"
                [attr.x]="10"
                [attr.y]="3 * (node.dimension.height / 4)">
                    {{node.verString}}
            </svg:text>
        </svg:g>
    </ng-template>
    <ng-template #linkTemplate let-link>
        <svg:g class="edge"
            ngx-tooltip
            [tooltipPlacement]="'top'"
            [tooltipType]="'popover'"
            [tooltipTitle]="link.direction"
        >
            <ng-container [ngSwitch]="link.direction">
                <svg:path
                    *ngSwitchCase="'ToFrom'"
                    [ngStyle]="pathStyle(link.source, link.target, link.direction)"
                    class="line"
                    stroke-width="3"
                    marker-start="url(#arrow)"
                    marker-end="url(#arrow)"
                >
                </svg:path>
                <svg:path
                    *ngSwitchCase="'FromOnly'"
                    [ngStyle]="pathStyle(link.source, link.target, link.direction)"
                    class="line"
                    stroke-width="3"
                    marker-start="url(#EndMarker)"
                    marker-end="url(#arrow)"
                >
                </svg:path>
                <svg:path
                    *ngSwitchCase="'ToOnly'"
                    [ngStyle]="pathStyle(link.source, link.target, link.direction)"
                    class="line"
                    stroke-width="3"
                    marker-start="url(#arrow)"
                    marker-end="url(#EndMarker)"
                >
                </svg:path>
            </ng-container>
            <svg:text class="edge-label" text-anchor="middle">
                <svg:textPath class="text-path" 
                    [attr.href]="'#' + link.id"
                    [style.dominant-baseline]="link.dominantBaseline" startOffset="50%">
                        {{link.label}}
                </svg:textPath>
            </svg:text>
        </svg:g>
    </ng-template>

`Style Function`

    pathStyle(source: string, target: string, direction: string): any {
        let colorTo: string;
        let colorFrom: string;
        try {
            colorFrom = selection.select('#nodeId-' + source).attr('fill');
        } catch ( err ) {
            colorTo = 'orange';
        }
        try {
            // colorFrom = this.d3Selection.select('#nodeId-' + source).attr('fill');
            colorTo = selection.select('#nodeId-' + target).attr('fill');
        } catch ( err ) {
            colorFrom = 'red';
        }
        let retVal: any;
        switch ( direction ) {
            case 'ToFrom':
                retVal = { 'stroke': 'darkred' };
                break;
            case 'ToOnly':
                retVal = { 'stroke': colorFrom, 'stroke-dasharray': '30,5' };
                break;
            case 'FromOnly':
                retVal = { 'stroke': colorTo, 'stroke-dasharray': '30,5' };
                break;
            default:
                retVal = { 'stroke': 'red !important' };
        }
        return retVal;
    }

**Comment by marjan-georgiev** [comment]
@alindberg thanks for sharing that! Any chance you could create a stackblitz for demo purposes?

**Comment by alindberg** [comment]
Here is a [StackBlitz ](https://stackblitz.com/edit/angular-ngx-graph-linkexample-custom-fills-and-markers)that demonstrates my approach to lines, fills and end-markers.

**Comment by marjan-georgiev** [comment]
@alindberg great example, thank you!

**Comment by assafsun** [comment]
@alindberg Thanks for the example, do you know why it's not working?

**Comment by KingDarBoja** [comment]
@assafsun I think doesn't work because `pathStyle()` method is being triggered hundred of times! 

I will submit a stackblitz if I manage to fix it.

**Comment by marjan-georgiev** [comment]
Here's an example on how this functionality can be implemented in your components:

https://stackblitz.com/edit/ngx-graph-demo-23yiqf?file=src%2Fapp%2Fapp.component.ts

**Comment by Hacklog24** [comment]
@marjan-georgiev 

Hi, I followed your example to add a new link between two nodes using drag and drop. I am attaching a screenshot where I add a link between nodes having the same target (only as a test). The rest of the code is the same. What I would like is to be able to retrieve the node on which I release the mouse in order to make the creation of the link dynamic. How can I do it? Thanks so much!

![onMouseUp()](https://user-images.githubusercontent.com/42044367/124377774-07e80b00-dcae-11eb-9dd3-8da4424e299b.PNG)

**Comment by arbertrary** [comment]
@Hacklog24 

It's a year later, you probably don't need this anymore but in case anyone else stumbles upon this issue just like me, I managed to do this by using `document.elementFromPoint(event.clientX, event.clientY)` which gives you the element under the cursor. Then I checked whether the element under the cursor is a `drag-circle`. I saved the id of the node which the circle belongs to as part of the `id` of the svg:circle element. Maybe this is a bit hacky though.

```TypeScript
  /**
   * On mouse up event
   *
   */
  @HostListener('document:mouseup', ['$event'])
  onMouseUp(event: MouseEvent): void {
    if (this.isDragging && this.draggingNode) {
      // logic if mouse is released over another node
      console.log("drop section");

      // elementFromPoint is MVP. gets the Element under the mouse cursor
      const circle = document.elementFromPoint(event.clientX, event.clientY);
      if (circle && circle.classList.contains("drag-circle")) {

        const targetId = circle.id.replace("circ-", "");

        const link: Edge = {
          id: this.draggingNode.id + Math.random().toString().substring(2, 8),
          source: this.draggingNode.id,
          target: targetId,
          label: "is parent of"
        }
        this.links.push(link);
        this.links = [...this.links];
      }
    }
    this.isDragging = false;
    this.draggingNode = undefined;
  }
}
```


```HTML
<svg:circle class="drag-circle" id="{{'circ-' + node.id}}" [attr.cx]="node.dimension.width"
                            [attr.cy]="node.dimension.height / 2" [attr.r]="8" fill="#ff0000" ngx-tooltip
                            tooltipTitle="New Action" tooltipPlacement="right"
                            (mousedown)="onNodeCircleMouseDown($event, node)"></svg:circle>
```
