### ISSUE TITLE
Zoom-Event

### ISSUE THREAD

**Issue by obi5747** [swimlane/ngx-graph#65]
How can i add a zoom event to the graph?

**Comment by isaacplmann** [comment]
You'd need to submit a PR to add an `@Output` to the graph component and call it whenever zooming happens.

Seems like a reasonable feature.

**Comment by assafsun** [comment]
@marjan-georgiev I'm closing this item.
If you meant to keep this item open than please reopen it. Thanks!

**Comment by marjan-georgiev** [comment]
Submitted a new PR for this: https://github.com/swimlane/ngx-graph/pull/141
