### ISSUE TITLE
Unhandled Promise rejection: Template parse errors: Can't bind to 'ngTemplateOutletContext' since it isn't a known property of 'ng-template'.

### ISSUE THREAD

**Issue by kmahalingpur** [swimlane/ngx-graph#72]
Hi im using angular 2 to render graph but im facing "Unhandled Promise rejection: Template parse errors:
Can't bind to 'ngTemplateOutletContext' since it isn't a known property of 'ng-template'.
" this issue. When i checked the issues i came to know that 'ngTemplateOutletContext' was the replacement  of 'ngOutletContext' for the fix of issue in angular 5. How can i use this in angular 2. until i migrate from angular 2 to 5. 
@marjan-georgiev is there any alternative way to use this in angular 2.

**Comment by assafsun** [comment]
Hi!
Is this issue still relevant? 
I believe that the use of Angular 2 will reduce over time so please update if we can close this issue for your case.

**Comment by marjan-georgiev** [comment]
@kmahalingpur our latest version is not compatible with angular 2. You could try using version `1.0.0` which is compatible with angular 2, but that is very old and not supported any more. I recommend upgrading your app to the latest angular version.
