### ISSUE TITLE
TypeError: _co.hierarchialGraph is undefined

### ISSUE THREAD

**Issue by issamRca** [swimlane/ngx-graph#75]
i got always in console of browser that type of Error  "TypeError: _co.hierarchialGraph is undefined". could someone tel me plz it's because of what?

**Comment by assafsun** [comment]
I'm assuming that graph is not loaded in addition to the error.
I don't exactly what's the problem but it seems like you don't use right the graph component.
Please review again the demo app and see the example.

**Comment by assafsun** [comment]
I'm closing this issue, please submit a new issue or update this one and I will try to help if it's reproduce.
