### ISSUE TITLE
rtl is not working 

### ISSUE THREAD

**Issue by kokodda** [swimlane/ngx-graph#77]
rtl is not working

**Comment by marjan-georgiev** [comment]
If you're referring to the right to left node orientation - it works fine. Need to set `[orientation]="'RL'"` on the component.

If you're referring to something else, please open an issue with more details.

**Comment by abhishekhingu** [comment]
Hi 
I am getting error Can't bind to 'orientation' since it isn't a known property of 'ngx-charts-line-chart'.
while try to do this in chart.
