### ISSUE TITLE
tooltip issue

### ISSUE THREAD

**Issue by gracian37** [swimlane/ngx-graph#80]
I get this error. Can't bind to 'tooltipPlacement' since it isn't a known property of ':svg:g'.
Anyone can help?Thanks!

**Comment by gracian37** [comment]
Thanks @naveenr2112 ,I have already installed ngx-tooltip,but still not work.

**Comment by somejavadev** [comment]
@gracian37 Same problem here, @naveenr2112  any guidance?

**Comment by alienninja** [comment]
I was able to resolve this buy including the module NgxChartsModule in my apps.module.ts.

Note this is the error I was receiving:

compiler.js:486 Uncaught Error: Template parse errors:
Can't bind to 'tooltipPlacement' since it isn't a known property of ':svg:g'. ("
          <svg:g class="node"
            ngx-tooltip
            [ERROR ->][tooltipPlacement]="'top'"
            [tooltipType]="'tooltip'"
            [tooltipTitle]="node.lab"): ng:///AppModule/DiagGraphComponent.html@31:12
Can't bind to 'tooltipType' since it isn't a known property of ':svg:g'. ("
            ngx-tooltip
            [tooltipPlacement]="'top'"
            [ERROR ->][tooltipType]="'tooltip'"
            [tooltipTitle]="node.label">
            <svg:rect [attr.width]"): ng:///AppModule/DiagGraphComponent.html@32:12
Can't bind to 'tooltipTitle' since it isn't a known property of ':svg:g'. ("
            [tooltipPlacement]="'top'"
            [tooltipType]="'tooltip'"
            [ERROR ->][tooltipTitle]="node.label">
            <svg:rect [attr.width]="node.width" [attr.height]="node.heig"):

**Comment by gracian37** [comment]
Thanks @alienninja .It works!

**Comment by jafarpoor** [comment]
hello - i need Help .  i have Example from ngx-graph with tooltip but tooltip donot word . i install pakge tooltip and add to app.module 

<ngx-graph
  class="chart-container"
  [view]="[500, 550]"
  [links]="[
    {
      id: 'a',
      source: 'first',
      target: 'second',
      label: 'is parent of'
    }, {
      id: 'b',
      source: 'first',
      target: 'c1',
      label: 'custom label'
    }, {
      id: 'd',
      source: 'first',
      target: 'c2',
      label: 'custom label'
    }, {
      id: 'e',
      source: 'c1',
      target: 'd',
      label: 'first link'
    }, {
      id: 'f',
      source: 'c1',
      target: 'd',
      label: 'second link'
    }
  ]"
  [nodes]="[
    {
      id: 'first',
      label: 'A'
    }, {
      id: 'second',
      label: 'B'
    }, {
      id: 'c1',
      label: 'C1'
    }, {
      id: 'c2',
      label: 'C2'
    }, {
      id: 'd',
      label: 'D'
    }
  ]"
  [clusters]="[
    {
      id: 'third',
      label: 'Cluster node',
      childNodeIds: ['c1', 'c2']
    }
  ]"
  layout="dagreCluster"
>
  <ng-template #defsTemplate>
    <svg:marker id="arrow" viewBox="0 -5 10 10" refX="8" refY="0" markerWidth="4" markerHeight="4" orient="auto">
      <svg:path d="M0,-5L10,0L0,5" class="arrow-head" />
    </svg:marker>
  </ng-template>


  <ng-template #nodeTemplate let-node>
    <svg:g
      class="node"
      ngx-tooltip
      [tooltipPlacement]="'top'"
      [tooltipType]="'tooltip'"
      [tooltipTitle]="tttttttt"
    >
      <svg:rect
        [attr.width]="node.dimension.width"
        [attr.height]="node.dimension.height"
        [attr.fill]="node.data.color"
      />
      <svg:text alignment-baseline="central" [attr.x]="10" [attr.y]="node.dimension.height / 2">
        {{node.label}}
      </svg:text>
    </svg:g>
  </ng-template>

  <ng-template #linkTemplate let-link>
    <svg:g class="edge">
      <svg:path class="line" stroke-width="2" marker-end="url(#arrow)"></svg:path>
      <svg:text class="edge-label" text-anchor="middle">
        <textPath
          class="text-path"
          [attr.href]="'#' + link.id"
          [style.dominant-baseline]="link.dominantBaseline"
          startOffset="50%"
        >
          {{link.label}}
        </textPath>
      </svg:text>
    </svg:g>
  </ng-template>
</ngx-graph>
