### ISSUE TITLE
Error output when building with fullTemplateTypeCheck 

### ISSUE THREAD

**Issue by benoitbzl** [swimlane/ngx-graph#81]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Building an application with fullTemplateTypeCheck set to true produces the error (file path removed):

`
.../status-graph-widget.component.html(27,11): : Directive GraphComponent, Expected 1 arguments, but got 0.
`

**Expected behavior**
No error reported.
I guess the error is there: 
https://github.com/swimlane/ngx-graph/blob/b04f64ae52a37d86383fe1515399adfe53adc609/src/graph/graph.component.ts#L859-L860

The function expects an argument, but the HostListener decorator does not provide one.

**Reproduction of the problem**
Build an application in prod mode with the fullTemplateTypeCheck parameter set to true.
Add to the tsconfig.app.json file:
`
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
  },
`

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-graph version:** 5.0.0

* **Angular version:** 6.0.1

* **Browser:** [ ]

* **Language:** [TypeScript 2.7.2]

**Comment by assafsun** [comment]
Please upgrade to version 5.2.1
I built it with fullTemplateTypeCheck and it results with no errors.
Please update me if I missed something, I'm closing this issue for now.

**Comment by sh-developers** [comment]
@assafsun  I have this exact same issue with ng-packagr default issues (they turn this on by default, with good reason), the issues is still on the same spot:
https://github.com/swimlane/ngx-graph/blob/master/projects/swimlane/ngx-graph/src/lib/graph/graph.component.ts#L944

```
@HostListener('document:mouseup')
onMouseUp(event: MouseEvent): void {
```
Should probably be:
```
@HostListener('document:mouseup', ['$event'])
onMouseUp(event: MouseEvent): void {
```

**Comment by assafsun** [comment]
Opening it for additional investigation.

Can you please elaborate on the problem reproduction?

**Comment by sh-developers** [comment]
When turning on strict template type check whilst compiling, it says that it is expecting 1 argument but getting 0 in the GraphComponent. The above mentioned piece of code is the culprit, as it says it expects an MouseEvent, but doesnt tell Angular so.

If I apply the above fix to the ngx-graph component, no errors are displayed.

You can probably reproduce by setting the mentioned "fullTemplateTypeCheck" to true in https://github.com/swimlane/ngx-graph/blob/master/projects/swimlane/ngx-graph/tsconfig.lib.json
This would also prevent any other errors slipping into the codebase in the future.

**Comment by sh-developers** [comment]
Any progress on fixing/replicating?

**Comment by wassim-azirar** [comment]
I'm having the same problem when I build my app with `ng build --prod`

ERROR in Directive GraphComponent : **Directive GraphComponent, Expected 1 arguments, but got 0.**

`  <ngx-graph [links]="links" [nodes]="nodes" [clusters]="clusters" ...`

**Comment by vkahawala** [comment]
Reproduced with below versions:
"ng-packagr": "^5.5.0",
"@swimlane/ngx-graph": "^6.1.0"

`Directive GraphComponent, Expected 1 arguments, but got 0.`

More detailed error:
`[error] Error:Directive GraphComponent, Expected 1 arguments, but got 0.
    at Object.<anonymous> (/<project path>/node_modules/ng-packagr/lib/ngc/compile-source-files.js:73:19)
    at Generator.next (<anonymous>)
    at fulfilled (/<project path>/node_modules/ng-packagr/lib/ngc/compile-source-files.js:4:58)`

**Comment by marcusrettig** [comment]
You can reproduce the issue by adding
```
"angularCompilerOptions": {
  "fullTemplateTypeCheck": true
}
```
to `tsconfig.json` in project root, then running `ng build --aot`.

Opened a [PR](https://github.com/swimlane/ngx-graph/pull/237) with a fix.

**Comment by marjan-georgiev** [comment]
Merged the PR, thanks @marcusrettig

**Comment by cifcloud** [comment]
> Merged the PR, thanks @marcusrettig

@marjan-georgiev When will this be released as a new version? It's a great package, but we need this fix to be able to put our latest code into production.
