### ISSUE TITLE
prohibit the links between the nodes from overlapping ?

### ISSUE THREAD

**Issue by issamRca** [swimlane/ngx-graph#83]
how can i prohibit the links between the nodes from overlapping?

![capture](https://user-images.githubusercontent.com/29162735/39997889-af305d3e-5784-11e8-9437-3c70bba17655.PNG)

**Comment by marjan-georgiev** [comment]
The link layout is generated by dagre, which is a third party library we use.

You can avoid it in this particular case by changing the curve interpolation to something else.

**Comment by issamRca** [comment]
I need to use this curve interpolation('step')  and resolve the overlapping issue, Is there a way?

**Comment by marjan-georgiev** [comment]
Unfortunately not on our side. I would suggest opening an issue with dagre: https://github.com/dagrejs/dagre

Alternatively, try any of the other step interpolations and see if they solve the issue.

**Comment by shyamsathyan** [comment]
Hi,

While choosing the step and step Before line interpolation options I am facing the issue like the edge and the arrow head is overlapping with the node boundaries. Please provide a solution for this

![image](https://user-images.githubusercontent.com/31466782/117106348-54da5e80-ad9d-11eb-8bf3-64e568cd0d21.png)
