### ISSUE TITLE
change position of a nodes ?

### ISSUE THREAD

**Issue by issamRca** [swimlane/ngx-graph#90]
i need to put "I2"(interface) inside  #"Eq1"(router) and "I4" inside "equi2" how i can do that? 
![capture](https://user-images.githubusercontent.com/29162735/40907743-0a7a74e8-67e5-11e8-9c21-d64fdf81d540.PNG)

**Comment by alienninja** [comment]
It would greatly help me as well for an example like this as I would like to use nested boxes.

**Comment by isaacplmann** [comment]
6.x will have support for custom layout engines and give you more control over the default dagre layout engine.  Nested boxes are sometimes called clusters or groups.  The 6.x branch has a dagreCluster example and a cola.js example that also uses clusters.  And you can create your own if you want to.

https://github.com/swimlane/ngx-graph/blob/6.x/demo/app.component.ts

Still working on documentation for the 6.x release.

**Comment by issamRca** [comment]
@isaacplmann  can you give us an example of 'turbine.json' how would it like for Nested boxes?

**Comment by issamRca** [comment]
I tried for a while to run the 6.x Demo but i had some error like:

ERROR in src/app/graph/graph.component.ts(35,36): error TS2305: Module '"C:/Users/A690206/Desktop/sw/node_modules/rxjs/Rx"' has no exported member 'of'.

src/app/graph/graph.component.ts(366,34): error TS2339: Property 'nodes' does not exist on type '{}'.

src/app/graph/index.ts(3,15): error TS2691: An import path cannot end with a '.ts' extension. Consider importing './mouse-wheel.directive' instead.

src/app/graph/layouts/colaForceDirected.ts(7,8): error TS2307: Cannot find module 'webcola'.

src/app/graph/layouts/colaForceDirected.ts(89,7): error TS2322: Type '{ nodes: any; groups: any[]; links: any; groupLinks: Edge[]; }' is not assignable to type 'ColaGraph'.
  Object literal may only specify known properties, and 'groupLinks' does not exist in type 'ColaGraph'.

**Comment by isaacplmann** [comment]
Thanks for posting those errors.  A couple of those should be solved by running `npm install`.  The `mouse-wheel.directive` import error and the `ColaGraph` type error have been fixed.  Let me know if you're stilling getting errors.

**Comment by issamRca** [comment]
that what i got : 


ERROR in src/src/declarations.d.ts(8,22): error TS2304: Cannot find name 'NodeRequire'.

ERROR in src/app/graph/graph.component.ts(35,36): error TS2305: Module '"C:/Users/A690206/Desktop/sw/node_modules/rxjs/Rx"' has no exported member 'of'.

src/src/graph/graph.component.ts(366,34): error TS2339: Property 'nodes' does not exist on type '{}'.

src/app/graph/index.ts(3,15): error TS2691: An import path cannot end with a '.ts' extension. Consider importing './mouse-wheel.directive' instead.

src/src/graph/layouts/colaForceDirected.ts(7,8): error TS2307: Cannot find module 'webcola'.

src/src/graph/layouts/colaForceDirected.ts(89,7): error TS2322: Type '{ nodes: any; groups: any[]; links: any; groupLinks: Edge[]; }' is not assignable to type 'ColaGraph'.

  Object literal may only specify known properties, and 'groupLinks' does not exist in type 'ColaGraph'.

**Comment by issamRca** [comment]
i still have the errors above, where i can find the version that you have corrected?

**Comment by isaacplmann** [comment]
Pull in the latest code from the 6.x branch.

**Comment by issamRca** [comment]
now I have these errors:

ERROR in src/src/declarations.d.ts(8,22): error TS2304: Cannot find name 'NodeRequire'.

ERROR in src/app/graph/graph.component.ts(35,36): error TS2305: Module '"C:/Users/A690206/Desktop/sw/node_modules/rxjs/Rx"' has no exported member 'of'.

src/src/graph/graph.component.ts(366,34): error TS2339: Property 'nodes' does not exist on type '{}'.

src/src/graph/layouts/colaForceDirected.ts(7,8): error TS2307: Cannot find module 'webcola'.

**Comment by isaacplmann** [comment]
Delete your `node_modules` and re-run `npm install`.  Then run `ng -v` and post the response that it prints here.  There's something in your environment that is different from mine.

**Comment by isaacplmann** [comment]
ngx-graph is using newer versions Angular, cli and typescript.  Any one of those things could cause errors when building.  Did you clone the ngx-graph repo and try to build it?  Or is this a problem trying to build your app?

**Comment by issamRca** [comment]
i try to run demo with newer versions Angular, cli and typescript.
I have these 2 errors:

ERROR in src/src/declarations.d.ts(8,22): error TS2304: Cannot find name 'NodeRequire'.
src/src/graph/layouts/colaForceDirected.ts(7,8): error TS2307: Cannot find module 'webcola'.

after adding   "webcola": "^3.3.8" to the depencies
i had that 

ERROR in src/src/declarations.d.ts(8,22): error TS2304: Cannot find name 'NodeRequire'.
src/src/graph/layouts/colaForceDirected.ts(69,9): error TS2322: Type '{ id: string; padding: number; groups: any[]; leaves: any[]; }' is not assignable to type 'Group'.
  Object literal may only specify known properties, and 'id' does not exist in type 'Group'.

**Comment by issamRca** [comment]
did u have any idea why  I have this error?Did you have successfully executed an example with nested nodes?

Failed to compile.
src/src/graph/layouts/colaForceDirected.ts(69,9): error TS2322: Type '{ id: string; padding: number; groups: any[]; leaves: any[]; }' is not assignable to type 'Group'. Object literal may only specify known properties, and 'id' does not exist in type 'Group'.

**Comment by issamRca** [comment]
i clone the ngx-graph repo and try to build it ,did u have any idea why  I have this error?Did you have successfully executed an example with nested nodes?

Failed to compile.
src/src/graph/layouts/colaForceDirected.ts(69,9): error TS2322: Type '{ id: string; padding: number; groups: any[]; leaves: any[]; }' is not assignable to type 'Group'. Object literal may only specify known properties, and 'id' does not exist in type 'Group'.

**Comment by assafsun** [comment]
I think clusters can help with this case no?

**Comment by assafsun** [comment]
Closing this issue because there is a release candidate for 6 and no response to may latest message.

Let me know for any changes.

**Comment by suryasyam61** [comment]
How to change node positions using Node id
