### ISSUE TITLE
customColors function passes the name instead of value for <ngx-charts-number-card>

### ISSUE THREAD

**Issue by ciukstar** [swimlane/ngx-graph#91]
`customColors`'s function passes the name instead of value for `<ngx-charts-number-card>`

**Comment by marjan-georgiev** [comment]
Did you mean to open this in `ngx-charts`?

**Comment by assafsun** [comment]
@ciukstar I'm closing this issue due to the time that passed and because it seems like a ngx-charts question.
Please update if I missed something in this thread or open a new issue.

Thanks!
