### ISSUE TITLE
Links do not work correctly if node IDs have hyphens (version 4.x)

### ISSUE THREAD

**Issue by cwgorman** [swimlane/ngx-graph#92]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
If node ids include hyphens (`-`, eg UUIDs) then links are not drawn.

**Expected behavior**
ngx-graph should be agnostic of the ids used and draw the links correctly.

**Please tell us about your environment:**
Chrome, MacOS

* **ngx-graph version:** 4.3.0
The issue seems to have been fixed in the newest version, but the newest version doesn't work with Angular 5. The line seems to be [here](https://github.com/swimlane/ngx-graph/blob/87166c9c23d1967a46e603c52c828ef76dcb0463/src/graph/graph.component.ts#L387). This was fixed for the newest version [in this commit](https://github.com/swimlane/ngx-graph/commit/0b3128dc57e7c1843104b585bc7edde71b4b63d7).

* **Angular version:** 5.2.10
We cannot update our Angular version at this time due to other dependencies.

My request is that this fix be included in a version 4.3.1 release, based off the 4.x branch that still works with Angular 5.

**Comment by assafsun** [comment]
Hi @cwgorman! Is this issue still relevant?

**Comment by assafsun** [comment]
Latest version of ngx-graph is working Angular 6
I'm closing this issue due to the release to ngx-graph latest versions.

Please update for any other issue and we will respond to it.

Thanks.
