### ISSUE TITLE
Hide some links in graph

### ISSUE THREAD

**Issue by Maciejszuchta** [swimlane/ngx-graph#94]
Is there a way to dynamically hide certain links in graph?

**Comment by marjan-georgiev** [comment]
Answered this on gitter, but will do it here in case other users have the same issue. 

Yes, you can hide the links and nodes in your custom templates based on the links/node's data. Just use *ngIf and don't render anything for the links you don't want to show.

In the future, please don't use the github issues for questions. Use gitter/stackoverflow instead, and give us some time to respond. Also, when opening a github issue, fill out the issue form correctly.
