### ISSUE TITLE
Dynamically update links in graph

### ISSUE THREAD

**Issue by Maciejszuchta** [swimlane/ngx-graph#95]
OK, so what I'm trying to achieve is:

I successfully created a graph with all needed links and nodes. Now using my pathfinding algorithm I want to find the quickest path from start to end of my graph. For this, I updated the graph links so that I can hide the links that are not necessary for the shortest path and don't lose the initial graph structure. 

Unfortunately, I cant achieve this. What I tried was:

Using [attr.stroke-width] and if link is to be hidden i set it to 0
Using [ngStyle] = "{'display': 'none'}" for hidden links

It looks like setting those only work for initial data when the graph is rendered for the first time but if  I update links with stoke or display property it seems that it doesn't get reflected in HTML template.

Is there anyone responsible for ngx-graph library that I can contact to get some feedback. All issues seem to be left without any response :(

**Comment by marjan-georgiev** [comment]
@Maciejszuchta you just opened this issue an hour ago. Please give us some time to respond.

To answer your question, the ngx-graph component uses `ChangeDetectionStrategy.OnPush`, so when updating data, you need to pass the chart immutable data in order for it to detect changes.
